### ISSUE TITLE
GiderosAndroidPlayer.apk black screen output only? 

### ISSUE THREAD

**Issue by FuzzyDweeb** [gideros/gideros#10]
Gideros Android Player 2015.02 .apk ...same problem as iOS player?
![photo on 01-03-2015 at 10 59 am](https://cloud.githubusercontent.com/assets/9529552/6430451/65688aea-c002-11e4-9a11-42e73a34607e.jpg)

**Comment by FuzzyDweeb** [comment]
^Samsung Note 4 used.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/gideros/gideros/commit/06d391ca0b90c6cf5893c2042bd4721046d9e103
