### ISSUE TITLE
Ads plugin needs updating

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#101]
AppLovin have updated to v6 of their lib (download the lib from AppLovin).

As a result, the code to interface to the lib won't work anymore.   It was an easy fix however...

Here is the code for the fix for the Gideros ads plugin:
http://www.sinistersoft.com/downloads/AdsApplovin.java

The version of github needs to be updated...

**Comment by FuzzyDweeb** [comment]
Superb and cheers! :D

**Comment by ar2rsawseen** [comment]
Updated here:
https://github.com/gideros/gideros/commit/1d65ac4d8d536b121f88d76cf260879cec241959
