### ISSUE TITLE
Sound sample looping not working on windows exports

### ISSUE THREAD

**Issue by FuzzyDweeb** [gideros/gideros#106]
Sound samples that loop only play back once and not repeatedly on windows exports from gideros to visual studio projects.

**Comment by FuzzyDweeb** [comment]
Example:

This normally loops a sound on IOS/Android but doesn't on Windows Phone...

Channel=sSample_Loop:play(0,math.huge)

**Comment by john-blackburn** [comment]
Fixed in 3c258ecd1e8abac75daabce420aa1b710569304d

**Comment by FuzzyDweeb** [comment]
Cheers John

**Comment by john-blackburn** [comment]
Btw, these days you should do Sample_Loop:play(0,true) to make it loop. That's what the official docs say. But using math.huge still works.

**Comment by FuzzyDweeb** [comment]
Ah OK cheers John
