### ISSUE TITLE
Mac Desktop Export: Resize Window

### ISSUE THREAD

**Issue by Kellog** [gideros/gideros#109]
The resizing of the application window is always disabled.

There should be an option to allow users to resize the window with the aspect ratio remaining intact.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/gideros/gideros/commit/bd6c59185e4be3eaad20cbc1e8a06c82fbfb63b9

Resizing allowed when window size in Gideros project properties set to 0 (as in auto) if there is a specific size set, then only this size and fullscreen mode allowed
