### ISSUE TITLE
SoundChannel stereo functionality

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#112]
Ability to control left/right channel volume of a SoundChannel object independently.

Useful in platform games to make the player aware of sprites out of view (as well as improving the experience in general).

**Comment by ar2rsawseen** [comment]
I know that Gideros internally uses OpenAL (except winrt uses xAduio)
example:
https://github.com/gideros/gideros/blob/f2e10f4499f0d8e10eb159fef26b832aebbd8b88/libgid/src/qt/gaudio-qt.cpp

so first step is to find how to implement the same functionality in OpenAL and xAudio :)

**Comment by SinisterSoft** [comment]
btw, possible soln. to Android latency issue at the bottom of this thread:

https://code.google.com/p/apportable/issues/detail?id=637

**Comment by hgy29** [comment]
SoundChannel now has setWorldPosition(x,y,z,vx,vy,vz) to position the sound channel in a 3D environment, this solves the issue for all platforms but WinRT.

**Comment by totebo** [comment]
WOW!
