### ISSUE TITLE
Problems exporting desktop MacOs

### ISSUE THREAD

**Issue by yubaro** [gideros/gideros#115]
Perhaps also Windows. It seems problems with the length of characters in Organization.

With a length of 9 characters or less in Organization (with and without space) works fine.

With 10 characters or more:
classes/dataSaver.lua:41: attempt to index local 'file' (a nil value)
stack traceback:
	classes/dataSaver.lua:41: in function 'saveValue'

**Comment by ar2rsawseen** [comment]
question is, do Apple limit developer organization length? Because those two should match for app to be accepted per Apple policy

**Comment by ar2rsawseen** [comment]
@yubaro do you provide anything in organization domain field?

**Comment by yubaro** [comment]
@ar2rsawseen, both in organization and domain, my names are long, Apple will reject my application.
If the fields are empty, works fine.

**Comment by ar2rsawseen** [comment]
if fields are empty it uses GiderosMobile Organization info

how long are your org and domain names?

**Comment by yubaro** [comment]
My Apple Account is personal and that organization is my full name, is long, 20 characters with spaces.

**Comment by yubaro** [comment]
@ar2rsawseen, in Mac Desktop export with the new version 2015.07.15, the .app not working, quits unexpectedly when trying to start. This did not happen in the previous version, in the previous version works fine.

**Comment by ar2rsawseen** [comment]
The only changes were basically paths changed and some resolution stuff.

Do you get any error stack to share, to see what is happening?

**Comment by yubaro** [comment]
Yes @ar2rsawseen,

Crashed Thread:        0  Dispatch queue: com.apple.main-thread
 
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
 
Application Specific Information:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error (1000) creating CGSWindow on line 281'
terminating with uncaught exception of type NSException
abort() called

**Comment by tkhnoman** [comment]
I believe it was just error on building.
My build on my PC works just fine.

**Comment by tkhnoman** [comment]
This is the MacOS template build, copy and paste it inside Gideros Studio (show packages) / Contents / Templates / Qt / MacOSXDesktopTemplate.

http://www.mediafire.com/download/i2154w8r21c2pt4/MacOSXDesktopTemplate.app.zip

Not forget to mention, it does not contain any plugin (like controller, and such), i just raw build.

**Comment by yubaro** [comment]
@tkhnoman the error continues. With the new template(MacOSXDesktopTemplate.app) remains the problem now with any size of characters.

**Comment by tkhnoman** [comment]
Confirmed by yubaro that this issue is fixed

**Comment by ar2rsawseen** [comment]
Thanks ;)

**Comment by yubaro** [comment]
Hi guys, sorry for this, but I just realize my name, there is now the same problem but with great characters separated.
In my case I write in organization: Name Lastname(father) LastName(mother)
And the error above comes again.
Any solution?
One question, what is the right thing to write in organization and domain?Which is correct?

Thanks
