### ISSUE TITLE
application:setWindowSize() bug

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#117]
application:setWindowSize() on Windows Desktop Export now have some kind of weird bug.
I'm not sure how to say this, in my testcode, i have 4 button that called these:
application:setWindowSize(576, 1024)
application:setWindowSize(720, 1280)
application:setWindowSize(900, 1600)
application:setWindowSize(1080, 1920)

Sometime the window won't change when i change between them, i wonder why.

My Window Size and Logical dimension are both 576 x 1024, and application:setLogicalDimensions(1080, 1920)

**Comment by tkhnoman** [comment]
New thing i found, 
When it won't change, it somehow changed when i move the window...

**Comment by ar2rsawseen** [comment]
ok great, then it could be somekind of redrawing or similar event, I will test it more thoroughly ;)

**Comment by tkhnoman** [comment]
This is fixed on my pull request, and can be closed if it's pulled

**Comment by ar2rsawseen** [comment]
Merged, thanks ;)
https://github.com/gideros/gideros/pull/118
