### ISSUE TITLE
bring to front

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#12]
antix:
What would be totally fantastic however is if when you press the play button in Gideros Studio, and if the player is on the local machine then it brings the player window to the front.

**Comment by ar2rsawseen** [comment]
While theoretically this is implemented in https://github.com/gideros/gideros/commit/eac568f38c16d3ce3e1a8f26edc1cfeaf43e3387

due to OS restrictions, unfortunately it probably won't work as expected

in Windows 8 even Always on Top is not working anymore due to OS limitations

**Comment by SinisterSoft** [comment]
Making it the active window should work?

**Comment by ar2rsawseen** [comment]
Nope, OS limitation

http://doc-snapshot.qt-project.org/qt5-5.4/qwidget.html#activateWindow
