### ISSUE TITLE
Saved exported Window position on .ini

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#120]
Just like Player, position and size should be saved on .ini file

Screen also should be centered on first run (or probably easier at 0,0)

**Comment by tkhnoman** [comment]
I'm working on this issue myself. Closed.

**Comment by ar2rsawseen** [comment]
Great, if you have any questions, let me know.
In player QSettings class is used for that purpose

Which should be initialized after setting organization:
https://github.com/gideros/gideros/blob/22aae4300593a66b8f4223772bef7fc5574b4733/player/Sources/main.cpp#L59

And then can be used like this:
https://github.com/gideros/gideros/blob/f2e10f4499f0d8e10eb159fef26b832aebbd8b88/ui/playersettingsdialog.cpp#L33-L36

If you have any questions, let me know ;)

http://doc.qt.io/qt-5/qsettings.html

**Comment by tkhnoman** [comment]
Thanks.

Actually, it's already done.
I just need some retesting before pull request.
