### ISSUE TITLE
Controller lib crashes on Android

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#122]
If you set the API to 21 then the controller lib crashes on Android.

**Comment by ar2rsawseen** [comment]
I remember you provided some info which almost made sense (like a logcat or something) is it still available?

**Comment by ar2rsawseen** [comment]
Found it:
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI GetStaticMethodID called with pending exception 'java.lang.IllegalArgumentException' thrown in unknown throw location
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]     in call to GetStaticMethodID
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]     from void com.giderosmobile.android.player.GiderosApplication.nativeDrawFrame()
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65] "GLThread 12582" prio=5 tid=14 Runnable
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12cbb220 self=0xb899daa8
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | sysTid=29151 nice=0 cgrp=apps sched=0/0 handle=0xb899e040
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=1099 stm=96 core=2 HZ=100
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | stack=0xa0eba000-0xa0ebc000 stackSize=1036KB
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #00 pc 00004828  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #01 pc 00002ec5  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #02 pc 0024441d  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #03 pc 002277eb  /system/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+394)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #04 pc 000af2b3  /system/lib/libart.so (art::JniAbort(char const*, char const*)+582)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #05 pc 000af9f9  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #06 pc 000b2b73  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv*, int, char const*)+1286)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #07 pc 000b4e53  /system/lib/libart.so (art::CheckJNI::GetStaticMethodID(_JNIEnv*, _jclass*, char const*, char const*)+26)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #08 pc 00005804  /data/app/com.sinistersoft.superhero-1/lib/arm/libcontroller.so (ghid_isAnyAvailable+52)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #09 pc 00006218  /data/app/com.sinistersoft.superhero-1/lib/arm/libcontroller.so (???)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #10 pc 00007188  /data/app/com.sinistersoft.superhero-1/lib/arm/liblua.so (???)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at com.giderosmobile.android.player.GiderosApplication.nativeDrawFrame(Native method)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at com.giderosmobile.android.player.GiderosApplication.onDrawFrame(GiderosApplication.java:557)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   - locked <0x2d6fa7f4> (a java.lang.Object)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at com.giderosmobile.android.GiderosRenderer.onDrawFrame(SuperheroActivity.java:290)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65] 
07-16 20:20:45.184: A/libc(29132): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 29151 (GLThread 12582)
07-16 20:20:45.184: W/libc(29132): Security Level: (1), Debug inforamtion is controlled by the DUMPABLE flag.

**Comment by SinisterSoft** [comment]
New crash?
On 8 Sep 2015 14:02, Arturs Sosins <notifications@github.com> wrote:Found it:
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: JNI GetStaticMethodID called with pending exception 'java.lang.IllegalArgumentException' thrown in unknown throw location
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]     in call to GetStaticMethodID
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]     from void com.giderosmobile.android.player.GiderosApplication.nativeDrawFrame()
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65] "GLThread 12582" prio=5 tid=14 Runnable
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x12cbb220 self=0xb899daa8
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | sysTid=29151 nice=0 cgrp=apps sched=0/0 handle=0xb899e040
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=1099 stm=96 core=2 HZ=100
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | stack=0xa0eba000-0xa0ebc000 stackSize=1036KB
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #00 pc 00004828  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext)+23)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #1 pc 00002ec5  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext)+8)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #2 pc 0024441d  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream >&, int, char const, art::mirror::ArtMethod)+68)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #3 pc 002277eb  /system/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream >&) const+394)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #4 pc 000af2b3  /system/lib/libart.so (art::JniAbort(char const, char const)+582)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #5 pc 000af9f9  /system/lib/libart.so (art::JniAbortF(char const, char const, ...)+60)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #6 pc 000b2b73  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv, int, char const)+1286)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #7 pc 000b4e53  /system/lib/libart.so (art::CheckJNI::GetStaticMethodID(_JNIEnv, _jclass, char const, char const)+26)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #8 pc 00005804  /data/app/com.sinistersoft.superhero-1/lib/arm/libcontroller.so (ghid_isAnyAvailable+52)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #9 pc 00006218  /data/app/com.sinistersoft.superhero-1/lib/arm/libcontroller.so (???)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   native: #10 pc 00007188  /data/app/com.sinistersoft.superhero-1/lib/arm/liblua.so (???)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at com.giderosmobile.android.player.GiderosApplication.nativeDrawFrame(Native method)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at com.giderosmobile.android.player.GiderosApplication.onDrawFrame(GiderosApplication.java:557)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   - locked <0x2d6fa7f4> (a java.lang.Object)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at com.giderosmobile.android.GiderosRenderer.onDrawFrame(SuperheroActivity.java:290)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1522)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65]   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
07-16 20:20:45.144: A/art(29132): art/runtime/check_jni.cc:65] 
07-16 20:20:45.184: A/libc(29132): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x3c in tid 29151 (GLThread 12582)
07-16 20:20:45.184: W/libc(29132): Security Level: (1), Debug inforamtion is controlled by the DUMPABLE flag.

**Comment by ar2rsawseen** [comment]
No I think thats the same crash you created issue for

**Comment by hgy29** [comment]
@SinisterSoft : is this still an issue today ?

**Comment by SinisterSoft** [comment]
I'm not sure.  I'll publish an update and let you know for next revision.

On 03/07/2018 13:47:09, Nicolas Bouquet <notifications@github.com> wrote:
@SinisterSoft [https://github.com/SinisterSoft] : is this still an issue today ?

**Comment by SinisterSoft** [comment]
Tested with API set to 26 and on latest release - no longer an issue.
