### ISSUE TITLE
[WinRT] Unable to disable texture filtering

### ISSUE THREAD

**Issue by dcr30** [gideros/gideros#123]
Texture filtering is enabled by default on Windows Phone unlike in other platforms where it's disabled.
It can't be disabled when creating new texture.

**Comment by ar2rsawseen** [comment]
It could be just the way how DirectX is dealing with Textures
What do you think @john-blackburn ?

**Comment by dcr30** [comment]
Filtering is still enabled and can't be disabled even when it's set to "false" when creating texture in Gideros 2015.08:

Here are some screenshots from my device.
![Screenshot 1](http://i.imgur.com/KXPAbCy.png)
![Screenshot 2](http://i.imgur.com/8VsdYvs.png)

**Comment by hgy29** [comment]
Hmm, re-checked code in 2015.08 and it should now not enforce filtering any more. I am starting to think that Windows Display scaling may apply filtering on the whole framebuffer when upscaling to actual pixels. @john-blackburn what do you think ?
@dcr30 does enabling filtering on textures changes the aspect of the rendered image in some way ? Is there some visible difference or nothing at all ?

**Comment by dcr30** [comment]
```lua
-- No filtering
local texture1 = Texture.new("assets/player1.png", false)
local bitmap1 = Bitmap.new(texture1)
bitmap1:setScale(10)
stage:addChild(bitmap1)

-- Filtering enabled
local texture2 = Texture.new("assets/player1.png", true)
local bitmap2 = Bitmap.new(texture2)
bitmap2:setScale(10)
bitmap2:setX(bitmap1:getWidth())
stage:addChild(bitmap2)
```

![Imgur](http://i.imgur.com/JicXBpS.png)

I don't see any difference here

**Comment by hgy29** [comment]
Fixed (and verified!)
