### ISSUE TITLE
A way is needed of finding the font base of the default font

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#125]
The default font is 'nil', but in order to use text handling commands you need it's fontbase (nil can't be used).

There is a routine in the source code that may need exposing to lua somehow:

Font* Application::getDefaultFont()
{
 if (defaultFont_ == NULL)
  defaultFont_ = new Font(this);

 return defaultFont_;
}

**Comment by hgy29** [comment]
I added a method in Font class (lua bindiing) to get gideros embedded font: Font.getdefault()
