### ISSUE TITLE
Desktop export does not respect "Window size" setting in properties

### ISSUE THREAD

**Issue by john-blackburn** [gideros/gideros#134]
The size of the desktop export window is currently dictated by the gdrpos.ini file in the projects directory. This means the window will reopen at whatever size the user resized it to be when previously playing the game. This is not correct. If the developer sets "Window size" at non-zero in the properties the exported project should open at this size.

In general, I think gdrpos.ini should not be read by the desktop export project as this can lead to many problems (eg the user could manoeuvre the window off the screen and be unable to play the game again). The desktop export window should start at (0,0) position and be the size specified in the Gideros Studio properties panel: either a fixed size if given, or, if "window size" was set to (0,0), it should be the game's logical size.

**Comment by john-blackburn** [comment]
@tkhnoman , could you look into this? I think an exported desktop game should not read gdrpos.ini. Instead it should open at the size specified by user.

**Comment by tkhnoman** [comment]
I just tried to imitate standard game behavior, but i guess, we should just let user do that.
I will remove it.

Regarding started on (0,0), it was changed before i tried pull request, and it was changed that top left of the window is in the center of the screen, which make it broken if i used big res.

I will change it to 0,0

**Comment by tkhnoman** [comment]
Well, I agreed to change these because now we can do application:set, which means we can change position as our will. In before, this was not presented on API. :)

**Comment by john-blackburn** [comment]
I think gdrpos.ini is a resource the Lua programs can read if they want. But it should not be read automatically by the exported desktop player. For one thing it becomes very confusing for the developer, if he re-exports multiple times, perhaps with different versions of Gideros, behaviour depends on what was done previously. 

You can also get a case where the desktop app launches with a zero-sized window if gdrpos.ini is not present in Documents. This can happen if they user previously exported with an old version of Gideros.

**Comment by tkhnoman** [comment]
I think i will just remove it completely.
User can just use APPLICATION_EXIT to save pos and size of window themselves now, so it should not be a problem

**Comment by john-blackburn** [comment]
yes, that's probably the cleanest way
