### ISSUE TITLE
Add a trakker playback system

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#137]
In order to use smaller music files or even create music directly within an app then something like:

http://xmp.sourceforge.net/

Should be added asa music playback system.

It would be great to be able to create music actually from winthin a Gideros app!

**Comment by totebo** [comment]
.mod! +1

**Comment by hgy29** [comment]
Done for all platforms (except newest win32 export)

**Comment by hgy29** [comment]
Maybe we can close this issue now, the trakker playback engine has been in for years :)
