### ISSUE TITLE
b2.World:setDebugDraw() sprite is misaligned if its holding sprite is moved

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#138]
Please see detailed explanation:
http://giderosmobile.com/forum/discussion/comment/42157#Comment_42157

**Comment by hgy29** [comment]
Probably due to wrong order of matrix multiplication when applying physics scale. Investigating right now...

**Comment by hgy29** [comment]
Fixed! Was a matrix pre/post multiply issue, it only affected debug drawing

**Comment by totebo** [comment]
Wow! Great!
