### ISSUE TITLE
Gameplay recording...

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#142]
A plugin lib for Kamcord would be great, it looks better than Everplay.

https://docs.kamcord.com/documents/platform/android/the-native-c-interface/

**Comment by totebo** [comment]
+1, including ReplayKit for iOS 9: https://developer.apple.com/ios/pre-release/

**Comment by SinisterSoft** [comment]
Megacool looks like a better solution to this as it's cross platform.
