### ISSUE TITLE
Improved print() function

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#145]
Add extra columns to make debugging easier. For each print, these extra columns could also be included:

- Timestamp
- File (class) name
- Line number the print command was invoked from

**Comment by tkhnoman** [comment]
@totebo these can be added by yourself, even for the line number.
Just create another function that called print for it.

I don't see anything good from these, because it might disturb our usual print routine.

**Comment by tkhnoman** [comment]
function _print(text)
	print(text,os.date("%H")..":"..os.date("%M")..":"..os.date("%S"),debug.getinfo(2).short_src..":"..debug.getinfo(2).currentline)
end

**Comment by totebo** [comment]
Awesome, problem solved! This can be removed.

**Comment by ar2rsawseen** [comment]
Do you think it should be added by default?

**Comment by totebo** [comment]
Probably not; let's leave it optional. I'm using Print excessively, but for
those who don't rely on it, the extra info might be annoying.

**Comment by tkhnoman** [comment]
I sometime use print for drawing a table, this would be bad for that. So please don't.

**Comment by ar2rsawseen** [comment]
Ok, then closing this issue
