### ISSUE TITLE
Support for pressure sensitive displays

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#146]
Event to return event.touch.pressure, returning 0 before full implementation.

**Comment by tkhnoman** [comment]
i will handle this now, will do pull request in a moment.
(not forget to mention, i won't check the output)

**Comment by keszegh** [comment]
obviously the desktop (wacom) part is the harder, but i thought i will note that the android part should not be forgotten too.
(i guess you did not forget about it, but repeating cannot harm)

**Comment by ar2rsawseen** [comment]
I think @tkhnoman added it to desktop and I just added it to android

https://github.com/gideros/gideros/commit/a8b0c57fe3bdee3fc208013781d1cf9271aa115c

**Comment by ar2rsawseen** [comment]
and for ios
https://github.com/gideros/gideros/commit/d1e0e7354ced1793e784b2feaf8cb051ca3f9e82

**Comment by ar2rsawseen** [comment]
is anything left?

**Comment by keszegh** [comment]
thanks a lot, if all these work, then only html5 is left...
