### ISSUE TITLE
hide cursor and custom cursors

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#147]
possibility to hide cursor on desktop (and provide our own).
additional possibility: custom cursors as provided by @tkhnoman, see http://giderosmobile.com/forum/discussion/5870/new-desktop-api-test/p1

**Comment by tkhnoman** [comment]
This is already possible. To hide cursor, you can use "blank".

**Comment by keszegh** [comment]
great, in my code it was still application:setDesktopProperty(..) which did not work. i realized now that at the end it's simply a set function. so it works now.
