### ISSUE TITLE
fit giderosplayer window to app

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#15]
there should be a button/short-cut to achieve the opposite of fit to window, i.e. to fit window size to the exact size of the app. in old giderosplayer that was possible as shrinking as much as possible the player one could achieve this, but now the player can be shrinked as small as you want (which otherwise is a good thing), so this 'feature' is lost.

**Comment by ar2rsawseen** [comment]
Implemented in https://github.com/gideros/gideros/commit/aa9518f4c8d26a47ba00a5e47899796b7c27ee04
