### ISSUE TITLE
behaviour after fullscreen

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#153]
on desktop gideros player (and maybe exported desktop app too) when setting setfullscreen true and then false then the 'autoscale'ing of the gideros player is ruined, it will become fixed window size.
( turning off/on autoscale in the menu corrects this.)

**Comment by ar2rsawseen** [comment]
So it is happening only on player?

**Comment by keszegh** [comment]
yes, in qt export it works fine. in win32 export fullscreen did not even seem to work. and in win player it behaves like explained above.

**Comment by john-blackburn** [comment]
Thanks for the comment also about win32. I need to work on the fullscreen aspect of this. I did write some code but am not very happy with it.

**Comment by keszegh** [comment]
on win32 setFullScreen(true) still does not work, while it would be very important to publish Windows games without using QT.

**Comment by mokalux** [comment]
setfullscreen is working now on windows (tested with windows 10).

You may want to close this issue?

**Comment by hgy29** [comment]
Agreed, a fix was made for this two years ago. Closing.
