### ISSUE TITLE
Feature Request: Export: add options to set icon, signing and zipalign (Android)

### ISSUE THREAD

**Issue by mydoghasworms** [gideros/gideros#156]
For the export, it would be nice if, on the project properties, one could add an icon that will be exported together with the project. I am assuming this would work for Android and iOS?

**EDIT** - I forgot about the build. It would be nice if Gideros Studio could automate the build as well, although if you did it for one platform, you would have to do it for all of them so the others don't feel left out ;-) Although it would be nice, and required for the following to work as well:

For the Android export, it would be nice to be able to specify the keyfile for signing and have the Android template include the build instructions to perform both the signing and zipalign so that these steps do not have to be done manually after the export.

**Comment by hgy29** [comment]
On its way into Gideros 2016.02 :) Gideros will be able to output signed APK (with app icon), by calling android tools. It will needs android sdk, java and apache ant installed.

**Comment by mydoghasworms** [comment]
:clap: :tada: That is excellent news, thanks!

**Comment by hgy29** [comment]
Fixed with APK export :)
