### ISSUE TITLE
exported windows apps seem to have the same documents folder

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#161]
c:\Users\username\AppData\Roaming\giderosgame\
seems to be generic, so i guess it remains the same for more gideros games and then they will overlap.

**Comment by john-blackburn** [comment]
You are right, but this happens only for the new win32 release which is in alpha. For the "regular" Windows Desktop export (Qt based) it should go in its own folder depending on the company name you used when exporting. I will fix these by beta release.

**Comment by keszegh** [comment]
it looks you are right.

**Comment by hgy29** [comment]
should be fixed by now
