### ISSUE TITLE
Mac OSX export bundle identifier

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#163]
Info.plist key for CFBundleIdentifier still use com.yourcompany.#appname#
Better that if it's replaced with just "bundle" and not domain.

CFBundleShortVersionString and CFBundleVersion also needed for Mac OS X export, and should be included in export option also.

**Comment by tkhnoman** [comment]
I also don't know how to handle info.plist at MacOSX

**Comment by ar2rsawseen** [comment]
aha, was not aware of them. I will add these string to be replaced upon export

**Comment by ar2rsawseen** [comment]
btw, is there any list of all mandatory keys/values, that should be present?

**Comment by tkhnoman** [comment]
After looking at it more, i'm not sure myself about uploading to Mac AppStore.
I don't think it would be accepted, since we did not code sign the app upon export.

**Comment by ar2rsawseen** [comment]
yes, of course it needs to be codesigned, and not just executable, but every dynamic lib inside I think
but lets take it step by step and deal with bundle stuff at first

**Comment by ar2rsawseen** [comment]
putting it here for reference:
http://stackoverflow.com/a/25713297

**Comment by ar2rsawseen** [comment]
And also this one
http://abstractingreality.com/2014/03/27/deploying-qt-5-app-mac-app-store/

**Comment by ar2rsawseen** [comment]
I've now actually added all to export, including needed info like bundle and version, as well as codesigning and creating package on export. After verifying, all seems to be signed correctly. Will try to submit it to Mac Appstore later on :)

**Comment by john-blackburn** [comment]
This is great work!

-----Original Message-----

**Comment by ar2rsawseen** [comment]
After view more adjustments, like missing keys and Entitlements file I was able to submit my app to Mac Appstore :)

Most probably it won't be accepted due to error on exit bug that we are still experiencing, but all in all, it is now possible to submit the app

**Comment by yubaro** [comment]
@ar2rsawseen Are approved or rejected your submission in Mac AppStore?

**Comment by ar2rsawseen** [comment]
Rejected, apart from exit crash, there was also issue with icon sizes. Would need to think on that too :)

but it should be possible to change icns after export and run product build again. And maybe exit bug is already fixed, don't know, did not try to build from sources yet
