### ISSUE TITLE
Scale problem at main Gideros Studio window(Windows 8.1 pro)

### ISSUE THREAD

**Issue by unlying** [gideros/gideros#166]
![image 1](https://cloud.githubusercontent.com/assets/11470069/10129869/a5e869d6-65cb-11e5-8901-89151b004df8.png)

**Comment by unlying** [comment]
Macbook pro 2880x1800

**Comment by GregBreinholt** [comment]
![capturegideros](https://cloud.githubusercontent.com/assets/6941844/10130077/a4b4b34a-65f7-11e5-8b9a-8303f4e437f1.PNG)

Same on Windows with a 3200x1800 resolution Blade, with screen scaling set to Recommended.

**Comment by SinisterSoft** [comment]
Same on Intel 3200x1800 Ultrabook platform sample.
