### ISSUE TITLE
Vector support

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#168]
Support to load EPS and/or SVG vector graphics into Gideros, or other formats that make more sense.

**Comment by keszegh** [comment]
svg is maybe more common for graphics creators, and checking out how others did might help also:
https://github.com/openfl/svg
also swf is an interesting option:
https://github.com/openfl/swf

but both of these require a non-trivial effort i guess. but who knows, some of us remember the wild dreams we had:
http://tmblr.co/Z0Xaus1C-YhEt

**Comment by totebo** [comment]
Exactly! Thought I'd add it, because it would be a great feature for a 2D game tool.

**Comment by hgy29** [comment]
In fact, I already begun to intergate optimized vector graphics support in gideros, based on @atilimcetin previous work. The main reason is that it is way faster than shapes, and will be useful for rendering TT fonts efficiently. TTFonts are way too slow as of today. However it requires adding stenciling support in GL/DX11, new dedicated shaders, and perhaps a new API for those Sprites...

I am planning to add it as part of my ongoing kickstarter, with SVG support.

**Comment by totebo** [comment]
Yay!
