### ISSUE TITLE
object functions should work for user made classes

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#169]
MyClass=gideros.class(Sprite)

function MyClass:init()
  print(self:isInstanceOf("MyClass"))  
  print(self:getClass())
end

myClass=MyClass.new()

this code should print:
true
MyClass
whereas it prints:
false
Sprite

**Comment by ar2rsawseen** [comment]
Problem is that they have those functions and they work, unfortunately not the way you expect them to work. :)

They can't know their names, for example.

local a = function() end

a contains function, but function does not know the name of the variable it is stored in (it can even be stored in many variables at once).

same case MyClass, we can't know the name of the variable where you store the value (in this case class is the value you store in MyClass variable). There are some method to know that, but they are inefficient and are not error prone, may not work in some or many cases.

But what you could do, is to overwrite it yourself, like this should work:
function MyClass:init()
    self.__classname = "MyClass"
    print(self:getClass()) --should print MyClass
end

**Comment by keszegh** [comment]
i see, so that's not much more then providing a variable "__classname" for each core class that stores its name and we can do that for our classes too. it should be in the documentation then that __classname stores this name, or provide a ~setClass function to set it.

**Comment by ar2rsawseen** [comment]
Problem is, that it was a quick addition before release, and we are still thinking on continuous usage, etc, so for example, maybe we could do

MyClass  = Core.class(Sprite, "MyClass")
