### ISSUE TITLE
memory leak from Gideros 2015.08 onward

### ISSUE THREAD

**Issue by billydb** [gideros/gideros#171]
Found a memory leak that only appears from 2015.08 version onwards. Tested with project including scene manager, movieclips, sounds, texture packs, tilemaps. Disabled individual parts to test (without luck) except for sceneManager and it's possible there were still some instances of the movieclip class.

**Comment by hgy29** [comment]
Can you provide a sample project that shows the issue ? I'll try to understand what happens.
Could be VBO as @john-blackburn pointed out, though I don't believe it, but it could well be MovieClip too, since its code is less easily understantable and thus error prone.
You said you used leaky: did it show unfreed lua objects ? If so then its probably a MovieClip issue...

**Comment by hgy29** [comment]
After reading again MovieClip changes, since 2015.08 MovieClip now keeps a reference to each lua Sprite involved in a tween, refs are freed when MovieClip object is freed. Could it be that your code keep references on the MovieClips ? It would be good if you could share what leaky tells you.

**Comment by billydb** [comment]
Hi, yes I will re install the latest Gideros and check in a bit and share
what leaky says. Also I think the crashes I was getting were due to leaky:)
It is entirely possible its a movieclip issue as I use them all over the
place. The latest change to that was creating "complete" events that would
then trigger sounds or set the next stage of the animation.
Here's a snippet:


--inside a "createTween" function called from the init function of the
level...
*local tween = MovieClip.new{*
* {d1,d2,tweenSprite,{y = {t1Start,t1Start,child._tweenEase}}},*
* {t1A,t1B,tweenSprite,{y = {t1Start,t1End,child._tweenEase}}},*
* {t2A,t2B,tweenSprite,{y = {t1End ,t1End ,child._tweenEase}}},*--stops
here then to trigger sound
* {t3A,t3B,tweenSprite,{y = {t1End ,t1Start,child._tweenEase}}},*
* {t4A,t4B,tweenSprite,{y = {t1Start,t1Start,child._tweenEase}}}*
* }*
* tween:setStopAction(t2B)*

*tween:addEventListener("complete",self.tweenLoop,self,tween)*

--the tween movieclip is added to a table called self.tweens




*function level:tweenLoop(event)*
* local tween = event:getTarget()*
* local child = tween.child*
* if tween.partOne == true then*
* tween:clearAction(tween.midFrame)*
* tween:gotoAndPlay(tween.midFrame)*
* tween.partOne = false*
* if not self.ball.dead then*
* if child._soundAtLoop then*
* self.soundFx:play(child,child:getX(),child:getY())*
* end*
* end*
* else*
* tween:setStopAction(tween.midFrame)*
* tween:gotoAndPlay(tween.startFrame)*
* tween.partOne = true*
* if not self.ball.dead then*
* if child._soundAtEnd then*
* self.soundFx:play(child,child:getX(),child:getY())*
* end*
* end*
* end*
*end*



--when exiting the level...

function level:onExitBegin()

self.tiledLevel.onExitBegin()
self.tiledLevel.B2_Worlds[1]:removeEventListener(Event.BEGIN_CONTACT,
self.onPreSolve, self)
self.tiledLevel.B2_Worlds[1]:removeEventListener(Event.BEGIN_CONTACT,
self.onBeginContact)
self.tiledLevel.B2_Worlds[1]:removeEventListener(Event.END_CONTACT,
self.onEndContact)
self:removeChild(self.tiledLevel)
self.ball:onExitBegin(self.ball)
*self.soundFx:reset()*
*for i = 1, #self.tweenSprites do*
* local spr = self.tweenSprites[i]*
* local tween = self.tweens[i]*
* tween:removeEventListener("complete",self.tweenLoop,self,tween)*
* tween:removeEventListener("complete",self.tweenComplete,self,tween) *
* end*
end


--the loop should just be going through the self.tweens table but that and
the self.tweenSprites table are always the same size so it should still
work. I'll change it but left it here encase it could be breaking in some
way i'm not aware of.
Also the sound fx created during the tween complete event (i just included
the whole thing as it's not too huge):

soundFx = gideros.class(Sprite)


function soundFx:init()
self.soundsPlaying = {}
end

function soundFx:update(lvlSelf)
for i = 1, #self.soundsPlaying do
local snd = self.soundsPlaying[i]
local dist = (getDistance(lvlSelf.ball.cX,lvlSelf.ball.cY
,snd.x,snd.y))/400000
local volume = 1 - dist
if volume < 0 then volume = 0 end
snd:setVolume(volume)
end
end

*function soundFx:play(child,x,y)*
* local channel = sounds[child._sound]:play()*
* --print(#self.soundsPlaying + 1)*
* table.insert(self.soundsPlaying,channel)*
* channel.x = x*
* channel.y = y*
* --print("no of sounds is ",#self.soundsPlaying)*
* channel.index = #self.soundsPlaying*
* if child._soundLoop then *
* channel:setLooping(true)*
* print(child._sound)*
* else*
* channel:addEventListener("complete",self.onComplete,self,channel)*
* end*
*end*

function soundFx:onComplete(event)
local index = event:getTarget().index
self.soundsPlaying[index]:removeEventListener("complete",self.onComplete,self,channel)
table.remove(self.soundsPlaying,index)
for i = 1, #self.soundsPlaying do
local snd = self.soundsPlaying[i]
snd.index = i
end
end

function soundFx:reset(event)
for i = 1, #self.soundsPlaying do
local snd = self.soundsPlaying[i]
snd:removeEventListener("complete",self.onComplete,self,channel)
snd:stop()
end
self.soundsPlaying = {}
collectgarbage()
end


Thanks

**Comment by billydb** [comment]
I've attached a stripped down project that shows the leak and below is what
I was getting when moving from scene 1 to scene 2.
The leak disappears in Gideros_07_15 and earlier.
Give me a shout if I can do anything else to help.


Uploading finished.

MODIFIED classes.lua INITIALISED

*** OBJECT SNAPSHOT message here ***

SceneManager has 1 instances

*start has 1 instances*

*** OBJECT SNAPSHOT END ****

*** OBJECT SNAPSHOT message here ***

SceneManager has 1 instances

*start has 2 instances*

level_select has 1 instances

*** OBJECT SNAPSHOT END ****

*** OBJECT SNAPSHOT message here ***

SceneManager has 1 instances

*start has 3 instances*

*level_select has 2 instances*

*** OBJECT SNAPSHOT END ****

*** OBJECT SNAPSHOT message here ***

SceneManager has 1 instances

*start has 4 instances*

*level_select has 3 instances*

*** OBJECT SNAPSHOT END ****

*** OBJECT SNAPSHOT message here ***

SceneManager has 1 instances

*start has 5 instances*

*level_select has 4 instances*

*** OBJECT SNAPSHOT END ****

**Comment by hgy29** [comment]
I am not sure about how to interpret this. Obviously 'start' and 'level_select' have increasing instance count, is this the leak ? I'll understand better with the code I guess. You can post it in this issue's thread directly from github (https://github.com/gideros/gideros/issues/171).

**Comment by billydb** [comment]
Sorry I'm sure I'm being dense but I have the project in a zip, its around 300k, but I cant attach it to this discussion thread, it says it doesn't support this file format and I'm not sure how else to do it.

**Comment by hgy29** [comment]
Ok, then send it to me at hgygs@hieroglyphe.net

**Comment by totebo** [comment]
Dropbox it and post the link!

**Comment by hgy29** [comment]
Ok, got it :) Lets go for a debug session! I heavily suspect MovieClip...

**Comment by billydb** [comment]
yeh i'm guessing. I did a test with the scenemanager demo project and it
had no problems. I think movieclips are the only thing extra now in that
test project.

**Comment by billydb** [comment]
sorry i'm a complete dummy with this stuff (bodes well for my game huh :))

https://www.dropbox.com/s/tcv3a41qhjg4243/leakTest.zip?dl=0

**Comment by hgy29** [comment]
Ok, tracing through C code it looks like MovieClip destructor is never called (i.e. MovieClip are not garbage collected). Now I am wondering what would still reference them...

**Comment by hgy29** [comment]
Damn, there is a reference loop: your level_select, has a child 'start', which itself has an eventListener referencing the MovieClip, which itself reference the level_select... I suppose that since MovieClip is C code, it has strong references over lua object, and such loops can't be collected...

**Comment by billydb** [comment]
sorry i'm not following, is this a problem with my code or with the movie clips? I'm not sure what you mean by the level_select has a child called start, the only reference I can see to anything called start is the scene manager reference to the start class. If it is me is there something I can do to avoid this loop?

**Comment by billydb** [comment]
Hi hgh29, I'm guessing your super busy with the kickstarter but have you had a chance to look at this? I tried taking out the movieclip from the example and it still shows a leak when changing scene. Something in scene manager or more fundamental?

**Comment by hgy29** [comment]
I saw a possible issue with movieclip retaining hard refs to sprites, but if you say the problem persists even without movieclips then my theory doesn't fit anymore! And I didn't see any leak apart from sprites not been garbage collected due to movieclip ref loops...

**Comment by billydb** [comment]
Nope it's definitely MovieClip! Sorry I messed up and left a movieclip in the 2nd scene. Taking it out and memory leak is gone. I hope this is fixable :)

**Comment by john-blackburn** [comment]
Thanks for reporting this. It's very important we find and squash bugs like
this. I think there is now enough info to find this bug...

**Comment by billydb** [comment]
Yeh no worries, sorry I can't help more, bit out of my depth. I have noticed weird stuff with adding movieclips to a scene. I create a sprite and animate it with a movieclip, if i add the movieclip to the scene all is good, if i add the just the sprite it appears for a single frame and disappears, if i add it later in an enter frame event (using a bool so it doesn't keep getting added) it appears and stays but doesn't animate. I thought maybe the movieclip overwrites the sprites render but then the enter frame seems to overwrite that. Not a big problem but maybe it's related?
