### ISSUE TITLE
add filepicker for media plugin on desktop

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#173]
there should be a 'load' file picker which allows to choose a file and a 'save' file picker which allows to choose a folder and in it give any filename.

**Comment by tkhnoman** [comment]
It should be added on next update, and the command would be for example :
application:get("saveFileDialog","Save File|C:/|Text File (*.txt);;Image File (*.jpg *.png)

**Comment by keszegh** [comment]
thanks

**Comment by ar2rsawseen** [comment]
So closing this issue :)
