### ISSUE TITLE
3D issue in iOS player

### ISSUE THREAD

**Issue by Morozov-5F** [gideros/gideros#176]
It was a usual Tuesday. I wanted to test a simple example of 3D in iOS. I launched a built-in example with horse. On desktop player it was fine, but when i tried to launch it in iOS (on simulator and on my iPod) and then I realize that something is wrong with my little horse. I loved it very much, but it appears to be dead or so. 
<img width="1212" alt="2015-10-06 22 51 26" src="https://cloud.githubusercontent.com/assets/1385292/10320738/a31fcfd8-6c7d-11e5-8d8b-7464f9574178.png">
Ok, seriously, there is a REALLY big trouble with z-buffer in gideros player on iOS (check a screenshot). I tried two different versions of player and tried to export with different parameters. I am using an XCode 7. It's not only an example, I found this bug (or what?) in my game, I was up to release it to iOS (already released to winphone and android), every other platform is OK. So I run some tests and found out that.

**Comment by dcr30** [comment]
I'm having the same issue when trying to run my game in latest iOS player:

Windows:
![image](https://cloud.githubusercontent.com/assets/3995234/10324493/a20c65f6-6c92-11e5-8baa-550239d2ccc2.png)

iOS:
![image](https://cloud.githubusercontent.com/assets/3995234/10324477/8eff5734-6c92-11e5-8a4c-15937b625cf7.png)

**Comment by dcr30** [comment]
We've just found out that this bug is only happening in OS X El Capitan, no matter which version of XCode is used. So building Gideros Player on OS X Yosemite fixed it for us.

**Comment by Morozov-5F** [comment]
Nope, it still doesn't work. It randomly works in player (after player redeployment) but exported project doesn't seem to work. No way.

**Comment by Morozov-5F** [comment]
So, no info about that problem? That really freezes our development process. I'm pretty sure that it's our fault, but on Android deployment works pretty fine and game is already on play market. We were sure that iOS will be easy to publish to, but that kind of bug destroyed our plans.

**Comment by hgy29** [comment]
Hi, sorry for not getting in touch earlier. It would be weird that z buffer stopped working on iOS, a better explanation would be a frustum configuration issue. If you use perspective, did you explicitly set the far distance in configureFrustum ? Because if not, gideros computes a value which depends on your device's width and height, and it is often a bad idea. if possible, also set the near distance (new in 2015.9)

**Comment by Morozov-5F** [comment]
@hgy29 No, it doesn't fixed that. I think, the best example is default 3D Horse project. On player it works fine, but when it comes to native compilation via Xcode, it breaks things. It looks like that all far objects are near and all near are far. Same situation in our game: we were playing with different arguments to configureFrustum and game worked as expected in player, but all was messed up after Xcode compilation. I am a bit frustrated.

**Comment by hgy29** [comment]
Oh, so it works in iOS player but not in exported projrect ? I didn't get that! Then it must be that some code was done in the player but not in the Template. There are duplicate codes in Gideros source tree, and it wouldn't be the first time I forgot to add it in both places. I mostly check with the player only.
Let see that...

**Comment by hgy29** [comment]
So I found the bug! I have a PR waiting for approbation which icludes a fix for this.
