### ISSUE TITLE
Wrong path checked

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#191]
The virtual path should be checked for duplicate project entries rather than the original path.   The current method could cause one file to be overwritten by an other in the project by accident.

**Comment by hgy29** [comment]
Need to add a duplicate check somewhere around here:
https://github.com/gideros/gideros/blob/master/ui/librarytreewidget.cpp#L198

**Comment by ar2rsawseen** [comment]
I know you explained it in the group chat previously, but can you outline the problem here, it is hard to find it in chat history :)

**Comment by SinisterSoft** [comment]
When you add a file to a project then it's possible for two virtual files to be added that have the same filename - that is because the source name is checked for duplicates when adding a file - it should be the virtual name is checked for duplicates when adding a file instead.
