### ISSUE TITLE
IDE: Remove test devices from dropdown when they are disconnected

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#192]
The "start to all players" halts if a device has been removed. After a Gideros restart the devices are up-to-date and "start to all players" functions again.

**Comment by hgy29** [comment]
Fixed in: https://github.com/gideros/gideros/commit/bf41507cc66f64eefcada25915ec5180eaaaaf02

**Comment by totebo** [comment]
This doesn't work in v2015-12 on OSX. When a client leaves it remains in the IP dropdown list.

**Comment by hgy29** [comment]
Yes, 2015-12 was prepared before that fix.
