### ISSUE TITLE
Allow a generic set() method for MovieClip

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#194]
Allow a generic set() method for MovieClip to work on any object, not just Sprite. This would enable tweening any object, such as vertexes in a Mesh and Box2D bodies.

**Comment by ar2rsawseen** [comment]
MovieClip is meant for managing renderable objects. Thus it would accept sprites, but there is nothing stopping you from defining your own set method for Mesh (which is also sprite) to tween anything you want, either it would be mesh vertices or body attached as a sprite's propety

Or did I misunderstood your request?

**Comment by totebo** [comment]
Yes, @hgy just explained this also. I managed to get it working with Mesh
vertices. Not sure how to do the same with Box2D Bodies, but I could figure
it out.

Let's scrap this feature request. :)

**Comment by ar2rsawseen** [comment]
You can get an inspiration from box2d easy.

Basically you create sprite and add box2d body as it's sprite.body property

then you define set method there you change sprites coordinates and body coordinates, like

function sprite:set(property, value)
    self:setX(value)
    self.body:setX(value)
end

this exactly code won't work, but you get the idea :)

**Comment by totebo** [comment]
Yes, perfect. Thanks!
