### ISSUE TITLE
OSX Player + Desktop error on exit 

### ISSUE THREAD

**Issue by Kellog** [gideros/gideros#197]
"Quit unexpectedly" message box on exting application since 2015.08

**Comment by hgy29** [comment]
Should be already fixed by this commit:
https://github.com/gideros/gideros/commit/6368f32be34e9708f68aafa79fe20f6348fb1a3c

**Comment by hgy29** [comment]
Not yet released though...

**Comment by ar2rsawseen** [comment]
Closing this, reopen if issue still persists
