### ISSUE TITLE
Player restarts on iOS after having been sent to background

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#199]
It's time consuming to test "Event.APPLICATION_BACKGROUND" and "Event.APPLICATION_RESUME" on iOS because the player restarts. Could it be made persistent, like on Android?

**Comment by hgy29** [comment]
Yes it can, someone else knows a good reason not to do so ? Just need to remove "exit on suspend" in info.plist

**Comment by totebo** [comment]
The player is still resetting after having pressed the home button on iOS.

1. Start app
2. Press home button
3. Tap app icon again
4. App appears to be presistent, then is reset with IP showing after 2 seconds or so (no error message in console)

**Comment by hgy29** [comment]
Hmm again it seems to work for me. However I use a "custom" ios player, i.e. a regular export where assets have been removed. Could be that .plist file used to build GiderosIosPlayer.zip is not the same as the one that was fixed ?

**Comment by totebo** [comment]
I will double check and get back.

**Comment by totebo** [comment]
User error! I was using the wrong build when testing. I can confirm 2015-12 works as expected (and it's AWESOME, because now I can test reconnection to my multiplayer game easily!)
