### ISSUE TITLE
tvOS apps crash with bitcode applied

### ISSUE THREAD

**Issue by FuzzyDweeb** [gideros/gideros#201]
Exported tvOS apps crash when recompiled with bitcode.

If you export an .ipa from the final Archive and untick bitcode, the app will run on tvOS target OK.

If you export an .ipa from the final Archive and tick bitcode, the app will crash on boot on tvOS target.

Symbolic crash logging has problems in that the bitcode causes the crash log to not output gideros crash part. This appears to be a possible bug at Apple end as it also happens with non Gideros developed app crash logging.

Bitcode is a requirement for tvOS apps therefore it is not actually currently possible to publish a tvOS app with Gideros until this is fixed.

See forum thread of more details...
http://giderosmobile.com/forum/discussion/6184/tvos-crash-simulated-in-real-device-and-symbolicated-crash-logs

**Comment by FuzzyDweeb** [comment]
Update:

After further testing...

I just did a new fresh export from Gideros without any encryption and it all worked fine when I exported the bitcoded ipa.

Conclusion: Gideros Lua code and asset encryption breaks end bitcoded apps on tvOS.

**Comment by FuzzyDweeb** [comment]
Full details and findings in the forum thread above.

**Comment by ar2rsawseen** [comment]
It seems this issue was resolved. Issue was with encryption due to bit replacement and was fixed in https://github.com/gideros/gideros/commit/4f83006d26283df2f5a9779f0936e974a666f5ea
