### ISSUE TITLE
monokai editor theme

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#203]
it would be great to have a monokai theme, mainly for the editor.
see e.g. from zbs theme config file:
Monokai = {
    Background  = H'272822',
    CurrentLine = H'2D2F29',
    Selection   = H'49483E',
    Foreground  = H'F8F8F2',
    Comment     = H'75715E',
    Red         = H'AE81FF',
    Orange      = H'AE81FF',
    Yellow      = H'F8F8F2',
    Green       = H'E6DB74',
    Aqua        = H'66D9EF',
    Blue        = H'F92672',
    Purple      = H'A6E22E',
  },
or other places, e.g.:
https://github.com/procedural/qtcreator-themes/blob/master/monokai.xml

**Comment by keszegh** [comment]
and 'zenburn' theme would be also nice.
  Zenburn = {
    Background  = H'3f3f3f',
    CurrentLine = H'363636',
    Selection   = H'1f1f1f',
    Foreground  = H'dcdccc',
    Comment     = H'7f9f7f',
    Red         = H'8cd0d3',
    Orange      = H'dfaf8f',
    Yellow      = H'e3ceab',
    Green       = H'cc9393',
    Aqua        = H'dca3a3',
    Blue        = H'f0dfaf',
    Purple      = H'efef8f',
  },

**Comment by mokalux** [comment]
thanks to oleg gideros has now a plethora of themes to play with.

You may want to close this issue?

**Comment by mokalux** [comment]
don't want to close this issue?
