### ISSUE TITLE
[android] crashing on x86 binaries

### ISSUE THREAD

**Issue by ar2rsawseen** [gideros/gideros#21]
03-13 21:39:18.110: I/DEBUG(144): **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* **\* ***
03-13 21:39:18.110: I/DEBUG(144): Build fingerprint: 'asus/WW_epad/ME302C:4.3/JSS15Q/WW_epad-V5.0.21-20140701:user/release-keys'
03-13 21:39:18.110: I/DEBUG(144): Revision: '0'
03-13 21:39:18.110: I/DEBUG(144): pid: 3896, tid: 3917, name: Thread-317  >>> com.debia.sostavslova <<<
03-13 21:39:18.110: I/DEBUG(144): signal 11 (SIGSEGV), code 128 (SI_KERNEL), fault addr 00000000
03-13 21:39:18.150: I/DEBUG(144):     eax 00000000  ebx 792afb68  ecx 78444760  edx 3f800000
03-13 21:39:18.150: I/DEBUG(144):     esi 78444760  edi 83b3f310
03-13 21:39:18.150: I/DEBUG(144):     xcs 00000073  xds 0000007b  xes 0000007b  xfs 00000000  xss 0000007b
03-13 21:39:18.150: I/DEBUG(144):     eip 7908df46  ebp 788df010  esp 7bf4e98c  flags 00210202
03-13 21:39:18.160: I/DEBUG(144): backtrace:
03-13 21:39:18.160: I/DEBUG(144):     #00  pc 000fdf46  /data/app-lib/com.debia.sostavslova-2/libgideros.so
03-13 21:39:18.160: I/DEBUG(144):     #01  pc 000fee09  /data/app-lib/com.debia.sostavslova-2/libgideros.so
03-13 21:39:18.160: I/DEBUG(144):     #02  pc 0010104b  /data/app-lib/com.debia.sostavslova-2/libgideros.so
03-13 21:39:18.160: I/DEBUG(144):     #03  pc 00060898  /data/app-lib/com.debia.sostavslova-2/libgideros.so
03-13 21:39:18.160: I/DEBUG(144):     #04  pc 0007c24f  /system/lib/libdvm.so
03-13 21:39:18.160: I/DEBUG(144):     #05  pc 000164bf  <unknown>
03-13 21:39:18.160: I/DEBUG(144):     #06  pc 000d7dfc  /system/lib/libdvm.so
03-13 21:39:18.160: I/DEBUG(144):     #07  pc 00000118  /dev/ashmem/dalvik-jit-code-cache (deleted)
03-13 21:39:18.160: I/DEBUG(144):     #08  pc 0008cd61  /system/lib/libdvm.so
03-13 21:39:18.160: I/DEBUG(144):     #09  pc 0010abbe  /system/lib/libdvm.so
03-13 21:39:18.160: I/DEBUG(144):     #10  pc 0010af17  /system/lib/libdvm.so
03-13 21:39:18.160: I/DEBUG(144):     #11  pc 000e8e2a  /system/lib/libdvm.so
03-13 21:39:18.160: I/DEBUG(144):     #12  pc 0001b55c  /system/lib/libc.so
03-13 21:39:18.160: I/DEBUG(144):     #13  pc 0003dcb5  /system/lib/libc.so
03-13 21:39:18.160: I/DEBUG(144):     #14  pc 000e8a7f  /system/lib/libdvm.so
03-13 21:39:18.160: I/DEBUG(144): stack:
03-13 21:39:18.160: I/DEBUG(144):          7bf4e94c  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e950  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e954  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e958  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e95c  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e960  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e964  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e968  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e96c  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e970  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e974  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e978  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e97c  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e980  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e984  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e988  00000000  
03-13 21:39:18.160: I/DEBUG(144):     #00  7bf4e98c  7c795000  /dev/ashmem/AudioFlinger::Client (deleted)
03-13 21:39:18.160: I/DEBUG(144):          7bf4e990  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e994  00000001  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e998  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e99c  3f800000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9a0  00000001  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9a4  3f800000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9a8  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9ac  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9b0  3f800000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9b4  3f800000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9b8  41bf9b94  /system/lib/libmedia.so
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9bc  7c795000  /dev/ashmem/AudioFlinger::Client (deleted)
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9c0  00000000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9c4  7bf4f3d0  
03-13 21:39:18.160: I/DEBUG(144):          7bf4e9c8  41b6a393  /system/lib/libmedia.so
03-13 21:39:18.160: I/DEBUG(144):          ........  ........
03-13 21:39:18.160: I/DEBUG(144):     #01  7bf4eabc  83b3f310  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eac0  78444760  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eac4  00004800  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eac8  7b5e9f10  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eacc  a2100005  
03-13 21:39:18.160: I/DEBUG(144):          7bf4ead0  a2100005  
03-13 21:39:18.160: I/DEBUG(144):          7bf4ead4  00000800  
03-13 21:39:18.160: I/DEBUG(144):          7bf4ead8  788df084  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eadc  00000200  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eae0  729ebd20  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eae4  3b800000  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eae8  729ebd24  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eaec  7bf4f224  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eaf0  a2200005  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eaf4  7b5e94c0  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eaf8  41178c10  /system/lib/libdvm.so
03-13 21:39:18.160: I/DEBUG(144):          ........  ........
03-13 21:39:18.160: I/DEBUG(144):     #02  7bf4eb2c  788df010  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eb30  436236d0  /dev/ashmem/dalvik-heap (deleted)
03-13 21:39:18.160: I/DEBUG(144):          7bf4eb34  00000200  
03-13 21:39:18.160: I/DEBUG(144):          7bf4eb38  43623f10  /dev/ashmem/dalvik-heap (deleted)
03-13 21:39:18.160: I/DEBUG(144):          7bf4eb3c  792afb68  /data/app-lib/com.debia.sostavslova-2/libgideros.so
03-13 21:39:18.160: I/DEBUG(144):          7bf4eb40  79091016  /data/app-lib/com.debia.sostavslova-2/libgideros.so
03-13 21:39:18.160: I/DEBUG(144):          7bf4eb44  792afb68  /data/app-lib/com.debia.sostavslova-2/libgideros.so
03-13 21:39:18.160: I/DEBUG(144):          7bf4eb48  78ff0899  /data/app-lib/com.debia.sostavslova-2/libgideros.so
03-13 21:39:18.220: I/BootReceiver(451): Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
03-13 21:39:18.240: W/ActivityManager(451):   Force finishing activity com.debia.sostavslova/com.giderosmobile.android.sostavslovoActivity
03-13 21:39:18.250: E/IMGSRV(145): :0: PVRDRMOpen: TP3, ret = 90
03-13 21:39:18.270: W/InputDispatcher(451): channel '21f4c470 com.debia.sostavslova/com.giderosmobile.android.sostavslovoActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-13 21:39:18.270: E/InputDispatcher(451): channel '21f4c470 com.debia.sostavslova/com.giderosmobile.android.sostavslovoActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-13 21:39:18.270: W/InputDispatcher(451): Attempted to unregister already unregistered input channel '21f4c470 com.debia.sostavslova/com.giderosmobile.android.sostavslovoActivity (server)'
03-13 21:39:18.270: I/WindowState(451): WIN DEATH: Window{21f4c470 u0 com.debia.sostavslova/com.giderosmobile.android.sostavslovoActivity}
03-13 21:39:18.270: I/WindowState(451): WIN DEATH: Window{21cf65e8 u0 SurfaceView}
03-13 21:39:18.280: I/ActivityManager(451): Process com.debia.sostavslova (pid 3896) has died.

**Comment by ar2rsawseen** [comment]
It seems it crashes on .wav files with low bitrate, as 176Kbps

**Comment by unlying** [comment]
Converted for 352Kbps. Still crashes.

**Comment by unlying** [comment]
Converted to 1411Kbps. Works perfectly.

**Comment by hgy29** [comment]
Does this still happen on newest gideroses ? We switched to a newer version of OpenAL which uses OpenSL as a backend for audio, so this is issue is probably no longer relevant as such. I'll close it, but if it comes up again feel free to reopen it.
