### ISSUE TITLE
[enhancement] Breakpoint support

### ISSUE THREAD

**Issue by chrisfoulds** [gideros/gideros#211]
As title says, breakpoint support is for me the single largest omission to the Gideros IDE.

An ideal feature set would be
Integrated breakpoints
Stop on error
Step over/Step into functions
Along with full local and global inspection of variables.

**Comment by totebo** [comment]
Very much +1

**Comment by hgy29** [comment]
If someone wants to work on this, he/she is welcome :)

**Comment by ar2rsawseen** [comment]
I think that currently ZeroBrane Studio supports it
For now we don't have enough resources to dedicate to side tools, sorry :)

But yeah, as Nico sayd, if anyone wants to work on it, they can, and we could provide any info on the internal stuff that we have

**Comment by Apollo144** [comment]
hey guys! I guess this issue deserves to be closed now!

**Comment by hgy29** [comment]
You are rigjht!
