### ISSUE TITLE
Blank text while trying to use ionicons ttf 

### ISSUE THREAD

**Issue by fomojola** [gideros/gideros#212]
Just started working with Gideros: having a great time so far. Trying to use an icon font (ionicons: https://github.com/driftyco/ionicons) so I can use the icons for buttons (I use this for my native iOS/Android apps: quite handy, as the font scales nicely and allows custom colors without complex work). I've gotten the font to load correctly, and using the following unicode character function:

```
function unichr(ord)
    if ord == nil then return nil end
    if ord < 32 then return string.format('\\x%02x', ord) end
    if ord < 126 then return string.char(ord) end
    if ord < 65539 then return string.format("\\u%04x", ord) end
    if ord < 1114111 then return string.format("\\u%08x", ord) end
end
```

I can generate strings with the proper unicode bits: however, when I load the font

`local iconfont = TTFont.new("Fonts/ionicons.ttf", 28)`

that works right, but when I try and draw a text field it just renders blank in both the desktop player and the Android player (the code below is supposed to draw a hamburger menu).

```
local text = TextField.new(iconfont, unichr(0xf20d)
text:setTextColor(foregroundColor)
text:setPosition(round((width-size)/2, 0), round(height/2, 0))
self:addChild(text)
```

Any thoughts on how I can get this working? I've switched to using PNG images scaled down, but being able to do this with fonts would make things like upstate/downstate coloring work quite cleanly.

Thanks,

Femi.

**Comment by hgy29** [comment]
I don't think the \u or \x syntax in strings are handled. Rather you should convert you Unicode char to an UTF-8 string, or maybe directly use UTF-8 sequences: try "\239\136\141"

**Comment by mertocan** [comment]
use this method to convert utf8 

``` LUA

function utf8(decimal)
    if decimal<128 then return string.char(decimal) end
    local charbytes = {}
    for bytes,vals in ipairs(bytemarkers) do
      if decimal<=vals[1] then
        for b=bytes+1,2,-1 do
          local mod = decimal%64
          decimal = (decimal-mod)/64
          charbytes[b] = string.char(128+mod)
        end
        charbytes[1] = string.char(vals[2]+decimal)
        break
      end
    end
    return table.concat(charbytes)
end
```

Then use it like 

``` LUA
local text = TextField.new(iconfont, utf8(0xf20d));
```
BTW, make sure that you have the icon '0xf20d' in your font.

**Comment by fomojola** [comment]
Thank you so much: this worked. Dug out the SO post (at http://stackoverflow.com/questions/26071104/more-elegant-simpler-way-to-convert-code-point-to-utf-8) so for posterity (and anyone else who wants to use the same technique) you'll need to add

`local bytemarkers = { {0x7FF,192}, {0xFFFF,224}, {0x1FFFFF,240} }`

before the definition of utf8 above.
