### ISSUE TITLE
MovieClip:getFrame()

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#214]
This would be handy when you want to synchronize the frames on separate MovieClips, ie. a character changing direction on frame 5 should start on frame 5 in its new state.

http://giderosmobile.com/forum/discussion/6078/movieclip-frame

**Comment by SinisterSoft** [comment]
Also a movie:setFrame(x) - so you could program a movie clip that was looping to skip out of the loop and continue if a specific event occurred in the main program.

**Comment by ar2rsawseen** [comment]
@SinisterSoft isn't that's what gotoAndPlay/Stop is for?

**Comment by SinisterSoft** [comment]
lol, yes I suppose it is - you learn something new every day! :)

**Comment by totebo** [comment]
Don't forget what we came here for: MovieClip:getFrame(), mm, sweet getFrame().

Another method to complete the package:

MovieClip:setPaused(bol)

To be able to stop animations when player hits pause, for instance.

**Comment by tkhnoman** [comment]
There is MovieClip:stop and MovieClip:play, so MovieClip:setPaused(bol) is not needed i guess.

**Comment by totebo** [comment]
Ah yes, you're right. So then MovieClip:getFrame() is the one thing needed.
