### ISSUE TITLE
Windows protected your PC

### ISSUE THREAD

**Issue by teo6667** [gideros/gideros#216]
When I try to install gideros I get this message! Why is the publisher unknown??? I don't want to take the risk to run :)

![gideros](https://cloud.githubusercontent.com/assets/13005539/13435237/915df318-dfd9-11e5-936d-f0d9bec56f1c.png)

**Comment by SinisterSoft** [comment]
This happens with programs like dev-kits, they are not downloaded by hundreds of thousands of people so this message appears until enough people download them.   As long as you have downloaded it via  the proper website, click 'Run anyway'.

**Comment by john-blackburn** [comment]
I think we are signing the code, but perhaps MS has updated their policy... Should show "Open source publisher Arturs Sosins".

**Comment by hgy29** [comment]
Recent releases are signed by my companies certificate and shows 'Point Core' as publisher. Not much more we can do I suppose.
