### ISSUE TITLE
Gideros Studio - 'Open in explorer' in context menu

### ISSUE THREAD

**Issue by rolfpancake** [gideros/gideros#217]
When using Gideros Studio and rightclick on the project root there should be a context menu entry for opening the project folder in explorer.

![rightclickmenu_open-in-explorer](https://cloud.githubusercontent.com/assets/9326192/13474937/7778474a-e0c0-11e5-8100-a603500d9a11.png)

This would make it easier to work with assets.

**Comment by ar2rsawseen** [comment]
Great suggestion, I like it.

**Comment by john-blackburn** [comment]
Yes, and this should apply to individual files in a project as well, eg LUA files. And/or hover over the file and it shows the full path.

**Comment by hgy29** [comment]
It is possible since 2017.2, thanks to @alexzheng.
