### ISSUE TITLE
Gideros Studio - Consistent use of offline documentation

### ISSUE THREAD

**Issue by rolfpancake** [gideros/gideros#218]
If Gideros Studio is installed, the documentation is available offline in the installation directory (`Gideros\Documentation)`.
This offline repository is used on the _Welcome Screen_ when clicking on **Getting Started** or **Reference Manual**:

![gideros-studio_docs_offline](https://cloud.githubusercontent.com/assets/9326192/13569594/2b5553d8-e469-11e5-9c68-0b0249a3d873.png)

When trying to open the docs via menu it points to the online documentation:

![gideros-studio_docs_online](https://cloud.githubusercontent.com/assets/9326192/13569615/4d0f9254-e469-11e5-8e60-ab795ccf3cc7.png)

There should be a consistent use of the offline documentation everywhere in Gideros Studio.

**Comment by rolfpancake** [comment]
See #219 for further discussion.

**Comment by Nlcke** [comment]
https://github.com/gideros/gideros/issues/219 have been closed:
> We have now solved this problem. From now on Gideros Studio will ship with the latest documentation which will be automatically downloaded from the website. So you can read off line.
