### ISSUE TITLE
Reference manual online and offline are not consistent

### ISSUE THREAD

**Issue by rolfpancake** [gideros/gideros#219]
The reference manual can be accessed online or offline (in the installation directory) but it has not the same structure.

**Online manual** (tabs, structuring):

![gideros_reference_online](https://cloud.githubusercontent.com/assets/9326192/13569707/d8ff6af0-e469-11e5-9cd2-ad619f3109d0.png)

**Offline manual** (no tabs, no structuring):

![gideros_reference_offline](https://cloud.githubusercontent.com/assets/9326192/13569739/154825f6-e46a-11e5-88da-626267650bfe.png)

Both versions have their points:

- The structuring of the online manual makes it easy to explore
- The full page layout (everything on one page) of the offline manual makes it easy to search in the whole documentation (with `STRG`+`F`)

**Comment by ar2rsawseen** [comment]
Also problem is that online version is dynamically generated. So each record has its page, etc/
But offline can only be single paged, because of complexity of generation it would provide.
Also that was the reason we decided to move to online only documentation, and tried to remove offline docs from Studio.

**Comment by rolfpancake** [comment]
Well I really like using an offline documentation.

- Sometimes you simply aren't online
- Sometimes your internet connection is slow
- Sometimes you don't use the most up-to-date release of Gideros and wish the docs to stay in the same version as long as you don't update

If it is hard to provide an offline documentation there should be a possibility to just download the generated docs. I could do this with httrack or similar but this would make it a hassle.

**Comment by john-blackburn** [comment]
We have now solved this problem. From now on Gideros Studio will ship with the latest documentation which will be automatically downloaded from the website. So you can read off line.
