### ISSUE TITLE
[android] "jumpy" sprite when update position in ENTER_FRAME event

### ISSUE THREAD

**Issue by grotly** [gideros/gideros#22]
When constantly updating position for a sprite in ENTER_FRAME event, at a bit higher speeds, the sprite looks like it jumps on the screen and the movement is not smooth. This happens only on android devices and it becomes more visible when more sprites are moved at the same time. The issue is described in details and with an attached example here:

http://giderosmobile.com/forum/discussion/comment/41240#Comment_41240

The issue does not occur on Apple devices, unless the number of sprites is extremely high and the hardware limitation become visible.

**Comment by ar2rsawseen** [comment]
Could be related to:

http://stackoverflow.com/questions/21172585/android-thread-performance-priority-on-galaxy-note-2-when-screen-is-touched-rele/

**Comment by mokalux** [comment]
I tested the demo posted on the forum on a low end device samsung J6 and it runs "smoothly" enough I guess.
You may want to close this issue.

**Comment by hgy29** [comment]
Agreed, it is been four years now and no more complaints nor evidence. Closing.
