### ISSUE TITLE
Feature request: Automatically add dependencies to project

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#224]
A "Resolve dependencies" option for the "Tools" menu.

1. Look through all extended classes  
2. Add any inheritance to "Code Dependencies" for that class

The use case is that XCode has different requirements for dependencies, so these issues cannot be tested in the Gideros Player:
http://giderosmobile.com/forum/discussion/6334/xcode-messing-with-my-mind

**Comment by ar2rsawseen** [comment]
But the problem is, we don't know in which class you defined in which file.
You can have them in multiple files or all in one :)

**Comment by totebo** [comment]
The problem is only with extended classes (since other uses gives an error in Gideros Player and XCode). So, for example, when the class Weapon extends GameObject, a dependency to GameObject should be made in the Weapon class.

**Comment by ar2rsawseen** [comment]
Yes, what I mean is that dependencies are file based.
You may have GameObject class in file go.lua and Weapon in file wp.lua
unfortunately we can't know that

**Comment by totebo** [comment]
Ah, bummer.
