### ISSUE TITLE
Feature Request: getTextureRegion for Bitmap class

### ISSUE THREAD

**Issue by Antix-Software** [gideros/gideros#225]
Bitmap class should have a getTextureRegion() method to make using setRegion() easier to use.

**Comment by hgy29** [comment]
Sorry, it is been a while since I checked feature requests, and I don't remember exactly why this should be added. Can you comment further ?

**Comment by Antix-Software** [comment]
Honestly I can't remember right now, this is eleven months ago. I know everybody is busy but leaving things for that long isn't great. Anyway, don't worry about it I must have come up with a solution to my issue :)

**Comment by hgy29** [comment]
No problem, I'll close it then. I agree that it is not great to leave it for that long, however saying that is a bit harsh since no one is really responsible for taking care of those issues, so who can be blamed then ? 
I take it even worse since have been doing 90% of gideros changes over the past year, spending far too much unpaid time on it while I do have a company to manage on the other side and 50 hours a week engineering job.

**Comment by Antix-Software** [comment]
Hey,

 

It wasn’t meant to be any kind of attack on you personally, please don’t take it like that. I’m also not trying to place blame on anyone in particular J

 

I have said it many times and will say it again.. Gideros is a truly fantastic engine that would really shine if only it could be maintained, supported, and nurtured more.

 

This is of course a very hard thing to accomplish because the team does not have the time and resources to do everything that needs to be done. Indeed it is a very perplexing problem, with no easy solutions.

 

I appreciate you do a heck of a lot given your very busy real life, all respect to you, and all the other maintainers J

 

I think part of the problem with Gideros is that there are many new features appearing (which are cool and I appreciate immensely) but in my opinion it is not where the bulk of the work should be being done.

 

The engine stands on it’s own merit and performs fantastically so maybe it is time to say, the engine can now sit and mature for a little while. During this time we will fix the few bugs there are, and focus our attention on things that have fallen by the wayside for a while, like documentation, the website, the blog, monitoring things like the github features request, and marketing and PR.

 

What do you think? If the team wasn’t focussing on adding new things, the infrastructure could be setup and it would be much easier to a) maintain, and b) bring others onboard to do the maintaining.

 

I have offered my services numerous times to John26 and he has always said great I’ll be in touch.. and that’s all I ever hear from him. I’m not attacking him here either but when somebody offers their free time (like all of you maintainers have so graciously done) then they should be utilized, not ignored J

 

Anyway do you think maybe I have a good idea or two? Or should I shut up and go back to making more games? ;)

 

Oh hey, do you have like some roster of who the current maintainers are and what their assigned responsibilities are?

 

I also remembered why I requested the getTextureRegion() feature for Bitmaps. It was to make frame based animation (MovieClip seems a little inefficient) easier to implement. Since I have already implemented my own frame based animation system (using TexturePack regions) which seems to be working it probably isn’t required.

 

Kind Regards,

 

Cliff.

 

Antix Development

Always fun,  Always free,  Apps and Games from Antix Development



Try our games <https://play.google.com/store/apps/developer?id=Antix+Development>  and Check out our Dev Blog <https://antixsoftwareblog.wordpress.com/> 


2/509 Henry St,  Raureka,  Hasting 4120,  New Zealand
E:antix.development@gmail.com   M:+64 27 552 1113
