### ISSUE TITLE
Android Landscape app rotates back to portrait after device power button is pressed... 

### ISSUE THREAD

**Issue by FuzzyDweeb** [gideros/gideros#226]
Odd bug that I've personally not seen before on previous Gideros releases prior to latest 2015.12 version.

To recreate...
_(Note: App built with Android Studio or Eclipse using Gideros 2015.12)_
Run landscape app.
Press device power button (standby).
Press device power button again (resume).
Notice landscape app now runs in portrait with bottom clipped.

You can get back to landscape again by pressing the left soft key to show minimised running app tasks, then press it again to go back to full screen Landscape.

(see pics attached)

![photo 29-03-2016 8 09 12 am](https://cloud.githubusercontent.com/assets/9529552/14101333/c3ccd234-f58b-11e5-9985-8558b0089a58.jpg)
![photo 29-03-2016 8 08 54 am](https://cloud.githubusercontent.com/assets/9529552/14101339/cc7b7278-f58b-11e5-9aab-9a29fc823ef9.jpg)

**Comment by FuzzyDweeb** [comment]
The FREE live app is here if you want to try it yourself to see the bug perhaps. Please leave 5-stars to fight off any trolls :)

[https://play.google.com/store/apps/details?id=com.mobileamusements.GorillaAdventureSlotsFREE](url)

**Comment by john-blackburn** [comment]
I was not able to reproduce this bug on my Samsung Galaxy Tab 2 running Android 4.4.4. I wonder if the bug happens only on certain devices. Did you try it out on any other android devices? What device are you using in the above photos and what version of Android is it running? What Android SDK did you use to create the APK?

**Comment by FuzzyDweeb** [comment]
I used Android Studio (but it does the same with Eclipse). Device is Galaxy S7 Edge running Android 6.0.1. I've not tried with any other devices yet but will on Monday and report back.

**Comment by FuzzyDweeb** [comment]
I also just tested this on 2 other Android devices both running 6.0 and didn't see this bug then either, so it must be specific to the Galaxy S7 perhaps.

**Comment by john-blackburn** [comment]
OK thanks for that feedback. Since the S7 is using the latest version of Android it might be a good idea to upgrade your Android SDK to the latest as well. The latest seems to be Android-23 so perhaps try re-exporting with that. See here (in the Deploy to devices tab) for info on how to change the version of Android SDK you link against within Android Studio.

http://docs.giderosmobile.com/deployment.html

**Comment by FuzzyDweeb** [comment]
Yes I already link with Android 23 in Android Studio.

It is odd because apps I built with Gideros .10 before this .12 version all seem to work correctly.

Is it something to do with gles 2.0 which gideros uses now perhaps.

**Comment by SinisterSoft** [comment]
Can you try targeting sdk 19 (android:targetSdkVersion="19") in the manifest and linking with Android 5.1.1 (api 22) instead.  This might work.

**Comment by FuzzyDweeb** [comment]
Need to do this in the manifest...

android:screenOrientation="sensorLandscape"

..which fixes it :)

**Comment by FuzzyDweeb** [comment]
Ah no when I hit power button to turn screen back on after screen timeout it still does it on S7 - odd.

**Comment by SinisterSoft** [comment]
Possible fix:

https://thinkandroid.wordpress.com/2010/01/24/handling-screen-off-and-screen-on-intents/

Arturs will know more than me though...

**Comment by SinisterSoft** [comment]
I got it to also go wrong on a Sony Z1 - so it looks like a general Gideros bug - not isolated to the S7.

**Comment by SinisterSoft** [comment]
Also got it to happen on a HTC M8.

**Comment by FuzzyDweeb** [comment]
Ah OK but cool it's not just me then after all :)

**Comment by FuzzyDweeb** [comment]
This bug is back again in Gideros 2016.06...

![photo on 06-07-2016 at 8 15 am](https://cloud.githubusercontent.com/assets/9529552/16610338/95226e34-4352-11e6-9f53-40710112a987.jpg)
