### ISSUE TITLE
HTML5 not utilising Hi-DPI (retina) screens 

### ISSUE THREAD

**Issue by Ninjadoodle** [gideros/gideros#229]
When I export an HTML5 game with @2x and @4x assets enabled, the game only loads @2x assets and the game looks blurry on a MacBook Pro Retina screen.

I'm pretty sure that the HTML5 export is ignoring the Hi-DPI screen and treating it as half it's resolution (because of the retina zooming).

**Comment by hgy29** [comment]
I think I found out the issue. Do you have some sample project to give me so that I check ?

**Comment by Ninjadoodle** [comment]
Hi Nicolas

Awesome, here is a dropbox lik to my sample project :)

https://www.dropbox.com/sh/5ggivi00ip38kii/AACV3S0A9eivCOh3kHez0hMda?dl=0

**Comment by hgy29** [comment]
@Ninjadoodle, I tried your sample project but couldn't see any difference, graphics look good no matter what, but I don't have a macbook pro retina. Can you try yourself with the latest version: http://apps.giderosmobile.com/Html5.zip ?

**Comment by hgy29** [comment]
I could finally try HiDpi case (thanks to firefox HiDpi emulation settings), and had it fixed. I'll close this issue then.

**Comment by Ninjadoodle** [comment]
Sorry about the wait, I was busy finishing off some work this week :)
Awesome about the fix!!

Thank you!
