### ISSUE TITLE
Render to texture allocates wrong size depending on scale

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#23]
If you create a texture using render to texture then it allocated different amounts of memory depending on the app scale setting - it should always allocate the same size of texture.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/gideros/gideros/commit/ea7b525670369ee35a37a9c0d95b63b22148b81a

**Comment by SinisterSoft** [comment]
Thanks for your help with this, much appreciated. :)
