### ISSUE TITLE
HTML5 - No sound in iOS Safari

### ISSUE THREAD

**Issue by Ninjadoodle** [gideros/gideros#230]
In HTML5 exports, I'm not getting any sounds in iOS Safari. Sound works fine on Android and Desktop.

**Comment by hgy29** [comment]
Confirmed, but it used to work! Must be a regression.

**Comment by hgy29** [comment]
Seems to be some user protection apple introduced in iOS9: http://www.holovaty.com/writing/ios9-web-audio/, nothing to do with Gideros. I'll take some time to see how others avoid this...

**Comment by ar2rsawseen** [comment]
Unfortunately I don't think it is possible.
Basically they do not allow sound initialization without user interaction.
So
1) Sounds by default should be disabled and user specifically needs to enable them with button click.
2) Sound effects are probably not possible, unless they are made from user interaction, like on jump, hit, etc
3) Sounds needs to be played on mouseup, touch end events

**Comment by hgy29** [comment]
A few tips here:
https://paulbakaus.com/tutorials/html5/web-audio-on-ios/

No sound on launch, but maybe enabled forever after the first click

**Comment by ar2rsawseen** [comment]
So what is source in context of Gideros?
A channel?

**Comment by hgy29** [comment]
I think so. I added a quick fix to HTML5 export, so that audio gets activated following a user click (touchEnd event). This means that sound is muted when the page load, and unmuted as long as the app runs once the user clics something.
So basically no background sound on app menu/first scene, but sound enabled after the first user selection.

**Comment by hgy29** [comment]
So, since it is an iOS9 limitation and we can't do anything better than enabling sound on user's first action, I suppose we can mark this bug as closed.

**Comment by Ninjadoodle** [comment]
Awesome, I think this is how other HTML5 engines deal with it.

Thank you!
