### ISSUE TITLE
Show/Hide keyboard and better key capture

### ISSUE THREAD

**Issue by Nlcke** [gideros/gideros#234]
Right now text input is only possible via TextInputDialog which is very limited and looks different on each platform. For example you can't use different font, can't have multiline text, can't position it where you want.
The best solution is to add show/hide keyboard method for touchscreen devices and good char capturing for all keyboards (both virtual and hardware). For touchscreen devices getKeyboardHeight method needed too. This allows to implement game chats and editors which will have same look as your game. It's also good for text-based games e.g. text quests.

**Comment by ar2rsawseen** [comment]
While I agree that would help alot, I already see the pain of implementing it on Android. I remember doing something like that before, showing/hiding keyboard programmatically. And different solutions worked in different situations.

Still though, legit request :)
