### ISSUE TITLE
Feature Request: getWidth and getHeight without children

### ISSUE THREAD

**Issue by Nlcke** [gideros/gideros#237]
Very useful for GUI libraries. For example if you want to place some button in the right bottom corner of  a parent you need to know that parent own width and height for calculations. For now you need to remove each other child from a parent to get it and then attach all removed children back which is very ineffective and can trigger some events like "onRemovedFromStage".

**Comment by ar2rsawseen** [comment]
I really don't see the need for it.

Parent's width is larger if it includes children.
So positioning element internally should also use width expanded with children.

Additionally it may listen to remove from stage event and reposition it internally to changed width, when children are removed

But all in all, in my opinion, is positioning elements including width expanded by children, cause it is the real current width

**Comment by Nlcke** [comment]
No, you must be missed our disccussion in Slack. This should be just an option for `getWidth` and `getHeight`, _not a replacement_. And John suggested to simply add boolean parameter to those functions. So `spite:getWidth(true)` will return real width of an element and `sprite:getWidth()` will return current width with children, like always.
I think you don't see how useful it is because you never tried relative positioning and anchoring of elements. If so you can look at my Layout library.

**Comment by ar2rsawseen** [comment]
I saw the discussion and I have tried relative positioning when working on GiderosCodingEasy
I just say, that real parent dimensions should count in children too, or else it is contradiction with everything else Gideros does

**Comment by ar2rsawseen** [comment]
I mean adding children to Bitmap is unnatural and should not be encouraged or handled.
If you need children, you use Sprite as container

**Comment by Nlcke** [comment]
"real parent dimensions should count in children too" -- I never said they shouldn't if by "real" you mean parent + children size. I said "This should be just an option for getWidth and getHeight". Very useful option for relative positioning/sizing. How can it contradict with (default) absolute ones? They can only _complement_ each other. And more than that Gideros long ago has primitive support of relative sizing for a stage through `scale mode` and `logical dimensions` settings.
And you cannot achieve same effect only with Sprite containers. You can only poorly simulate some cases with it.
"adding children to Bitmap is unnatural" -- why? Bitmap is subclass of Sprite. Same for TextField, Mesh, Path2D and Shape. This cannot be unnatural because they (subclasses) have same properties as Sprite has. The only difference is they have content. "If you need children, you use Sprite as container" -- why I need another layer of complexity if they are already Sprites? This cannot help anyway with positioning/sizing.
