### ISSUE TITLE
Gideros Player Crash When Trying to Start (2016.06)

### ISSUE THREAD

**Issue by bearcodez** [gideros/gideros#239]
The latest version 2016.06 of gideros player on Windows is always crash when try to start and run for existing project. I had to revert back to version 2015.12 in order to start without issue. I try to run with administrator right also same issue.

**Comment by hgy29** [comment]
Is the problem solved on 2016.8.2 or better ?

**Comment by bearcodez** [comment]
hi @hgy29 

Yupe. The problem is solved on version 2016.08.1

Thanks for looking into this.
