### ISSUE TITLE
Bug: RenderTarget doesn't work as intended on older devices

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#241]
On older devices RenderTarget fails to copy any pixels if the area is very narrow, in my case for an energy bar. This code shows the issue.

```
local shape = Shape.new()
shape:setFillStyle(Shape.SOLID, 0xff0000, 1)
shape:beginPath()
shape:moveTo(0,0)
shape:lineTo(100, 0)
shape:lineTo(100, 100)
shape:lineTo(0, 100)
shape:lineTo(0, 0)
shape:endPath()
stage:addChild(shape)

local width = 100 
local height = 5 -- Using a value of 10 works on all devices
local rt = RenderTarget.new( width, height )
local bitmap = Bitmap.new( rt )
rt:draw( shape )
bitmap:setX( 125 )
stage:addChild( bitmap )
```

On these devices no pixels are copied:
- iPad 2
- iPod Touch 5th generation
- iPhone 5

On these it works fine (all pixels are copied):
- Local Gideros Player
- Nexus 6
- iPad Mini Retina

**Comment by hgy29** [comment]
With the deprecation of OpenGL on iOS and the switch to Metal API in recent Gideros, along with the drop of support for the mentioned old devices, I think we can close this.
