### ISSUE TITLE
Add feature to detect if device is an Android TV, Apple TV

### ISSUE THREAD

**Issue by simwhi** [gideros/gideros#258]
The use case for this feature is to allow developers to determine the type of device in order to provide or remove game features.

Here is some code as an example:

public static final String TAG = "DeviceTypeRuntimeCheck";

UiModeManager uiModeManager = (UiModeManager) getSystemService(UI_MODE_SERVICE);
if (uiModeManager.getCurrentModeType() == Configuration.UI_MODE_TYPE_TELEVISION) {
    Log.d(TAG, "Running on a TV Device")
} else {
    Log.d(TAG, "Running on a non-TV Device")
}

**Comment by SinisterSoft** [comment]
device={application:getDeviceInfo()}
print(device[5])

will show "TV" if on Android.
