### ISSUE TITLE
On Windows the Controller lib doesn't reset the controller count in the player when reset.

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#26]
It keeps incrementing the id code until you close and restart the player.

**Comment by ar2rsawseen** [comment]
Unfortunately this is due to the lib I'm using underneath, it only provides session level ID of device, so on next session this ID is changed, thus also the behavior that you see.

http://forums.tigsource.com/index.php?topic=10675.0

Closing for now until the underlaying library's functionality is updated or better alternative is found

**Comment by SinisterSoft** [comment]
I looked at the library - although it might not fix the problem, the verison linked to in the pad forum is out of date (2013 version).  Here is a link to the latest version (updated 2014):

http://ludobloom.com/svn/StemLibProjects/gamepad/tags/1.4.1/

**Comment by SinisterSoft** [comment]
If you do use it (the latest version) then please also look at this fix for it re PS4 joypads:

Using a Sony DS4 controller connected to the PC, the DI_BUFFEROVERFLOW happens regularly when using both analogue sticks at the same time. The DS4 controller is very common, as ist comes with the PS4 and a lot of people actually use it on their PC, too.
In our games we display a popup menu when the main controller gets disconnected so a new controller can be selected. With the DS4 this popup appears randomly and kind of breaks the game.
Changing the if (result != DI_OK) to if (SUCCEEDED(result)) fixes the problem.

**Comment by SinisterSoft** [comment]
Based on this, it looks like the initial functionality issue of it keep adding joypads as new ones might be fixed too:

http://ludobloom.com/svn/StemLibProjects/gamepad/tags/1.3.0/ReadMe.txt

**Comment by ar2rsawseen** [comment]
Unfortunately it does not seem to fix the issue, as stated in comment for deviceID:

http://ludobloom.com/svn/StemLibProjects/gamepad/tags/1.4.1/source/gamepad/Gamepad.h

If there would be at least something as serial number of device, that would help to get around.

Do you think it is still better to upgrade to newer version? Or current version works ok and better not make it worse :D

**Comment by SinisterSoft** [comment]
They had some memory leaks in an older version - how about including it an an 'alt' folder?

**Comment by ar2rsawseen** [comment]
Updated controller lib here: https://github.com/gideros/gideros/commit/2fa31910f43fc975e8c9093b5f5be55fa46f850e
