### ISSUE TITLE
Cannot disable splash screen by Gideros project setting.

### ISSUE THREAD

**Issue by bugcaptor** [gideros/gideros#271]
Display splash option of project property dialog does not work. Tested APK exporting, android project exporting.

**Comment by hgy29** [comment]
Yes I can see the APK export scripts has not been updated, however Android export has been (https://github.com/gideros/gideros/blob/master/gdrexport/ExportBuiltin.cpp#L91). It shall work for a full export. It wasn't 'asset only', right ?

**Comment by bugcaptor** [comment]
Oh right my mistake. Android project export of disabled splash works.

**Comment by ar2rsawseen** [comment]
Yes, my fault, only added it to Builtin exports, forgot that APK export was XML export :)
