### ISSUE TITLE
please add icon size 83.5 x2 for iPad pro App

### ISSUE THREAD

**Issue by alexzheng** [gideros/gideros#275]
when export app icons, this is missed

**Comment by hgy29** [comment]
We added 83.5 x2 icon for iphone4 retina, could it be the same ?
See: https://github.com/gideros/gideros/commit/cd6fb6f7373c2de9e5eace595a3af1f566465727

If not, which one should be added in Content.json ?

**Comment by alexzheng** [comment]
{
      "idiom" : "ipad",
      "size" : "83.5x83.5",
      "filename" : "AppIcon167x167.png",
      "scale" : "2x"
    }
