### ISSUE TITLE
source codebuild error when using the lastest ndk-build 13.0.3315539

### ISSUE THREAD

**Issue by alexzheng** [gideros/gideros#276]
[armeabi] Compile++ arm  : gvfs <= gfile.cpp
[armeabi] Compile++ arm  : gvfs <= gpath.cpp
[armeabi] SharedLibrary  : libgvfs.so
/Users/zhengyi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_4'
/Users/zhengyi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_4'
/Users/zhengyi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_4'
/Users/zhengyi/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/ext/atomicity.h:49: error: undefined reference to '__atomic_fetch_add_4'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [obj/local/armeabi/libgvfs.so] Error 1
Android NDK: ERROR:jni/Android.mk:gvfs: LOCAL_SRC_FILES points to a missing file  
Android NDK: Check that jni/../../libgvfs/libs/armeabi/libgvfs.so exists  or that its path is correct  
/Users/zhengyi/Library/Android/sdk/ndk-bundle/build/core/prebuilt-library.mk:45: **\* Android NDK: Aborting    .  Stop.
Android NDK: ERROR:jni/Android.mk:gvfs: LOCAL_SRC_FILES points to a missing file

**Comment by hgy29** [comment]
Yes, we know that newest NDKs can't build gideros, so we decided to stick to r10 series until we know more. It looks like newest NDKs suppose you are targetting newest SDK too, so they don't include some libs required on older devices. If we want gideros to run on Gingerbread, then we must use r10. Or so it seems...

**Comment by alexzheng** [comment]
Thanks for your confirm, I will just go back to the older ndk.

**Comment by hgy29** [comment]
Anyway the error you have is not what we encountered, we were actualmly able to build gideros only it refused to run on some devices. It seems that your NDK is actually broken!

**Comment by alexzheng** [comment]
my NDK is updated by the android studio, and I googled, it seems this a common error for the new ndk.

**Comment by beyazc** [comment]
You should add following flag.    
ldFlags.add("-latomic")

**Comment by hgy29** [comment]
Turned out that newest NDK dropped support for android 8, which was the baseline gideros last year. After migrating every plugin and core to android-9 min (and adding -latomic where needed), gideros can be built with r14. Changes will be commited soon...

**Comment by SinisterSoft** [comment]
:)
