### ISSUE TITLE
sorry to mention again about the long path name in the compiled lua scripts 

### ISSUE THREAD

**Issue by alexzheng** [gideros/gideros#277]
any idea to remove the absolute path?
If not, simple add an -s option to luac, but it's not a good solution.

**Comment by hgy29** [comment]
Hey, the absolute path has already been removed in 2016.8.2, it is now relative to the project's root, unless your talking about something else ?

**Comment by alexzheng** [comment]
it produce an even longer path like this in 8.2
../../../../Users/username/Dropbox/lua/mygame/cell.lua

my project root dir is mygame

**Comment by hgy29** [comment]
ah, but path is relative! But probably no relative to the right base dir. I can change it to be the directory containing .gproj file, but this may not be enough since gideros directory structure is virtual.

**Comment by alexzheng** [comment]
yes, it seems it's hard to find a right root dir for all the lua scripts in the gideros project.
A stupid solution is copy them to the export project first, then compile them, in this way, all scripts has the same root.

**Comment by hgy29** [comment]
Yes, that's what I just did in the end. Let me check and commit!

**Comment by alexzheng** [comment]
Just change the base dir to the directory containing .gproj file will be enough for most situations,
because game related scripts were just in that dir in most users, maybe some common libs file in somewhere else.

**Comment by alexzheng** [comment]
you are so fast ,then just ignore my reply.

**Comment by alexzheng** [comment]
BTW, How do you think the -s option for luac?  will it be necessary to have an option for that.

**Comment by hgy29** [comment]
It makes the code lighter and possibly harder to decompile, at the expense of crash readability. Maybe a few users will want it turned on for release, while others will want to see readable lua crashes on their console (logcat or Xcode). I can't say.

**Comment by alexzheng** [comment]
That's exactly what I think.

**Comment by alexzheng** [comment]
it seems you have just removed all  the final compiled lua files when no suffix is added to the compiled files.
The result is no lua files for iOS project.

**Comment by hgy29** [comment]
Damn! Glad you saw it! I checked on Android...
Should be fixed now

**Comment by alexzheng** [comment]
BTW, as you said gideros should be built using ndk 10 for running on some device,  is this also required for build custom plugins?
