### ISSUE TITLE
some improvements  for ads plugin

### ISSUE THREAD

**Issue by alexzheng** [gideros/gideros#278]
[source.zip](https://github.com/gideros/gideros/files/529661/source.zip)

some modification for the ads plugin, I don't know where to upload, if it's useful, please merge to the branch.

something like:
orientation issue
interstitial ads preload and refresh

**Comment by hgy29** [comment]
Hi @alexzheng, it looks useful according to your description, however there are so many files in your archive that it is a little difficult to review the changes.

If you wish to propose your changes, the best way is to fork gideros on github, commit your changes to your fork, then ask for a 'pull request' into gideros master repository.

That way we can review your changes online and merge them more easily.
