### ISSUE TITLE
Path2d and win32 export

### ISSUE THREAD

**Issue by piretro** [gideros/gideros#283]
Hi, there is some problem with path2d and win32 export: the circle should be a transparent red like its bounding box is, and the bounding box should not be visible (see attached image)

[release 2016.8.2]

Thank you
![path2d-gideros win32 no qt](https://cloud.githubusercontent.com/assets/8805969/19841571/0bf126b0-9f0e-11e6-984c-3233f50b3e28.png)

**Comment by hgy29** [comment]
Looks like stencil buffer is not queried in Win32 export. @john-blackburn can you look at this ?
