### ISSUE TITLE
setGenericArray is not documented.

### ISSUE THREAD

**Issue by bugcaptor** [gideros/gideros#284]
I found GMesh::setGenericArray method and its lua binding also. But has no documentation and any forum article. May I use it?

Made spec based on the code.

Mesh:setGenericArray(index: int, type: int, mult: int, count: int, arrayTable: {})

type(int enum): DBYTE(0), DUBYTE, DSHORT, DUSHORT, DINT, DFLOAT
index: [3, 7] (0~2 already occupied by base elements)
mult: maybe logical item's element count
count: maybe logical item count
arrayTable size must be eqaul to mult * count.

**Comment by hgy29** [comment]
Yes, you can use it, and I shall document it :)
Your spec is correct, and you can find DBYTE, DUBUYTE, ... values in Shader binder: Shader.DUBYTE, Shader.DFLOAT, ...
mult is typically the vector size (think shader) and count the number of item to send. Should be equal to vertex count.

**Comment by dungeonkim** [comment]
It does not seem to work in HTML5 export.
