### ISSUE TITLE
Particles on android player are always oriented to Portrait mode

### ISSUE THREAD

**Issue by piretro** [gideros/gideros#286]
If Landscape L/R mode is selected in project properties, textured Particles are not rotated by +-90° (while this happens on windows player)

gideros 2016.8.2

Thank you

**Comment by hgy29** [comment]
It is due to the fact that previous implementation used point sprites, which don't have orientation. Next implementation (2016.10) will use quads instead and should be properly oriented.

**Comment by piretro** [comment]
Allright thank you, 
I think that I can close this issue if it has already been fixed in the next release.
