### ISSUE TITLE
Gideros Studio does not support HPPI screens

### ISSUE THREAD

**Issue by GregBreinholt** [gideros/gideros#289]
![capture giderospng](https://cloud.githubusercontent.com/assets/6941844/20245359/a39a8fde-a9da-11e6-8b3d-b5babf809966.PNG)

Gideros Studio is barely usable on HPPI screens, e.g. when Windows scaling is set to 200% (see the image).

**Comment by hgy29** [comment]
I recently acquired a HDPI screen and can confirm the issue. I will have a look at what can be done.

**Comment by GregBreinholt** [comment]
I hope that means you have a fast new laptop?  ;-)
Although its kind of typical how upgrading to new technology brings new issues.

**Comment by hgy29** [comment]
Well it is just a UHD desktop monitor, I had customers complaining about HiDPI issues and needed to see by myself :)
