### ISSUE TITLE
Update google play games AppState to Saved Games API

### ISSUE THREAD

**Issue by l7777777b** [gideros/gideros#291]
The appstate api is deprecated and the doc has been replaced by saved games api.
[https://support.google.com/googleplay/android-developer/answer/6136246?hl=en](https://support.google.com/googleplay/android-developer/answer/6136246?hl=en)

If i'm using more recent version of google play service in android studio, there will be errors because of appstate can't be found or removed from the library. so right now we only can use the lower version of google play library or remove the appstate related code. i wish it could be updated.

**Comment by hgy29** [comment]
This was fixed in gaming plugin in commit ca69d400e2ed8d43eb05f2056d50ba7734552474
