### ISSUE TITLE
iOS Crash: MovieClip

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#292]
Gideros version 2016.8.2.

[com.dsancientgames.ffr_issue_7_crash_89dfcf4e8dca4df48cdd4902a46f22f5_1b186febef404cf9bddd49e12f024b9c_0_v1.txt](https://github.com/gideros/gideros/files/666342/com.dsancientgames.ffr_issue_7_crash_89dfcf4e8dca4df48cdd4902a46f22f5_1b186febef404cf9bddd49e12f024b9c_0_v1.txt)

**Comment by hgy29** [comment]
This one should have been fixed by now, can you confirm ?
