### ISSUE TITLE
Android Crash: Chartboost

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#293]
[com.totebo.fastfoodrampage_issue_7_crash_585A70C502D4000102C4B194E3E7EAC5_2df623963a2848bfb8670b55328feee8_0_v1.txt](https://github.com/gideros/gideros/files/666343/com.totebo.fastfoodrampage_issue_7_crash_585A70C502D4000102C4B194E3E7EAC5_2df623963a2848bfb8670b55328feee8_0_v1.txt)

**Comment by SinisterSoft** [comment]
Has this happened again recently?
