### ISSUE TITLE
loadstring() too slow.

### ISSUE THREAD

**Issue by bugcaptor** [gideros/gideros#297]
The performance of Lua's loadstring () function in Gideros is very slow. I think it's because of the addition of macro features. Loading a large data table is 20 times slower than cjson. (A json data file with the same contents), but when I test it with pure lua, the difference is about 1.7 times. (Based on PC environment) If you roll back the llex.c code that added the macro function, it will be narrowed to about 1.7 times. It looks like it needs to be fixed or rolled back to be similar in performance. 

Maybe it will also affect the speed of a typical Lua script loading?

**Comment by hgy29** [comment]
@Nlcke, can you look at that one ?

**Comment by Nlcke** [comment]
@bugcaptor, attach your data table for tests.

**Comment by SinisterSoft** [comment]
@bugcaptot  Can you try again with the 2017.3.1 version - Macros have been altered and it might be fixed - please try on export too and it may act differently that in the player.

**Comment by hgy29** [comment]
No longer relevant since luau
