### ISSUE TITLE
Controller issue on Windows

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#298]
Gamepad_detectDevices at onEnterFrame make the game lag to 15 fps on some PC.
But can also happen on all PC, by continuously enable and disable a joypad.

https://github.com/gideros/gideros/blob/master/plugins/controller/source/controller.cpp#L227

(I just did make a quick fix by putting Gamepad_detectDevices at :vibrate() and call it when needed to refresh.)

**Comment by SinisterSoft** [comment]
I saw this problem too.  If it's in the next version I can test here.

**Comment by hgy29** [comment]
Everything seemed ok in my recent tests with controller on Windows, so this is issue is probably gone.
