### ISSUE TITLE
Update the gaming plugin API with methods from googleplay plugin

### ISSUE THREAD

**Issue by l7777777b** [gideros/gideros#299]
Currently i'm using googleplay plugin because the method i needed (googleplay:getPlayerScore()) is not implemented in the gaming plugin yet. i hope all of the googleplay plugin's methods can be available in the gaming plugin and then deprecate the googleplay plugin so there is only gaming plugin to be maintained.

**Comment by hgy29** [comment]
Yep thats idea, frankly I wasn't aware that some methods were missing from gaming plugin. Could you maybe make a list of what is missing ? I'll try to port back code from googplay plugin into gaming plugin

**Comment by hgy29** [comment]
googleplay plugin functionnality has been merged into gaming plugin: abfae6f0cec3edf8b538b2577adee5a15d114336
