### ISSUE TITLE
ogl2 possible improvements required

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#30]
By making these improvements:

remove 1.0 limit for rgb multiplier
alpha level for each cell in a tilemap
rgb multiplier for each cell in a tilemap‏

It will make writing arcade games using Gideros much easier as it will then allow maps containing nice alpha and lighting effects, it will also allow sprites to flash to complete white, red, etc...
https://github.com/gideros/gideros/labels

**Comment by ar2rsawseen** [comment]
Have you talked with @hgy29 about this? What is his opinion?

**Comment by hgy29** [comment]
I think it should be possible to enhance some things but hadn't time yet to check what could actually be done, thats why I suggested @SinisterSoft to post its ideas here :)

**Comment by SinisterSoft** [comment]
Alpha and colour added to tilemaps. :)
