### ISSUE TITLE
The problem is in Cyrillic fonts multiline fields

### ISSUE THREAD

**Issue by awkaw** [gideros/gideros#302]
The problem is in Cyrillic fonts multiline fields. The letters jump. Font "Roboto". Russian language

**Comment by awkaw** [comment]
The letters jump in TextWrap. My solution: https://github.com/awkaw/MultiLine

**Comment by hgy29** [comment]
Could you have a go with latest release (2017.10) and see if embedded textwrap function works better than TextWrap.lua ?

**Comment by hgy29** [comment]
Closing this since it should be solved in 2017.10. Reopen if necessary.
