### ISSUE TITLE
iOS: Add encryption by default to avoid warnings when uploading to iTunes

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#304]
iTunes has recently started enforcing this more actively. Could we add the key as default in Gideros? This would avoid manually having to fill in a form each time you upload to iTunes.

Ideally this would only be set when exporting WITH encryption.

![screen shot 2017-02-21 at 14 04 34](https://cloud.githubusercontent.com/assets/4493302/23268489/d3a3f5fc-f9e5-11e6-83c3-52fe838613bb.png)

![screen shot 2017-02-21 at 14 06 03](https://cloud.githubusercontent.com/assets/4493302/23268482/d0251032-f9e5-11e6-935c-c13b1f4d8fc2.png)

**Comment by hgy29** [comment]
Fixed in 2017.3 (through require plugin)
