### ISSUE TITLE
Running Gideros Player from bash/batch

### ISSUE THREAD

**Issue by thronecode** [gideros/gideros#307]
Hello Gideros community. 
How would you go about running the Gideros Player from a command line (bash, batch, anything but that soul freezing blue play button)? 
I'm using an external editor and using my own batch would be extremely helpful! Thank you in advance :smile:

**Comment by ar2rsawseen** [comment]
Very old feature, don't know if still working, not using it, but should be available:
http://giderosmobile.com/forum/discussion/comment/13029#Comment_13029
