### ISSUE TITLE
Does splash screen ad. still appear on gideros-based apps?

### ISSUE THREAD

**Issue by cwchentw** [gideros/gideros#308]
In previous online articles related to gideros studio, these articles mentioned that 
gideros studio will add gideros-ad. splash screen on these apps.  I tried to find answers
toward the issue on gideros website and forum, but failed to find an updated answer.
Do splash screen ad. still appear on these apps?  If yes, can I remove it?  I don't mind 
pay for this function if affordable.

Sorry to use GitHub Issues to ask questions since I have problems confirming mail on
gideros forum.  (The confirming mail didn't send to my mail.)

**Comment by SinisterSoft** [comment]
The splash screen used to appear when Gideros was a commercial product and you didn't have a licence.

The splash screen now is entirely optional.  To change or add a splash screen just right-click the project name, click properties, then click the assets tab.  You can change the splash screen to new image or click 'disable splash' to not have anything appear.

**Comment by hgy29** [comment]
Oh and since you don't need to pay, you can still donate if you like gideros :)

**Comment by cwchentw** [comment]
Thanks for your reply.  I think I may consider gideros for my next app.

**Comment by SinisterSoft** [comment]
You should, it's fast, easy to use, etc...

**Comment by keszegh** [comment]
and feel free to ask on the gideros forum if you have further questions: http://giderosmobile.com/forum/

**Comment by SinisterSoft** [comment]
(I don't think he can register on the forum?)

@cwchentw have you tried using the Facebook or google login, that's how I registered on the forum.

**Comment by cwchentw** [comment]
I just received a confirmation email.  It took days before entering my mailbox?!  Anyway, I can post messages on gideros forum now.
