### ISSUE TITLE
touch.button

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#310]
when mouse events trigger touch events, then the mouse button info should be transferred too.
this way we would not need to handle mouse and touch separately even if mouse button info is needed (in case it is present).

**Comment by alexzheng** [comment]
for a game engine, we really need to check these information that will be seldom used.
will it overload the performance?

**Comment by keszegh** [comment]
i think this is a very useful feature.
hopefully it won't affect performance much, if yes, then perhaps this feature could be settable in the mouse/touch event preferences of the project, and/or be done only on desktop (where computing power is usually much higher).
