### ISSUE TITLE
Hard crash when trying to cache missing Font characters

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#319]
The player shuts down with no error message. Could this throw an error instead?

http://giderosmobile.com/forum/discussion/6606/textarea-gideros-library-for-multiline-text-editing#Item_23

**Comment by hgy29** [comment]
A possile work around was introduced in 97ecef75121cd9bff0bdda9ff861bb97a4eed5d9

**Comment by hgy29** [comment]
Is this still relevant with latest Gideros ?
