### ISSUE TITLE
json plugin value anomaly

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#320]
using json.decode
many times if i have a value stored as -139.89
the value restored is -139.88999999999999
etc with most of the values i store like this (all have 2 precision digits like this one).

**Comment by ar2rsawseen** [comment]
It is not a json problem per se, but rather floating point precision problem and how computer stored floating points. So it is mostly Lua or C specific and only thing is to round up the number to what you expect it to be, like 2 number precision 
http://lua-users.org/wiki/SimpleRound

**Comment by keszegh** [comment]
perhaps it could be done on the c side to make it faster? 
or if this adds a performance hit then it would be good to be able to add to json decode/encode the required precision as a parameter.

**Comment by ar2rsawseen** [comment]
Can't really do that I think, there could be multiple floats in json which require different precision

**Comment by keszegh** [comment]
thanks for the info.
and btw. at least if i store an integer, then they remain an integer, right?

**Comment by ar2rsawseen** [comment]
actually I think in Lua all numbers are stored as double underneath, but for integer, without point, at least it can be determined that expected value is integer and is probably rounded internally.

**Comment by hgy29** [comment]
This is an old issue, and there is nothing we can really do
