### ISSUE TITLE
Can't confirm emal adress in the forum

### ISSUE THREAD

**Issue by zerodarkzone** [gideros/gideros#325]
Hi,
I'm new to gideros and I just registered in the forums, however it has been impossible to confirm my e-mail. Is the forum "blocked"? or is this a bug?

**Comment by piretro** [comment]
It's a bug, sometimes it happens. You can try alternative login methods
(google or facebook)

Il 05/ago/2017 05:48 PM, "zerodarkzone" <notifications@github.com> ha
scritto:

**Comment by zerodarkzone** [comment]
When I try to login with google it says: "No servers found!".
Facebook gets stuck saying "UniqueID is required."

**Comment by mokalux** [comment]
ok so issue should be closed?
