### ISSUE TITLE
IDE close icons are missing on iOS

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#326]
Issue introduced in 2017.8.1
![screen shot 2017-09-11 at 14 14 44](https://user-images.githubusercontent.com/4493302/30276102-9d9f5312-96fb-11e7-844e-a77d97f9b1bd.png)

**Comment by hgy29** [comment]
This is a QT issue. Seems to affect other projects: https://github.com/spyder-ide/spyder/issues/4580

**Comment by hgy29** [comment]
Confirmed: https://bugreports.qt.io/browse/QTBUG-61092
This issue will be fixed with the next QT build (5.9.2)
