### ISSUE TITLE
macOS bug: When double clicking error from output panel, the line of the error is no longer highlighted

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#327]
Introduced in 2017.8.1. This was a real time saver, because you could immediately see the error, without first having to find the line number.

**Comment by hgy29** [comment]
But it was fixed in 2017.8.2, do you still see it ?

**Comment by totebo** [comment]
I think the click functionality was removed entirely in 2017.8.1. in
2017.8.2 the click functionality works, but the line the output refers to
is not highlighted like it used to be, forcing you to read which line
number it is and then find the line number.

**Comment by hgy29** [comment]
What happened is that the addition of the 'Files' and 'Plugins' folder in tree view initially broke file lookup from output pane. It was at least partially fixed in 2017.8.2, but maybe there are still parts of code that need updating.

**Comment by hgy29** [comment]
Just tried: when output pane is clicked, the line is highlighted in light gray with default theme

**Comment by totebo** [comment]
That's exactly what should happen, but doesn't happen for me. I use
2017.8.1. Was this specific behaviour added to 2017.8.2, or is it maybe a
Mac thing??

**Comment by totebo** [comment]
I can confirm the line is not highlighted in 2017.8.2 on Mac.

**Comment by totebo** [comment]
In 2017.11.2 I noticed the error line is now highlighted IF you scroll the scroll bars after double-clicking the error. Mysterious!

**Comment by totebo** [comment]
This is still an issue and causes, like Andrew would put it, death by a thousand cuts in productivity.

**Comment by SinisterSoft** [comment]
Andrew?

**Comment by totebo** [comment]
It's your new name, like it?

**Comment by hgy29** [comment]
I confirm it doesn't work on windows either on recent builds. Investigating...
