### ISSUE TITLE
android unsigned apk export does not work

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#328]
exporting an apk unsigned gives this error when trying to install:
There was a problem parsing the package.

**Comment by hgy29** [comment]
In the end it seems that android strictly forbids installation of unsigned apk on device or emulator.
See this: https://stackoverflow.com/questions/9401922/android-unsigned-app-not-able-to-install-on-device

**Comment by keszegh** [comment]
in one comment at the link it suggests that 'unsigned' actually means that 'signed with a built-in debug key'. can he be right? in any case for convenience gideros could do this for us, 'export unsigned' would then mean that gideros signs it with its own built-in debug key.

**Comment by hgy29** [comment]
That's dangerous, as apk could be submitted to store with this debug key. I suppose android store has special provision for detecting the debug key and refusing it. Anyway anyone wanting to develop for android will need his own keystore at some point, so why not use it right from the start ?

**Comment by keszegh** [comment]
i won't insist, even though when i'm exporting players with various plugins i would find it convenient if there would be no need to sign it.

what confuses me is that i do remember an option in eclipse and/or android studio to export unsigned apk which exported a 'debug' apk which i could nevertheless install on my android machines.
