### ISSUE TITLE
android front camera upside down

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#329]
it seems that the camera plugin renders the front camera upside down (at least on some android devices; on mine it is like that, for additonal indformation: it is camera no. 2 in the camera array). would be good if additional people could test/confirm this bug.

**Comment by hgy29** [comment]
Just read this on SO: https://stackoverflow.com/questions/10283467/android-front-facing-camera-taking-inverted-photos

"If applications want to rotate the picture to match the orientation of what users see, apps should use OrientationEventListener and Camera.CameraInfo. The value from OrientationEventListener is relative to the natural orientation of the device. CameraInfo.orientation is the angle between camera orientation and natural device orientation. The sum of the two is the rotation angle for back-facing camera. The difference of the two is the rotation angle for front-facing camera. Note that the JPEG pictures of front-facing cameras are not mirrored as in preview display."

I don't do the substract part for front cams, I will try this suggestion!

**Comment by hgy29** [comment]
I changed GCamera.java code around line 183 to be like this:
```				
if ((angle%180)!=(info.orientation%180)) { int c=dimret[0]; dimret[0]=dimret[1]; dimret[1]=c; }
if (info.facing == Camera.CameraInfo.CAMERA_FACING_FRONT)
	dimret[2] = (angle - info.orientation + 360) % 360;
else
	dimret[2] = (angle + info.orientation + 360) % 360;
				dimret[3] = 1;
```

And it seems to still work on my device while being what is suggested by android docs. @keszegh, can you try this change at your side ?

**Comment by keszegh** [comment]
it works, now the front camera is not upside down.

on the other hand the front camera is left-right mirroring (so that it works as a mirror and not as a camera), i don't know if that's the intentional default behaviour.

**Comment by hgy29** [comment]
From what I read, it is intentional but not always the case depending on the phone maker. It was part of the orientation issue and why it worked before on my phone but not on yours. So this is fixed.

**Comment by keszegh** [comment]
would it be possible to add it to the camera info whether it is mirrored? e.g. a phone of mine shows you mirrored selfie image but when the photo is shot then it saves the non-mirrored one. to achieve this behaviour one would need to know whether the image was mirrored or not.

**Comment by hgy29** [comment]
Actually there is no indication about this from Android

**Comment by hgy29** [comment]
Ok, so reading here and there it looks like it should always be mirrored on preview (what we use): https://stackoverflow.com/questions/10388789/how-to-keep-android-from-inverting-the-image-from-the-front-facing-camera on Android
Maybe you can just mirror it again when displaying (setScale(-1,1)) if front facing and android ?

**Comment by hgy29** [comment]
On second though, it seems to be the same for iOS, so assume front facing cameras always show mirrored pictures.

**Comment by keszegh** [comment]
so the conclusion is that when cam.position=="front" then on Android and iOS the feed is always mirrored.
sounds good.

**Comment by hgy29** [comment]
yes, which in turns means that you don't need to check the OS since only phones can tell if camera is front facing or backfacing

**Comment by keszegh** [comment]
perfect.
