### ISSUE TITLE
Lua can not supports Chinese variables

### ISSUE THREAD

**Issue by rjdgheart** [gideros/gideros#332]
Hello ,i am chinese,i hope LUA to support Chinese variables,i like lua and like this game engine too,the Chinese variables can help me a lot.
Different countries use different languages of code in Gideros,so cool.

**Comment by hgy29** [comment]
Hi @rjdgheart, can you be abit more explicit about what doesn't work ? What code are you trying to run and what does gideros/lua says about it ?

**Comment by rjdgheart** [comment]
--chinese code
玩家=1               
if 玩家 then
   玩家=玩家+1
end
--American code
player=1               
if player then
   player=player+1
end
--------------------------------------------
I like to use Chinese variables,but Gideros can not,love2d can,but I need the Gideros more.

**Comment by hgy29** [comment]
Ok, looks like lua parser has a problem with non ascii characters. I will see what I can do, thanks for reporting.

**Comment by rjdgheart** [comment]
Thank you for your help.
Different countries use different languages of code in Gideros,so cool.

**Comment by rjdgheart** [comment]
Unfortunately, gideros still cannot support Chinese variables，why did you close this?

**Comment by rjdgheart** [comment]
@hgy29

**Comment by hgy29** [comment]
Because I added necessary code in github in commit https://github.com/gideros/gideros/commit/cfa50c7ba7fde29caad5b24bfe57dfdf5e8be942.
However I did this after releasing 2017.10, so be patient and wait for next release (or build Gideros yourself from sources)
