### ISSUE TITLE
Move completely to LuaJIT 2.1  (edge)

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#34]
It looks like compile-link-run works (no actual JIT on iOS x64 or x32).

https://www.freelists.org/post/luajit/luajit-21-for-arm64-without-real-jit-support

LuaJIT 2.1 can run produce and later run it's own bytecode too, so it's a good way of getting past any current problems with the encryption being easy to hack (you export bytecode rather than source code).

LuaJIT will also make it easier to add c libraries as it can interface directly using Lua.

http://luajit.org/ext_ffi.html

**Comment by hgy29** [comment]
Is this still something we should do ?

**Comment by hgy29** [comment]
No longer relevant I suppose :)
