### ISSUE TITLE
texturepacker not saving last item to txt

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#340]
the texturepacker does not save the last item to the txt, it is present in the png but not in the txt. it happens with a texturepack of 124 textures of mine.

**Comment by SinisterSoft** [comment]
Confirmed.   I'm sure @keszegh will be able to contact you with a link to the files if needed.

**Comment by keszegh** [comment]
indeed, i can send the set of files that produce the error to anyone who can help to correct the bug.

**Comment by hgy29** [comment]
You have one of your files that texturepacker can't load, unfortunately this breaks the whole file list (file names are shifted). I fixed texture packer so that it warns about such issues, and output sensible file list anyway

**Comment by keszegh** [comment]
thanks, once there is a warning about which file causes the problem it will be easy to correct the corrupt file.
