### ISSUE TITLE
win32 error report

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#341]
when a win32 exported app crashes it does not give any meaningful info, so it is a guesswork what went wrong. this way users also cannot report bugs.
so a proper lua error report for win32 crashes would be needed.

**Comment by keszegh** [comment]
thanks, now i will be able to report even more bugs related to win32 export.

**Comment by hgy29** [comment]
Does it actually work ? I added the code but didn't actually try

**Comment by john-blackburn** [comment]
I'm confused by all this. There should be two win32 executables one of
which pops up a console which will contain any Lua errors (and also print
statements). So the issue doesn't arise at all. Or has this changed?

**Comment by hgy29** [comment]
Sure, but the end user won't want the console to be shown I suppose :)

**Comment by keszegh** [comment]
exactly.

**Comment by john-blackburn** [comment]
I see so there is no problem with the developer seeing bugs in win32, just
the end user. One option would be to send the end user both EXEs and link
only the non-console one in the Start Menu. Then, if the user encounters
problems he can run the game again in the console EXE. This would give a
much more comprehensive error report than a single MessageBox could
possibly convey.

**Comment by keszegh** [comment]
it is not always the case that someone can replicate a problem. also it is hard to make people do such complicated things. how it works in the qt export is good, so the same in win32 is a good solution i think.
