### ISSUE TITLE
Please add an api to get the package name and bundle id 

### ISSUE THREAD

**Issue by alexzheng** [gideros/gideros#345]
A unified api to get the package name on Android and the bundle Id on iOS would be useful to verify the package name

**Comment by SinisterSoft** [comment]
Good idea.

**Comment by SinisterSoft** [comment]
application:getAppId()  ?   or have it returned in the in app info ?

**Comment by alexzheng** [comment]
any way is OK.
I think  application:getAppId() is much more straightforward.

**Comment by hgy29** [comment]
Done and checked ok with iOS.
