### ISSUE TITLE
could safeAreaInsets be exported to Lua

### ISSUE THREAD

**Issue by alexzheng** [gideros/gideros#346]
to postion object in safe area for iPhone X, it is needed.
For any others, it can just return 0,0,0,0

**Comment by hgy29** [comment]
Implemented in 2017.11.2, but not tested on iPhone X (it returns 0,0,0,0 on my device). I'll close it, but feel free to reopen if it doesn't give expected results.

**Comment by alexzheng** [comment]
It could be tested on a iPhone X simulator. I wonder whether the value returned by the safeAreaInsets is points,In we used this in our lua code,should it be converted to pixel?

**Comment by hgy29** [comment]
Certainly, but I'll need a better Mac to launch the simulatior :)
I suppose they are returned in device pixels, so logical scale must be applied to them

**Comment by SinisterSoft** [comment]
@alexzheng If you have a possible fix then add it to GitHub and submit, it's easier then to patch it in. :)

**Comment by hgy29** [comment]
BTW I tried with the simulator (painful). new API reports insets as 0	44	44	34 (left,top,right,bottom), which obviously wrong. I must have made a mistake in the code...

**Comment by hgy29** [comment]
found out, will fix it

**Comment by alexzheng** [comment]
will it need to be scaled by this value 
[[UIScreen mainScreen] scale]

**Comment by hgy29** [comment]
since you know what should be done, can you take over and complete/fix what I've done so far ?

**Comment by alexzheng** [comment]
I have not built the source for a long time and my build environment is not work now,may be some dependent libs is outdated.
So, I can not submit code without test.

**Comment by alexzheng** [comment]
I'm using the old build scripts on MAC, I remember you have Introduced a new build makefiles on windows, is that new build system  available on Mac yet?

**Comment by alexzheng** [comment]
for landscape the value should be top, left,bottom,right(0,44,21,44)
for portrait the value should be top, left,bottom,right(44,0,34,0)
I wonder why the struct UIEdgeInsets get by safeAreaInsets is converted to CGRect for return value, 
It would cause confusion for the meaning of each value to other developers reading the code.

**Comment by alexzheng** [comment]
Would that be a little simpler.
BTW, I have not compiled to test it.
void getSafeDisplayArea(int &l,int &t,int &r,int &b)
{
		UIViewController *viewController = g_getRootViewController();
		
		UIEdgeInsets safeArea = [viewController.view safeAreaInsets];
		CGFloat scale = [[UIScreen mainScreen] scale];
		l=safeArea.left * scale;
		t=safeArea.top * scale;
		r=safeArea.right * scale;
		b=safeArea.bottom * scale;
}

**Comment by hgy29** [comment]
well that would surely be, but ATM I am a little fed up with doing this over and over again, each needing to change several files as code is replicated into at least three places.
