### ISSUE TITLE
can not close lua files in Studio in OSX

### ISSUE THREAD

**Issue by zoth** [gideros/gideros#348]
Using build 2017.11.3 running on OSX 10.10.5.
There is no "X" close icon on the lua source tab.
<img width="818" alt="gideros studio" src="https://user-images.githubusercontent.com/991717/34065565-dde5b824-e1b7-11e7-93be-163aa9b9c8a1.png">

**Comment by totebo** [comment]
You can still close the tabs; only the cross is missing.

**Comment by zoth** [comment]
Where on the tab do I click?

**Comment by totebo** [comment]
The right edge, I think. Or left. Try it!

**Comment by hgy29** [comment]
If that helps, I noticed that the close button is shown correctly when using QDark UI theme.

**Comment by zoth** [comment]
Thanks for the tip. I'll try it out.

**Comment by mokalux** [comment]
This issue has been fixed with new gideros. We can close this one?
