### ISSUE TITLE
Signing up issue of Gideros mobile forum

### ISSUE THREAD

**Issue by keewon** [gideros/gideros#349]
Sorry for posting here, but couldn't find other way to ask.

I tried signing up to Gideros mobile forum http://giderosmobile.com/forum/discussions
,but I can't.

Register page just shows form without submit button.
![2017-12-22 11 37 33](https://user-images.githubusercontent.com/227190/34283047-ffda1bb4-e70c-11e7-8e1f-4e362f017024.png)

And when I tried sign up with facebook id, it says 'Your humanity is suspect'
![2017-12-22 11 37 20](https://user-images.githubusercontent.com/227190/34283041-f9e37dcc-e70c-11e7-8994-7d9cc30257e1.png)

I could not sign up to forum, so I could not ask in there.
Thanks!

**Comment by hgy29** [comment]
Hi @keewon,

I am sorry I didn't see this request earlier. You were right, it didn't work, but now it should be ok.
