### ISSUE TITLE
Scale mode constants are nil

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#355]
These scale mode constants are no longer accessible as constants (2018.2.1), to be used with application:setScaleMode():

Application.NO_SCALE
Application.CENTER
Application.PIXEL_PERFECT
Application.LETTERBOX
Application.CROP
Application.STRETCH
Application.FIT_WIDTH
Application.FIT_HEIGHT

**Comment by hgy29** [comment]
Have they ever been ?

**Comment by totebo** [comment]
Very good question, I've actually never used them. I've always seen them in
the doc. :)

**Comment by SinisterSoft** [comment]
I'm sure I used them before.
