### ISSUE TITLE
QT export display not consistent with other exports

### ISSUE THREAD

**Issue by AnthonyBall1966** [gideros/gideros#358]
On most of the exports (android, htm5, etc) and the QT player if you set the logical screen size width and height to the same size (square), the screen width height to 0,0 (auto) and set the scale mode to letterbox then the screen will scale to fill the area and any extra space will have extra game 'footage'.  This allows you to make a game that will scale to any size screen and also work correctly in landscape and portrait.   But with QT export this does not happen - Any extra space will be the background colour rather than game footage.   Can this be changed to match the player and the other exports?

https://files.slack.com/files-pri/T13SUU3TQ-F9EED00BW/2018-02-25_14-37-23.png

**Comment by SinisterSoft** [comment]
Just tried this again on latest version - the extra area is actually white (not the background colour).

What happens though is still different to the other exports.

**Comment by hgy29** [comment]
Closing this since QT export is deprecated anyhow
