### ISSUE TITLE
setting fullscreen does not work together with rendertarget on windows

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#362]
e.g. if you add to the blur example this as the first line then you get only an empty screen:
application:setFullScreen(true)

**Comment by SinisterSoft** [comment]
I just tried it on bird example 2 and the shader is working for me.

**Comment by keszegh** [comment]
interesting. when i export it then it works for me too actually, but it does not in the player.

on the other hand i have some bug like this in my app which remains in the exported version too, but then it seems its harder to replicate it. i will try to give a minimal example.

**Comment by SinisterSoft** [comment]
I tried it in the player - not as an export - can you try the bird 2 demo in the player and see if that works for you too full screen?

**Comment by keszegh** [comment]
does not work for me in the player, if you mean "bird animation 2" example. 
i tried to run the player with both my vga's (intel and nvidia), as it caused problems earlier, but none of them works.

**Comment by hgy29** [comment]
Does it work at all without custom shaders ? Shaders are used internally for every draw operation, even for a simple bitmap.

**Comment by keszegh** [comment]
well, it seems that the bird animation 2 indeed works but in player fullscreen it positions in a strange way so that it sometimes ends up offscreen - i cannot really define the issue, yet changing orientations in player and in app (including scale modes) i can make it end up on screen. 
still, the behaviour seems to be strange, i guess i also reported earlier that fullscreen in gideros player has some problems.
all in all this is not the problem with shaders, so i will try to spot what causes the issue in my app with flickering in full-screen as i still think that it must be shader or rendertarget related as that's all i changed when it started to flicker.

**Comment by keszegh** [comment]
i think this issue as it is can be closed, and i will open another one when i know more, thanks for your help.

**Comment by keszegh** [comment]
i think i managed to find a small code to demonstrate the problem.  creating a renderTarget after setting fullScreen causes a problem.
run this and it will flicker in windows player (for me it does):
application:setFullScreen(true)
rt=RenderTarget.new(300,300)
rt:clear(0)

so the problem is with renderTarget, i changed the issue title accordingly.
btw exporting this, running the exe did not flicker for me for some reason, but in my more complicated app it also flickers in exported app, i guess there i make even more things with rendertargets.

**Comment by keszegh** [comment]
maybe related to issue https://github.com/gideros/gideros/issues/364

**Comment by keszegh** [comment]
it still is a problem in v2018.03.1

**Comment by hgy29** [comment]
Finally had time to have a look, and I can reproduce. Seems like rt:clear(0) triggers the issue (it doesn't happen if disabled). Still investigating...

**Comment by hgy29** [comment]
Ok, looks like this is a QT bug, there have been various reports indicating similar behaviors:
https://forum.qt.io/topic/87874/full-screen-makes-the-screen-flickers-on-windows-8/5
https://www.google.fr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjPmIeQ6IzaAhWLNxQKHVryDuQQFggoMAA&url=https%3A%2F%2Fforum.qt.io%2Ftopic%2F68132%2Fflicker-with-qopenglwidget-when-fullscreen-and-frameless-window&usg=AOvVaw09Wiuyd8a3jrSBkJOZA8Nx

**Comment by keszegh** [comment]
that's worrying, will it be corrected in qt sometime soon? 
isn't there some workaround meanwhile?

**Comment by hgy29** [comment]
Found a true fix :)
