### ISSUE TITLE
Ogg plugin doesn't work on iOS export

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#366]
2018.3.1. Fails because the ogg files are not found. Looks like the files are not being copied properly.

**Comment by hgy29** [comment]
Can you be more precise, which files seem to be missing ?

**Comment by totebo** [comment]
Some more info!

Error:

```
Undefined symbols for architecture x86_64:
  "_g_pluginMain_Ogg", referenced from:
      ___cxx_global_var_init in plugins.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Files:
<img width="284" alt="skarmavbild 2018-03-28 kl 17 39 35" src="https://user-images.githubusercontent.com/4493302/38018192-26e916b8-32af-11e8-967f-971af7edccdf.png">

Export log: [log.txt](https://github.com/gideros/gideros/files/1855159/log.txt)
