### ISSUE TITLE
Crash on app exit for macOS exports

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#367]
Please see attached file. The error is reported from an app exported from an empty Gideros project.

Tested affected Gideros builds: 2018.3, 2018.3.1
Tested not affected Gideros builds: 2018.2.1

To replicate:

1. Export project to macOS
2. Run app
3. Close app
4. Error consistently thrown

[ffr crash on exit.txt](https://github.com/gideros/gideros/files/1854440/ffr.crash.on.exit.txt)

**Comment by hgy29** [comment]
This is the same file related crash we have had on gideros for years, crashing in gvfs while attempting to close the app. It happens sporadically on iOS too

**Comment by totebo** [comment]
It's unlikely to be the same bug, since I can't replicate it on 2018.2.1 and I can replicate it 100% of the time in 2018.3+.

Was something introduced in 2018.3 that could affect this?

**Comment by hgy29** [comment]
Thinking of it, that could come from non-closed files, although I can't think of any changes implying keeping files open between 2018.2.1 and 2018.3

**Comment by totebo** [comment]
It's a strange one. The thing that makes me think there must be something in Gideros is that an empty exported project behaves in a consistent way on the two versions.

**Comment by hgy29** [comment]
The strange things is that this crash should only happen if some file is being forcefully flushed (write) due to exiting the app. That would mean something has actually tried to write data into a file. Is that your case ?
