### ISSUE TITLE
application:set("cursor","cross")  etc seem to be undocumented in reference manual

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#370]

**Comment by keszegh** [comment]
actually all things mentioned here should be added to documentation:
http://forum.giderosmobile.com/discussion/5870/new-desktop-api-test/p1

**Comment by paul-reilly** [comment]
Good point, I'd update the wiki docs! Thanks for pointing this out!

**Comment by keszegh** [comment]
btw application:set("windowModel",type) in particular but cursor etc also should be possible to set independently for each new window created with screen. a Screen:set("windowModel",type) etc. would be great.

**Comment by mokalux** [comment]
the wiki has been updated for application:set() and application:get().

Can we close this issue?
