### ISSUE TITLE
facebook instant game, the progress stops and can not complete.

### ISSUE THREAD

**Issue by ouguolin** [gideros/gideros#372]
I build the example of Button project with all default export settings for facebook instant game: no compress, no encrypt etc. 
I tested the game in a chrome or firefox browser on Macos sierra 10.12.
check the screen shot, progress stops at 5%. you can see the game is loaded and maybe it's working except the progress ui does not disappear.
![screen shot 2018-05-31 at 11 18 30 am](https://user-images.githubusercontent.com/152640/40759758-008e55d4-64c6-11e8-9381-09b9b8281a97.png)
![screen shot 2018-05-31 at 11 19 10 am](https://user-images.githubusercontent.com/152640/40759765-0cffd446-64c6-11e8-9f6e-09260c739b60.png)

**Comment by hgy29** [comment]
hi, I can see in your attached picture that the app is actually running behind Facebook progress bar, which means that you probably forgot to call FBInstant.startGameAsync() API from your app.

**Comment by hgy29** [comment]
For more details take a look at http://docs.giderosmobile.com/reference/fbinstant/fbcore/startGameAsync and http://docs.giderosmobile.com/reference/fbinstant/fbcore#*%20Initialisation%20and%20Core

**Comment by ouguolin** [comment]
hgy29, you are right. 
I forgot to call FBInstant.startGameAsync() API from my app lua code. I didn't know that. just add it at tail of main.lua and it works well.

pcall(function() FBInstant=require "FBInstant" end)
if FBInstant then
	FBInstant.startGameAsync(function()
		print("Loading screen removed")
		FBInstantAPI=true
	end)
else
	print("FBInstant not loaded")
end

thank you!
