### ISSUE TITLE
Android player lacked of box2d module(2018.6 pkg)

### ISSUE THREAD

**Issue by zero-meta** [gideros/gideros#374]
When I require "box2d",  Android player gives me an error: Can not find the module ...
I used the latest version android player.

**Comment by zero-meta** [comment]
So If I want to use box2d in the android live update player.
I must build a "GiderosAndroidPlayer.apk" myself that include liquidfun plugin?

**Comment by hgy29** [comment]
Yes, sorry we forgot to include liquidfun in default players. Anyhow nowadays almost everyone needs a custom player at some point (ads, etc) and they are easy to build: just export a project of your own with the required plugins and select ‘Player (no assets)’ export mode.
