### ISSUE TITLE
getPosition bug

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#38]
Value for Sprite:getPosition returned (x,y,y), and not returned Z position
Sprite:getZ also got this bug

Probably better that set/get position only use/return 2 variable, and separate Z, just like setRotationX & Y.
That way people can safely use a:setPosition( b:getPosition() )

**Comment by ar2rsawseen** [comment]
Bug fixed in https://github.com/gideros/gideros/commit/05593b40ace33659bb65b2a93fd7aebdc5add425

But if Z now returns correct value, would it still mess up your a:setPosition( b:getPosition() ) usage?

**Comment by tkhnoman** [comment]
After trying things, i think it won't affect that much, so it's fine i guess.

**Comment by ar2rsawseen** [comment]
Ok then closing issue
