### ISSUE TITLE
Gideros Player defaults

### ISSUE THREAD

**Issue by flashjaysan** [gideros/gideros#384]
When we alter in any way the settings in Gideros Player, it keeps those modification for all following projects. What if Gideros Player adapts its defaults settings to the logical dimensions of the project when we open a new one? The physical dimensions and also the dimensions of the window containing Gideros Player.

**Comment by hgy29** [comment]
Wouldn't you want physical size to match your display size rather than logical size ? logical size aren't pixels, it is whatever the dev want: one could set the logical size to 1x1 and treat coordinates in the range [0-1], and probably not want the window to be 1 pixel in size

**Comment by flashjaysan** [comment]
Yes. You got me on that. Didn't thought of that kind of occurrence.
