### ISSUE TITLE
File -> New Project typo

### ISSUE THREAD

**Issue by flashjaysan** [gideros/gideros#385]
I'm on Windows and I'm running Gideros 2018.6.2. The New Project option in the File menu is written :
New Project.. (only 2 dots)
It should be :
New Project... (with 3 dots)

**Comment by hgy29** [comment]
Shouldn't it be 'New Project', without any dots ?

**Comment by flashjaysan** [comment]
Well, if I'm correct, when a menu opens a dialog window, it got three dots. But I may be wrong.

**Comment by hgy29** [comment]
That could be changed as well. I am not sure people do care anyhow :)

**Comment by flashjaysan** [comment]
I don't care about this either. I only found a typo.
