### ISSUE TITLE
Feature request: Flag to get solid pixel boundaries from getTextureRegion()

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#386]
texture_pack:getTextureRegion() returns the original png bitmap size, even if TexturePacker has stripped transparent pixels. This is good and useful.

Would it be possible to add a flag to allow getting the texture region without the whitespace? This is included in the exported sprite sheet from TexturePacker, but just not accessible via the API yet.

Maybe something like:

local non_transparent_bounds = true
x,y,w,h = texture_pack:getTextureRegion( non_transparent_bounds )

**Comment by SinisterSoft** [comment]
Good idea.
On 22/07/2018 21:27:05, totebo <notifications@github.com> wrote:
texture_pack:getTextureRegion() returns the original png bitmap size, which is good.
Would it be possible to add a flag to allow getting the texture region without the whitespace? This is included in the exported sprite sheet from TexturePacker, but just not accessible via the API yet.
Maybe something like:
local non_transparent_bounds = true
x,y,w,h = texture_pack:getTextureRegion( non_transparent_bounds )

**Comment by hgy29** [comment]
I can't see it in exported texture/text file, where is it ?

**Comment by hgy29** [comment]
Hmm, I think I understand now, and if I am correct then you already have it:
x,y,w,h,dx1,dy1,dx2,dy2=texture_pack:getTextureRegion(region):getRegion().
d[x,y][1,2] are the transparent sizes before and after the region

**Comment by totebo** [comment]
Oh really, wow! Don't think that's documented, though?

**Comment by hgy29** [comment]
Correct! So this more a doc issue!

**Comment by hgy29** [comment]
Is that better: http://docs.giderosmobile.com/reference/gideros/TextureRegion/getRegion#TextureRegion:getRegion ?

**Comment by totebo** [comment]
Much better, and ridiculous! :)
