### ISSUE TITLE
bad html in some web doc pages :

### ISSUE THREAD

**Issue by stanpetit** [gideros/gideros#393]
Hi !
http://docs.giderosmobile.com/reference/physics/b2World/createJoint#b2.World:createJoint
and
http://docs.giderosmobile.com/reference/physics/b2World/createBody#b2.World:createBody
text renders with html tags ...

Best, 
Stan

**Comment by mokalux** [comment]
I think this has been fixed, should close this issue.

**Comment by hgy29** [comment]
Yes, those old docs are officially depreciated now, closing as 'Won't Fix' :)
