### ISSUE TITLE
Kiip plugin doesn't work on Android

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#396]
Android Studio error:

```
No resource identifier found for attribute 'appComponentFactory' in package 'android'
Message{kind=ERROR, text=No resource identifier found for attribute 'appComponentFactory' in package 'android', sources=[/Volumes/H/Temp/No Brakes Builds/Android Studio/No Brakes/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:59], original message=, tool name=Optional.of(AAPT)}
```

This line is marked red on export:
`QDir::mkpath: Empty or null file name`

Full export log attached.

[log.txt](https://github.com/gideros/gideros/files/2277943/log.txt)

**Comment by hgy29** [comment]
How can that be ? file name doesn't seem empty by the look of your log. Code is here: https://github.com/gideros/gideros/blob/master/gdrexport/ExportXml.cpp#L389

**Comment by totebo** [comment]
It's strange. I've filled in the required fields. Does it work when you export it?

**Comment by totebo** [comment]
Think this is still relevant.

**Comment by hgy29** [comment]
Seems like Kiip is dead, so closing this.
