### ISSUE TITLE
[IDE] Editor key bindings on OSX

### ISSUE THREAD

**Issue by zv20000** [gideros/gideros#41]
The usual text editing key combinations don't function in Gideros IDE since v2014.01:
  - Command + ArrowLeft/ArrowRight to jump to the beginning/end of the current line
  - Alt + ArrowLeft/ArrowRight to jump to the beginning of the previous/next word
In fact, the second combination Alt+Arrows mimics the function of the first, Command + Arrow, so I suppose there's just a wrong link somewhere.

**Comment by ar2rsawseen** [comment]
Just to update, the issue seems to be related to QScintilla
I've tried to upgrade QScintilla dependency to the latest version, but failed to make it work, so postponing this issue a little more

**Comment by zv20000** [comment]
On the Wiki page
    http://giderosmobile.com/DevCenter/index.php/Build_Gideros_On_Mac
it states:
"goto folder Qt4/Qt5 edit `qscicommandset.cpp` and put line
    #define DONT_USE_OSX_KEYS
after the includes"

May this be a problem?

**Comment by ar2rsawseen** [comment]
I thought build script I used was supposed to do that, but I'll recheck on next update ;)

**Comment by zv20000** [comment]
About scripts - could you give me a hint about the directory structure supposed to exist? At least /Volumes/gideros and ~/myprojects/gideros are missing on my Mac, are they the same? Or is somewhere a script or Wiki page describing this issue? (sorry to bother you, but I haven't found anything about this) The "Gideros Player.app" insists to be <1MB after the script run.

**Comment by ar2rsawseen** [comment]
It depends on what you want to build, and for which purpose.
You may want to build separate components as Gideros Player or Gideros Studio and you may want to build either of them for development (modify and rebuild) or once, create and package to use.

Which one is it? :)

**Comment by zv20000** [comment]
I want it all! :-)
Sincerely, I think about developing a plugin, maybe based on Microphone, and I thought building everything may be a good entry point (btw., I haven't managed to record anything on my Android devices with that Microphone thing). And then, there is this issue with the command key on OSX, so I'd need at least a new Studio on OSX and the plugins for Android+iOS. I'm also interested in building the core libgideros and maybe enhance that with the sound processing elements I think about, I need direct [and real-time] access to the waveforms produced by the microphone and prepare the waveforms to be played by the Sound[Channel]. Ideally this would be offered by the system (Gideros), but we don't live in an ideal world :-D

**Comment by ar2rsawseen** [comment]
Ok then you need to install QT 5.4 with QT creator on your mac

Honestly I have not tried building a player on Mac, I do it on Windows, but the steps should be similar.

You should go to each folder and build .pro projects with QT creator in this order:
libpystring
libgvfs
lua
libgid
libgideros

then go to player folder and build player_qt5.pro project

After that there should be a script to copy proper libraries and link them

Something like this:
https://github.com/gideros/gideros/blob/master/scripts/copyqt5.sh

Unfortunately I'm not that familiar with OSX linking process :)

With Gideros Studio you need to build QTScintilla first, as you specified in the link

**Comment by zv20000** [comment]
Thanks, I've done that Qt stuff already and still end up with a 2.1MB player app. Interestingly, the all_mac.sh has created a functioning player of 54MB in "build" but a 0.5MB small Studio app.
I give it up, I've chosen Gideros some years ago because I didn't want to mess around with such things like compiling from source without any documentation. Maybe writing a plugin from scratch would be simpler!?

**Comment by ar2rsawseen** [comment]
You just need to speak with someone who does Gideros development on OSX, like @marceloLiberton 
You can try to PM him on forum. Or if you want I can add you to core team skype group.

But yes, generally, for plugin, you don't need to build Gideros, any of released versions will do.
First you need to chose platform for which to develop plugin, like if Android, then you can follow my blog post here:
http://appcodingeasy.com/Gideros-Mobile/Creating-plugins-for-Android-in-Gideros

But ios would probably be the easiest to start since you probably already have xcode and you can write plugin code and test it in same xcode app's project you are going to use it on.

**Comment by zv20000** [comment]
Thanks for your advice. I've managed to set up my own plugin and, more than that, I've got instant access to the OpenAL engine initialized within libgideros. Great thing! :-D
I've also set up a new issue #73 with the link to the newer OpenAL version.

**Comment by ar2rsawseen** [comment]
I think that I finally fixed this issue, but I'm using remote desktop to work on Mac, so can't say for sure, but at least it seems behavior matches what was in older Gideros.
So closing this issue for now, soon will be a new release 2015.09, retry in it and reopen the issue if problem still persists ;)

**Comment by zv20000** [comment]
Wonderful, it works like expected! Many thanks, this new version will be my new favourite one :-)
And also thank you for the many hours of coding, this new kind of Gideros you are developing is becoming more and more a full-featured, no-whishes-left-over product.
z
