### ISSUE TITLE
Deprecated plugins warning

### ISSUE THREAD

**Issue by Apollo144** [gideros/gideros#416]
Hi!
Probably in plugins list it's better to add "(deprecated)" text to deprecated plugins, like this one:
https://imgurhd.ru/i/3p1l_orig.png

And in 'Gaming' plugin it's better to add "(Amazon)" to field "Api Key"
https://imgurhd.ru/i/3p1k_orig.png
(When I first used it, I was confused, I thought it was Google's api key, but found on forum that this field is only for Amazon)

Thanks!

**Comment by hgy29** [comment]
Amazon will be removed in next version
