### ISSUE TITLE
image scaling for TileMap doesn't work after 2017.11.3

### ISSUE THREAD

**Issue by Apollo144** [gideros/gideros#422]
> When set suffix @2x for scale 2, it works well in TileMap,but from 2017.11.3 it won't work.

> release 2017.11.3 add image scaling for TileMap,but it seems it doesn't work, before this release,image scaling in TileMap works. 

http://forum.giderosmobile.com/discussion/7456/image-scale-was-not-supported-in-tilemap-in-2017-11-3#latest

**Comment by hgy29** [comment]
Fixed in 90b35da34172cfa7b56d1f9c079e08cecb1ebf21
