### ISSUE TITLE
Building for iOS - strange bug

### ISSUE THREAD

**Issue by kappacoder** [gideros/gideros#432]
Hi guys, today while I was building for iOS I noticed that some of the .lua files don't get included
in the build which causes the apps to crash when testing on device.

Even more strange is that I noticed this happens only to simple module files of the following kind:

```
-- test.lua
local m = {}
-- some code here
return m
```
And then when calling require("test") in another place it will crash.

All other files ( scenes, Classes definitions, etc. ) seem to be bundled in the Xcode project.

The solution to this is I copy the missing files manually and add them to the assets folder of the xcode build. However, this gets tiresome every time I have to build.

Hopefully, it will be fixed soon.

**Comment by hgy29** [comment]
Hi, by default all lua files are merged into a single main.lua file during export. If you want to ‘require’ some of them, mark them as don’t execute (or something like that) in Gideros Studio

**Comment by kappacoder** [comment]
Thanks for the fast reply!

I see now that in Gideros Studio there is an option "Never encrypt" when right clicking a file. Is this what must be done for these kind of files?

**Comment by hgy29** [comment]
No, never encrypt will just leave your file unencrypted, that’s something else, only applicable to lua files, exclude from compilation maybe...

**Comment by kappacoder** [comment]
Found it ->"Exclude from execution"
Really appreciate your help!

**Comment by hgy29** [comment]
I assume it is 'fixed' then :)
