### ISSUE TITLE
Feature request: Particle X and Y Speed and Decay 

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#434]
Speed and decay in both X and Y axis separately, to allow more complex particle movements such as arcs, bounces, circular motions etc.

**Comment by totebo** [comment]
Still relevant.

**Comment by hgy29** [comment]
Speed is already separate and X and Y, but yes, decay isn't

**Comment by hgy29** [comment]
Commit fd81ee77f6c156f270134144cdadf8f1ed8fea89 fixes it, and add acceleration support at the same time.
