### ISSUE TITLE
Font outlines are slightly offset when the player is set to arbitrary dimensions 

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#439]
Minimal project: [Archive.zip](https://github.com/gideros/gideros/files/2466162/Archive.zip)

With "Hardware/Auto Scale" set, or exported to HTML5:
![screen shot 2018-10-10 at 20 15 08](https://user-images.githubusercontent.com/4493302/46760214-59b00200-ccc9-11e8-9d73-fd618a4d40c8.png)

With "Hardware/Auto Scale" not set, or exported to iOS/Android:
![screen shot 2018-10-10 at 20 15 16](https://user-images.githubusercontent.com/4493302/46760216-5b79c580-ccc9-11e8-9e95-3fad2935b9b2.png)

Changing the sample string changes the result with auto scale enabled, but not with it disabled. 

Lua code:

```
-- Properties
local str_cached_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
local str_sample = "W"
local str = "test" 
local line_thickness = 3
local size = 100
local x = 100
local y = 100

-- Bg
local font = TTFont.new( "DenkOne-Regular.ttf", size, str_cached_chars, true, line_thickness )
local textfield_bg = TextField.new( font, str, str_sample )
textfield_bg:setPosition( x-line_thickness,y-line_thickness )
stage:addChild( textfield_bg )

-- Fg
local font = TTFont.new( "DenkOne-Regular.ttf", size, str_cached_chars, true, 0 )
local textfield_fg = TextField.new( font, str, str_sample )
textfield_fg:setPosition( x,y )
textfield_fg:setTextColor( 0xa2bcac )
stage:addChild( textfield_fg )
```

**Comment by totebo** [comment]
Still relevant.

**Comment by hgy29** [comment]
Does CompositeFont (2019.1) fix it ?

**Comment by totebo** [comment]
YES! I opened the test project from the post, and it works now. Haven't tested HTML5, but looks hopeful.
