### ISSUE TITLE
screen:setShader() does not work

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#443]
screen:setShader() does not work, which would be ok, but reference guide says that Screen inherits Sprite and this is then inconsistent with what happens.

**Comment by paul-reilly** [comment]
Thanks for reporting, this is an error in the docs. Screen doesn't inherit from Sprite which explains what you are (not) seeing.

**Comment by hgy29** [comment]
This is because setShader only applies to the sprite itself, not its children. stage doesn't draw anything on its own. The same way setShader does nothing on Sprite or Viewport.
