### ISSUE TITLE
Event.KEY_DOWN and Event.KEY_UP should also have alt,ctr,shift modifiers

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#447]

**Comment by keszegh** [comment]
it would be great if this could be added as keeping track of modifiers being pressed is not completely accurate, e.g. when the app window is changed to another window with alt-tab then the alt is pressed inside the app but released outside and so when i return to the app window then it mistakenly thinks that alt is still pressed.
in short, there is no proper workaround for this feature.

**Comment by keszegh** [comment]
a function like application:isPressed(keyCode,realCode) would also solve this issue. 
or at least application:isCtrlPressed() etc. for the modifier buttons.

**Comment by keszegh** [comment]
it seems that application:isCtrlPressed()  etc. could be implemented:
https://doc.qt.io/qt-5/qguiapplication.html#queryKeyboardModifiers

**Comment by mokalux** [comment]
I am not sure how to listen to a key press and a modifier:
Is it the right way?

**-- key modifiers
function onKeyDown(e)
	if e.keyCode == KeyCode.CTRL then isctrl = true end
	if e.keyCode == KeyCode.G then isg = true end

	print(e.keyCode, e.realCode)
	if isctrl and isg then print("gideros A") isg = false end
end

function onKeyUp(e)
	if e.keyCode == KeyCode.CTRL then isctrl = false end
	if e.keyCode == KeyCode.G then isg = false end

	print(e.keyCode, e.realCode)
end

stage:addEventListener(Event.KEY_DOWN, onKeyDown)
stage:addEventListener(Event.KEY_UP, onKeyUp)**

How do you do it in gideros 2020.4?

**Comment by keszegh** [comment]
@mokalux , yes, this should work.
although it does not solve the issue.

**Comment by keszegh** [comment]
fantastic, thanks.
