### ISSUE TITLE
Focused window on Desktop

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#45]
Would be best to fire Event.APPLICATION_BACKGROUND and Event.APPLICATION_FOREGROUND upon window lost focus and get focus.

Or probably Event.APPLICATION_RESUME and Event.APPLICATION_SUSPEND.

**Comment by tkhnoman** [comment]
This is actually important, because it can be a bug.
I need it because touch_cancel is not being fired when application lost focus, for example when touch happened, and mouse goes over the bound, and then alt + Tab pressed, it did not get any touchesEnd or touchesCancel.

The same thing with Event.KEY_UP and for joystick.

**Comment by ar2rsawseen** [comment]
Added in https://github.com/gideros/gideros/commit/df1fea64e6e0b2335ba25a48ad808ccb06a56290
