### ISSUE TITLE
Add "Consolidate Project" studio command [enhancement]

### ISSUE THREAD

**Issue by piretro** [gideros/gideros#457]
Hi, 
since Gideros is able to pull files from all around the harddrive, I think it would be useful to have a menu command in Gideros Studio to copy everything from the original location to a new one, keeping directory structure as it is in the project tree (replicating the project tree in the local harddrive, with relative contained files), while updating the file paths in the project file. 

This would be handy when it's needed to move a project to another laptop or share it with someone.

It would work as a "Save as..."

Thank you

**Comment by mokalux** [comment]
why don't you just copy your project directory? I don't see any issue here. I propose to close it?!

**Comment by hgy29** [comment]
Well you can link assets from anywhere on your hard drive with gideros, which is an issue when you want to archive your project. I proposed this consolidate option in the forum a few months ago, which would remove links and copy files back to your project folder instead. This is still relevant I think.

**Comment by piretro** [comment]
I agree, consolidate would be useful

Il Sab 14 Set 2019, 06:34 Nicolas Bouquet <notifications@github.com> ha
scritto:

**Comment by mokalux** [comment]
oh yes I forgot about those outside links, I must have misunderstood the question.
I agree with you, this would be a nice enhancement indeed.

**Comment by hgy29** [comment]
Implemented in f9cf12dbd51aa9c33030fad4fe9cbbe351ec6d7f
