### ISSUE TITLE
Gideros freezes on macOS Mojave

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#458]
Freezes for around 25 seconds when:

- As Gideros is about to be opened
- As a project is about to be exported
- As files are about to be added

**Comment by hgy29** [comment]
Not a solution but a few links I gathered that may relate to this issue:
- https://forums.appleinsider.com/discussion/206106/why-macos-mojave-requires-metal-and-deprecates-opengl
- https://bugreports.qt.io/browse/QTBUG-68891

Didn't find anything about slowness though

**Comment by totebo** [comment]
Cool, may be related. It's beyond "slow" though; the computer freezes entirely, with the only thing working being the mouse pointer/spinny wheel.

**Comment by hgy29** [comment]
Still no clue about this. I had a chance to try on a Mojave powered MacBook Pro, and no slowness...

**Comment by totebo** [comment]
Just to show you the pain:
https://youtu.be/_zgI4fdXFso

**Comment by totebo** [comment]
Before you say it: Yes, it might be something outside of Gideros, but I haven't seen it in any other application! And I use a lot of apps. :)

**Comment by totebo** [comment]
Fix: http://forum.giderosmobile.com/discussion/7572/gideros-ide-freezes-for-20-seconds-on-macos-mojave?new=1
