### ISSUE TITLE
Offline documentation doesn't work out of the box

### ISSUE THREAD

**Issue by VedVid** [gideros/gideros#461]
There are "Getting Started" and "Reference Manual" buttons on starting screen of GiderosStudio and "Help & Support" and "Documentation" in Help menu. None of them work. The first ones doesn't trigger anything, and the second ones just defocuses Studio window. I don't see any "docs" directory in installation folder.

I believe it may be old issue, but I can confirm it only for two versions: 2018.12 and 2019.1. 

Tested on Windows 10 64-bit.

edit: I'm not sure how exactly offline docs are supposed to work... But I tried to use doc directory from downloaded repository, and it didn't work either at first. By default, I'm using Firefox (it's up to date). There was no reaction to [open] command. Still, I was able to run index and other files by Internet Explorer / Microsoft Edge and Chrome.

edit2: Changing default web browser from Firefox to Edge / Chrome didn't change lack of response from GiderosStudio buttons.

**Comment by SinisterSoft** [comment]
On the start screen they appear to do nothing I agree.

On the help menu, for me (win 10 x64), they go to these:

Help and support: http://forum.giderosmobile.com/

Documentation:  https://wiki.giderosmobile.com/index.php/Welcome!




On 08/01/2019 19:54:48, Ved <notifications@github.com> wrote:
There are "Getting Started" and "Reference Manual" buttons on starting screen of GiderosStudio and "Help & Support" and "Documentation" in Help menu. None of them work. The first ones doesn't trigger anything, and the second ones just defocuses Studio window. I don't see any "docs" directory in installation folder.
I believe it may be old issue, but I can confirm it only for two versions: 2018.12 and 2019.1.
Tested on Windows 10 64-bit.

**Comment by hgy29** [comment]
Buttons links hadn't been updated, this is fixed now (8ed0b487f6f63600a09c012157c94a792350d4a4).
