### ISSUE TITLE
iOS Gamekit Player scope (ALL_PLAYERS / FRIENDS) values are wrong

### ISSUE THREAD

**Issue by hasanalperen1** [gideros/gideros#462]
In (iOS) gamificationbinder.cpp , FRIENDS = 0 and ALL_PLAYERS = 1 are wrong.
It should be **FRIENDS = 1** and **ALL_PLAYERS = 0**

https://developer.apple.com/documentation/gamekit/gkleaderboard/playerscope/global
https://developer.apple.com/documentation/gamekit/gkleaderboard/playerscope/friendsonly

**Comment by hgy29** [comment]
Fixing, thanks.
