### ISSUE TITLE
Sprite:toggleVisibility() #enhancement

### ISSUE THREAD

**Issue by Apollo144** [gideros/gideros#463]
Hi guys!
imo Sprite:toggleVisibility() could be nice little enhancement.
Thx! :)

**Comment by Apollo144** [comment]
maybe timer and sounds also...
```
Timer:toggle()
SoundChannel:toggle()
```

**Comment by mokalux** [comment]
> 
> 
> Hi guys!
> imo Sprite:toggleVisibility() could be nice little enhancement.
> Thx! :)

why not use sprite:setVisible(bool)?
