### ISSUE TITLE
Gideros Player don't work on Linux (ArchLinux) : Seg Fault

### ISSUE THREAD

**Issue by MohamedLEGH** [gideros/gideros#465]
Hello,
I tried Gideros on my computer (Lenovo Thinkpad x230 with ArchLinux).
I can start Gideros Studio, Texture Packer and Font Creator without any problems but I cannot run Gideros Player.

I tried with Wine and also to compile it.
If I try to run it inside Gideros Studio, nothing happens.
If I try to run it directly, I have the following (not really helpful) message 
: ```[1]    22310 segmentation fault (core dumped)  ./GiderosPlayer```

**Comment by hgy29** [comment]
Hi @MohamedLEGH, I suspect it may be due to OpenGL drivers, faulty or absent somehow. Can you try to get a stack trace ? since you compiled it you should be able to run it under QtCreator in debug mode (open player/player.pro).

**Comment by MohamedLEGH** [comment]
When I try to run the file (player/player_qt5.pro) with QtCreator (normal run) : I get the following messages : 
```
15:13:12: Starting /home/mohamed0/Gideros/gideros/player/GiderosPlayer...
ANOM_ABEND auid=1000 uid=1000 gid=10 ses=2 pid=15049 comm="GiderosPlayer" exe="/home/mohamed0/Gideros/gideros/player/GiderosPlayer" sig=11 res=1
15:13:13: The program has unexpectedly finished.
15:13:13: The process was ended forcefully.
15:13:13: /home/mohamed0/Gideros/gideros/player/GiderosPlayer crashed.
```

When I try to run it in debug mode (with gdb), it told me that there is no debugging symbols (I'm sorry I'm a total noob with Qt Creator), **do you know how and where I should add debugging symbols ?**

By the way, this is the dessasembly of the program I get with the debug mode: 
```
0x7ffff665cf20                  f3 0f 1e fa                    endbr64
0x7ffff665cf24  <+    4>        53                             push   %rbx
0x7ffff665cf25  <+    5>        48 83 ec 10                    sub    $0x10,%rsp
0x7ffff665cf29  <+    9>        48 8b 05 b0 7f 13 00           mov    0x137fb0(%rip),%rax        # 0x7ffff6794ee0
0x7ffff665cf30  <+   16>        48 8b 00                       mov    (%rax),%rax
0x7ffff665cf33  <+   19>        48 85 c0                       test   %rax,%rax
0x7ffff665cf36  <+   22>        0f 85 84 00 00 00              jne    0x7ffff665cfc0 <free+160>
0x7ffff665cf3c  <+   28>        48 85 ff                       test   %rdi,%rdi
0x7ffff665cf3f  <+   31>        74 6f                          je     0x7ffff665cfb0 <free+144>
0x7ffff665cf41  <+   33>        48 8b 47 f8                    mov    -0x8(%rdi),%rax
0x7ffff665cf45  <+   37>        48 8d 77 f0                    lea    -0x10(%rdi),%rsi
0x7ffff665cf49  <+   41>        a8 02                          test   $0x2,%al
0x7ffff665cf4b  <+   43>        75 3b                          jne    0x7ffff665cf88 <free+104>
0x7ffff665cf4d  <+   45>        48 8b 15 bc 7d 13 00           mov    0x137dbc(%rip),%rdx        # 0x7ffff6794d10
0x7ffff665cf54  <+   52>        64 48 83 3a 00                 cmpq   $0x0,%fs:(%rdx)
0x7ffff665cf59  <+   57>        0f 84 a1 00 00 00              je     0x7ffff665d000 <free+224>
0x7ffff665cf5f  <+   63>        48 8d 3d 3a 8b 13 00           lea    0x138b3a(%rip),%rdi        # 0x7ffff6795aa0 <main_arena>
0x7ffff665cf66  <+   70>        a8 04                          test   $0x4,%al
0x7ffff665cf68  <+   72>        74 0c                          je     0x7ffff665cf76 <free+86>
0x7ffff665cf6a  <+   74>        48 89 f0                       mov    %rsi,%rax
0x7ffff665cf6d  <+   77>        48 25 00 00 00 fc              and    $0xfffffffffc000000,%rax
0x7ffff665cf73  <+   83>        48 8b 38                       mov    (%rax),%rdi
0x7ffff665cf76  <+   86>        48 83 c4 10                    add    $0x10,%rsp
0x7ffff665cf7a  <+   90>        31 d2                          xor    %edx,%edx
0x7ffff665cf7c  <+   92>        5b                             pop    %rbx
0x7ffff665cf7d  <+   93>        e9 8e c6 ff ff                 jmpq   0x7ffff6659610 <_int_free>
0x7ffff665cf82  <+   98>        66 0f 1f 44 00 00              nopw   0x0(%rax,%rax,1)
0x7ffff665cf88  <+  104>        8b 15 86 81 13 00              mov    0x138186(%rip),%edx        # 0x7ffff6795114 <mp_+52>
0x7ffff665cf8e  <+  110>        85 d2                          test   %edx,%edx
0x7ffff665cf90  <+  112>        75 11                          jne    0x7ffff665cfa3 <free+131>
0x7ffff665cf92  <+  114>        48 3b 05 57 81 13 00           cmp    0x138157(%rip),%rax        # 0x7ffff67950f0 <mp_+16>
0x7ffff665cf99  <+  121>        76 08                          jbe    0x7ffff665cfa3 <free+131>
0x7ffff665cf9b  <+  123>        48 3d 00 00 00 02              cmp    $0x2000000,%rax
0x7ffff665cfa1  <+  129>        76 2d                          jbe    0x7ffff665cfd0 <free+176>
0x7ffff665cfa3  <+  131>        48 83 c4 10                    add    $0x10,%rsp
0x7ffff665cfa7  <+  135>        48 89 f7                       mov    %rsi,%rdi
0x7ffff665cfaa  <+  138>        5b                             pop    %rbx
0x7ffff665cfab  <+  139>        e9 90 b6 ff ff                 jmpq   0x7ffff6658640 <munmap_chunk>
0x7ffff665cfb0  <+  144>        48 83 c4 10                    add    $0x10,%rsp
0x7ffff665cfb4  <+  148>        5b                             pop    %rbx
0x7ffff665cfb5  <+  149>        c3                             retq
0x7ffff665cfb6  <+  150>        66 2e 0f 1f 84 00 00 00 00 00  nopw   %cs:0x0(%rax,%rax,1)
0x7ffff665cfc0  <+  160>        48 8b 74 24 18                 mov    0x18(%rsp),%rsi
0x7ffff665cfc5  <+  165>        48 83 c4 10                    add    $0x10,%rsp
0x7ffff665cfc9  <+  169>        5b                             pop    %rbx
0x7ffff665cfca  <+  170>        ff e0                          jmpq   *%rax
0x7ffff665cfcc  <+  172>        0f 1f 40 00                    nopl   0x0(%rax)
0x7ffff665cfd0  <+  176>        48 39 35 c1 a7 13 00           cmp    %rsi,0x13a7c1(%rip)        # 0x7ffff6797798 <dumped_main_arena_start>
0x7ffff665cfd7  <+  183>        77 09                          ja     0x7ffff665cfe2 <free+194>
0x7ffff665cfd9  <+  185>        48 39 35 b0 a7 13 00           cmp    %rsi,0x13a7b0(%rip)        # 0x7ffff6797790 <dumped_main_arena_end>
0x7ffff665cfe0  <+  192>        77 c1                          ja     0x7ffff665cfa3 <free+131>
0x7ffff665cfe2  <+  194>        48 83 e0 f8                    and    $0xfffffffffffffff8,%rax
0x7ffff665cfe6  <+  198>        48 89 05 03 81 13 00           mov    %rax,0x138103(%rip)        # 0x7ffff67950f0 <mp_+16>
0x7ffff665cfed  <+  205>        48 01 c0                       add    %rax,%rax
0x7ffff665cff0  <+  208>        48 89 05 e9 80 13 00           mov    %rax,0x1380e9(%rip)        # 0x7ffff67950e0 <mp_>
0x7ffff665cff7  <+  215>        eb aa                          jmp    0x7ffff665cfa3 <free+131>
0x7ffff665cff9  <+  217>        0f 1f 80 00 00 00 00           nopl   0x0(%rax)
0x7ffff665d000  <+  224>        48 8b 15 11 7d 13 00           mov    0x137d11(%rip),%rdx        # 0x7ffff6794d18
0x7ffff665d007  <+  231>        64 80 3a 00                    cmpb   $0x0,%fs:(%rdx)
0x7ffff665d00b  <+  235>        0f 85 4e ff ff ff              jne    0x7ffff665cf5f <free+63>
0x7ffff665d011  <+  241>        48 89 fb                       mov    %rdi,%rbx
0x7ffff665d014  <+  244>        48 89 74 24 08                 mov    %rsi,0x8(%rsp)
0x7ffff665d019  <+  249>        e8 12 ea ff ff                 callq  0x7ffff665ba30 <tcache_init.part.6>
0x7ffff665d01e  <+  254>        48 8b 43 f8                    mov    -0x8(%rbx),%rax
0x7ffff665d022  <+  258>        48 8b 74 24 08                 mov    0x8(%rsp),%rsi
0x7ffff665d027  <+  263>        e9 33 ff ff ff                 jmpq   0x7ffff665cf5f <free+63>
```

The program crash at the line 10 : 
```
0x7ffff665cf41  <+   33>        48 8b 47 f8                    mov    -0x8(%rdi),%rax
```

hope this help

**Comment by hgy29** [comment]
You should have the 'start debug run' option (F5). It may not work right from the start though, because it will try to compile gideros, player but not support libs. you can copy the non qt .so files from normal build to debug build folder (pystring.so, gid.so, gideros.so,gvfs.so and lua.so) and start debug again once they are in place

**Comment by MohamedLEGH** [comment]
This is what I get when I run F5 (the compilation works fine, but running is not working at all)

![screen1_qt](https://user-images.githubusercontent.com/15138914/55561784-17550400-56f3-11e9-8715-95a1232033fd.png)

![screen2_qt](https://user-images.githubusercontent.com/15138914/55561783-16bc6d80-56f3-11e9-8346-37b3b59f8537.png)

**Comment by hgy29** [comment]
Can you try to click on the fourth icon from the bottom-left side and change it to Debug instead of Release ? Then run again in debug mode and you should have symbols.

**Comment by MohamedLEGH** [comment]
I don't have a debug mode : 
![qtCreator1](https://user-images.githubusercontent.com/15138914/55718351-c9dedc80-59fb-11e9-81ff-b0d234f5dbea.png)

I think on Linux Qt Creator doesn't generate a debug mode automatically. 

I can create one manually but I still don't have the symbols
![qtCreator2](https://user-images.githubusercontent.com/15138914/55718350-c9464600-59fb-11e9-9dd3-c8d6cc811cc5.png)

![qtCreator3](https://user-images.githubusercontent.com/15138914/55718349-c9464600-59fb-11e9-9b71-010bc61a9c49.png)

![qtCreator4](https://user-images.githubusercontent.com/15138914/55718348-c9464600-59fb-11e9-8372-8ac7c9441b9b.png)

Maybe the compilation flags are not correct , this is the 2 commande to build and compile that I have : 

qmake: ```qmake player_qt5.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug```
Make: ```make -j4 in /home/mohamed0/Gideros/gideros/player```

The build directory is gideros/player/

**Comment by rama0x9** [comment]
Hi, 2 years later and this problem still exists. Everything works except GiderosPlayer.
I tested building on different distros and the only one that works is MX Linux. (e.g Arch, PopOS and Fedora not working ).

I then debug tested with QtCreator and it works when i delete everything after    `MainWindowClass->setCentralWidget(centralWidget);` in ui_mainwindow.h on line 278.

Basically everything related to the menubar.

**Comment by hgy29** [comment]
Yes, I am afraid very few of us use linux, so not much time spent on this side. I don't know about the distros you mentioned, but I can have another go on a Debian.

**Comment by rama0x9** [comment]
I think there a more linux users than u see, but not having a ready to go package of gideros make people boot to windows.
It would really help if you can manage to make a Flatpak of gideros for example.

**Comment by hgy29** [comment]
Hey, this is an old thread but there are some fresh news about Gideros on Linux: we now distribute packages that should run ok on Debian based linux at least. Tested working on latest Debian and Ubuntu.
