### ISSUE TITLE
Build gideros player on linux

### ISSUE THREAD

**Issue by hagna** [gideros/gideros#483]
On Ubuntu 18.04.3 I get this error compiling player:

../luabinding/bufferbinder.cpp:153:2: error: ‘memcpy’ was not declared in this scope
  memcpy(buf,data,count);
  ^~~~~~
../luabinding/bufferbinder.cpp:153:2: note: suggested alternative: ‘wmemcpy’
  memcpy(buf,data,count);
  ^~~~~~
  wmemcpy

This patch fixes it (for me on ubuntu):

```diff --git a/luabinding/bufferbinder.cpp b/luabinding/bufferbinder.cpp
index c9f0418e..64c9c0af 100644
--- a/luabinding/bufferbinder.cpp
+++ b/luabinding/bufferbinder.cpp
@@ -6,6 +6,8 @@
 #include <string>
 #include <errno.h>
 #include "glog.h"
+#include <cstring>
+using namespace std;
 
 #include <pthread.h>
 
```

**Comment by hgy29** [comment]
Thanks for flagging, I will add the missing header
