### ISSUE TITLE
[IDE] Clear and search output

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#49]
I find myself manually looking for "a needle in a haystack" quite a bit when I'm debugging with the output. 

If I could clear it, I would at least know the output were only in the last session. Then I could copy and paste all to an external editor and search for that elusive "nil". If search was included I could do it all in the IDE.

**Comment by ar2rsawseen** [comment]
Implemented Ctrl+Shift+X to clear output
https://github.com/gideros/gideros/commit/444b2a8649e5aea2c7bd218bb864bcdb65516da9

**Comment by ar2rsawseen** [comment]
And search implemented here:
https://github.com/gideros/gideros/commit/f67ddea811c2660d48d069f8262567c4ab00e452

**Comment by totebo** [comment]
Yay! Awesome.
