### ISSUE TITLE
Add plugin to convert image sequence (plus optional audio file?) to ogg video and av1 video

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#492]

**Comment by hgy29** [comment]
It has been added for Ogg video (theora)  in 2024.6 (6af27ed06e5c8ba2dda5c5d1600066765824dae6)

**Comment by mokalux** [comment]
can you close this one keszegh or do you still need av1?

**Comment by keszegh** [comment]
ogg is good enough for now. closed.

**Comment by keszegh** [comment]
closed.
