### ISSUE TITLE
html5 alert dialog error

### ISSUE THREAD

**Issue by mokalux** [gideros/gideros#499]
The alert dialog fails on html5. The first time you open an alert dialog that works fine, but the second time you open it and then close it the app crashes.

*TextureBinder::create* stack NOT ok begin:2 end:4 delta:1
gideros-wasm.js:337
Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node
    button_handler https://v6p9d9t4.ssl.hwcdn.net/html/3076873/gideros-wasm.js:337
[post-exception status] Exception thrown, see JavaScript console gidloader.js:254:19
    printErr https://v6p9d9t4.ssl.hwcdn.net/html/3076873/gidloader.js:254
    setStatus https://v6p9d9t4.ssl.hwcdn.net/html/3076873/gidloader.js:362
    onerror https://v6p9d9t4.ssl.hwcdn.net/html/3076873/gidloader.js:359
gideros-wasm.js:337
Uncaught DOMException: Node.removeChild: The node to be removed is not a child of this node
    button_handler https://v6p9d9t4.ssl.hwcdn.net/html/3076873/gideros-wasm.js:337

Thank you for making gideros awesome :-)

**Comment by hgy29** [comment]
Should have been fixed by b7496b6b9f5ff143737a1d9d974a96bdd8f9815b in 2021.1, can you confirm ?

**Comment by mokalux** [comment]
yes this should be ok, I haven't rebuilt to test yet :-(
I will close it for now 👍
