### ISSUE TITLE
[Feat request] Flatpak version 

### ISSUE THREAD

**Issue by MetalMaxMX** [gideros/gideros#530]
Hi! 
So I'm here experimenting with some Lua game engines out there and I found gideros and I have seen that it was highly recommended on the forums of it. But I couldn't find any binaries or a straightforward way to build the engine on Linux, it seems the last instructions for it were a little outdated (See: https://www.dropbox.com/s/22arh2pxgif3d60/buildGiderosLinux.txt?dl=0) which I am not sure if they are updated with the latest build changes. (Since it said that it was last tested with Ubuntu 14.04...)

If you could point me to instructions on how I could build Gideros, I'd greatly appreciate that. Though admittedly, I'd rather have a flatpak of it as that would make the process a bit more straightforward and would be quite distro-agnostic as well. 

Cheers!
MetalMaxMX.

**Comment by mokalux** [comment]
there is this thread on the forum but gideros is going through a bit of a change. You can give it a try and ask on the forum :-)
https://forum.gideros.rocks/discussion/comment/66653/#Comment_66653

**Comment by hgy29** [comment]
I still couldn’t find how to build a flatpak with qt6 dependency.

**Comment by MetalMaxMX** [comment]
Hey! Thanks for answering you both. It seems that you need to install a Qt6 dependency before you're allowed to build and run this application. However, my distribution (Debian) does not provides base libraries from which to source repos that have Qt6 so I can see why the user mokalux went ahead with changes that make it possible to get it by running the installer from the qt site, though I'm also afraid it could play badly with other dependencies or the like. Still, thanks for the input here. 

As for hgy29's question, well, I'm afraid I wasn't able to get much either but I did find some clues. It seems https://flathub.org/apps/details/io.qt.QtCreator (QtCreator) 7 is already on Flathub, 7 by default uses the newest Qt branch so it's possible that flatpak might've been built with it. There's a few links that give some pointers on how to deploy to Linux in some other formats (like AppImage) https://doc.qt.io/qt-6/linux-deployment.html and a Github project known as linuxdeployqt. And flatpak's docs are here https://docs.flatpak.org/en/latest/qt.html#

If flatpak proves too complex, I'd also appreciate an AppImage or heck even a Snap if necessary. If only so that Linux users could have it running and testing it one way or another.

Cheers!
MetalMaxMX

**Comment by MetalMaxMX** [comment]
Hi! I am updating with some additional links I found, it seems https://invent.kde.org/packaging/flatpak-kde-runtime/-/tree/qt6.3 has proper instructions on how to get Qt6, specially as it is now bundled in more distros than ever before so it's easier to get. 

This branch seems to be useful and helpful when it comes to building an app done with Qt6, so that's a step-forward I believe! This forum post also has instructions on adding Flatpaks, seems to be one-liners on a command line 
https://forum.qt.io/topic/138867/create-a-flatpak-package-for-my-qt-app/2

Cheers once more!
MetalMaxMX

**Comment by mokalux** [comment]
**MetalMaxMX**, the devs are on holidays 😄

**Comment by MetalMaxMX** [comment]
> **MetalMaxMX**, the devs are on holidays smile

Oh, ok! Let 'em enjoy their holidays then. I was just updating since there are more resources to building Flatpaks with Qt6 since it is more common now!

**Comment by hgy29** [comment]
Hi, yes I am still on holidays, but that’s great news. I can’t promise I will make a Linux version of Gideros studio though, because that’s a lot of time to spend to include a third platform in the building process.

**Comment by MetalMaxMX** [comment]
Oh hey! I'd be just happy with at least building steps actually. As the ones from the site redirect to a Dropbox file that's probably outdated by now (http://giderosmobile.com/download) but if that isn't possible then that's also fair. I was just curious about this since the site did indicate that you could build this on your own and perhaps export binaries and all so that's why I raised the issue back then.

**Comment by hgy29** [comment]
Oh, if you just need building steps that’s easier, since it is mostly a matter of fixing current Linux build script if needed and finding prerequisites for the platform. I built it for Debian in my first attempt, I will try to repeat the procedure and document it on the wiki.

**Comment by MetalMaxMX** [comment]
Yes! I happen to run Debian as well. Thanks! If you can also specify the versions of Debian and all that'd be helpful as well. Debian has gotten a new release this year that comes with Qt6 though older versions can also use it through backports and all. 

Once again, thanks!

**Comment by hgy29** [comment]
@MetalMaxMX,

I managed to compile Gideros Studio and Player for Debian. I pushed a few changes to build scripts to achieve that.
Now you can follow the steps here: https://wiki.gideros.rocks/index.php/Compiling_Gideros_Source
- See Section 1.1 (LINUX) part
- Follow sections 1.3.1, 1.12.1 and 1.12.2 (see Linux/Debian part)
- Compile according to 1.12.4 and 2.1.1
- You should get GiderosStudio and GiderosPlayer binaries in Build.Linux folder
- You may need to launch GiderosPlayer or GiderosStudio with LC_ALL="C" environment variable set

**Comment by MetalMaxMX** [comment]
@hgy29 Hi, thanks for answering my queries!

I'd like to ask. According to 2.1.1, I am meant to use make –f scripts/Makefile.gid qtapp.install and not make -f scripts/Makefile.gid? Because I am having issues with the latter in the form of:
mkdir -p ./Build.Linux/Plugins
mkdir -p ./Build.Linux/Templates/Qt/LinuxDesktopTemplate/Plugins
mkdir -p ./Build.Linux/All\ Plugins/lsqlite3/bin/Linux
R=; cd ./plugins/lsqlite3/source; if [ -d "linux" ]; then cd linux; \
	else if [ -d "Desktop" ]; then cd Desktop; fi; fi; \
cp -P *.so* $R/./Build.Linux/Plugins; \
cp -P *.so* $R/./Build.Linux/Templates/Qt/LinuxDesktopTemplate/Plugins; \
cp -P *.so* $R/./Build.Linux/All\ Plugins/lsqlite3/bin/Linux	
cp: target '/./Build.Linux/Plugins' is not a directory
cp: target '/./Build.Linux/Templates/Qt/LinuxDesktopTemplate/Plugins' is not a directory
cp: target '/./Build.Linux/All Plugins/lsqlite3/bin/Linux' is not a directory
make[1]: *** [/home/mega/gideros/scripts//GidQtLinux.mk:74: lsqlite3.qtplugin.install] Error 1
make[1]: Leaving directory '/home/mega/gideros'
make: *** [/home/mega/gideros/scripts//GidQtLinux.mk:159: qtplugins.install] Error 2

I was able to fetch all the repos and built everything needed for the tools so it's weird that this keeps happening. And if I go according to 2.1.1, I get: make: *** No rule to make target '–f'.  Stop.

**Comment by MetalMaxMX** [comment]
Actually, a bit of an update. It seems on the instruction repos you put – instead of - and that is why it wasn't working on the Linux repo, though now I have 
make -f scripts/Makefile.gid qtapp.install 
cd ./libpystring; qmake6 libpystring.pro
Failure to open file: /home/mega/gideros/libpystring/Makefile
Unable to generate makefile for: libpystring.pro
make: *** [/home/mega/gideros/scripts//GidQtLinux.mk:165: libpystring.qmake.rel] Error 5

**Comment by hgy29** [comment]
You are right, there were some – instead of - throughout the document (it was first written as a word doc, and MS word substitutes - with –). That's fixed now. about your last error, it feels like a permission issue, as if you started the build as root but tried to launch it again as a normal user. The only parts the need to be run as root are 'apt install' stuff and 'qscintilla' and 'qlexilla' installation steps. It is easier to build everything as root though.

**Comment by MetalMaxMX** [comment]
It's weird, I ran into that issue precisely during the root step. Hmm, could you give me an example makefile.def you used for the Linux build? I wonder if that has to do with it

**Comment by hgy29** [comment]
Hey wait, I see 'R=;' in your log, where R should have been your current directory ($PWD). Could that be a shell issue ? I am using bash.

**Comment by MetalMaxMX** [comment]
I am using Bash, yes. The default stock bash that comes with Debian 11, no updates or anything there

**Comment by hgy29** [comment]
Hmmm, weird. Can you try to change line 74 of scripts/GidQtLinux.mk so that its reads R=`pwd` instead of R=$(PWD) ?

**Comment by hgy29** [comment]
I meant pwd surrounded by back quotes, seems like github processes them

**Comment by MetalMaxMX** [comment]
Hi! Sorry it's taking me a bit long here to reply since I simulated all the steps once again and got to the same issue. I applied your back quote fix and now it seems to be compiling smoothly. It's taking awhile to build but I think that change fixed it, could probably add that to the script on the main repo

**Comment by MetalMaxMX** [comment]
All right it built! Yeah, it was that issue with pwd

**Comment by MetalMaxMX** [comment]
Ok so I'll list here some of the things that could be improved with Gideros documentation:

A) There's a lot of dropbox links at http://giderosmobile.com/download scattered around, even for hardware configurations like RPi 2/3 that no longer work, suggest replacing them all with the compiling wiki.
B) State to the user that sudo is necessary for some steps or otherwise the engine won't work properly, at least make a note of the relevant steps needed for that. 
C) How does one exports projects from Linux? There is no option to export a Linux binary anywhere as it seems templates are required for just about anything.

**Comment by hgy29** [comment]
for the C point, you'll need to grab the Templates from Mac or Win32 installer, and there is no official Linux export, although the Qt (desktop) based one is correctly built. It isn't referenced in the studio, and QT has licensing issues. I non QT Linux export would be great, and I'll probably need one soon.

**Comment by MetalMaxMX** [comment]
All right, for now I am just happy that it built at all. I'll happily wait for a way to export Linux binaries from the IDE itself (Also, if possible. Would like a note or some steps on how to get the templates from the installers. I am assuming you have to open the executables as if they were a zip file or something?)

**Comment by hgy29** [comment]
I have just updated a bit Linux support in Gideros, now QT-Based Linux export is supported and almost working (it doesn't work with encryption yet). Aboute templates, currently you would need to install either windows or mac app and copy the Template and "All plugins" folders from there to Linux. For next release, I'll put a zip of the Templates and Plugins on Github too

**Comment by keszegh** [comment]
does this mean that we can export to linux from windows too? that would be amazingly useful as running apps using wine has issues.

**Comment by hgy29** [comment]
In theory, if you had the Linux export template (which won’t be automatically built soon because I would need to have a dedicated Linux machine to do this), you could export a linux project. But I am not sure windows will handle symlinks correctly, and I am not sure the bi Aries will be portable

**Comment by MetalMaxMX** [comment]
Oh, awesome that we have a Linux export now! I didn't understand what was the difference between a Qt export and a non-Qt export from the wording of your previous post but still cool that we can generate Linux binaries now! As for the templates, I see. But with those templates, you could have a working Linux setup that could cross-build to Windows and macOS from one OS? That's even better admittedly. 

Will be waiting for news on what this non-Qt export is supposed to be + Template binaries on Github!

**Comment by mokalux** [comment]
If you build your game using Qt you are bound to the Qt license which is here https://www.qt.io/download-open-source
and it sucks because you have to share your code:
GPL
Basic Premises of the Qt Open Source Model

GPL – All users have the rights to obtain, modify and redistribute the full source code of your application. Your users are granted rights founded on[ the four freedoms of the GNU General Public License](https://www.gnu.org/licenses/quick-guide-gplv3.html).
...

**Comment by MetalMaxMX** [comment]
@mokalux Pretty sure that one had an LGPL or BSD kind of licensing scheme? Still, even if it was GPL, it wouldn't be a problem if you were to build an open-source project to begin with. Though I suppose commercial releases or the like on Steam might be more problematic I can see

**Comment by hgy29** [comment]
I plan to work on a QT free Linux export, based on GLFW. Current HTML export is based on Linux coding style and APIs, so a lot of the work is already done.

**Comment by MetalMaxMX** [comment]
> I plan to work on a QT free Linux export, based on GLFW. Current HTML export is based on Linux coding style and APIs, so a lot of the work is already done.

Oh, awesome! Sounds good, and I imagine that export, once done, is going to be the default for Linux builds? (with Qt either disabled or hidden?)

**Comment by MetalMaxMX** [comment]
Oh, nice! Just wondering. But all the platforms are Qt-free exports, right?

**Comment by mokalux** [comment]
@MetalMaxMX yes all platforms are Qt free export **except for Windows**. To have a Windows free of Qt you have to export to win32 (64bits).

**Comment by mokalux** [comment]
I am not the dev and my Linux knowledge is very limited 😞 so I believe templates will net you anything possible from a Linux. I am on windows 10 and cannot export to Mac for example. I don't know if you can export to Mac and Windows using a Linux OS!?

**Comment by MetalMaxMX** [comment]
I mean, according to @hgy29. It should be possible if all the templates are in their respective folders. As for macOS, well, that sounds like a bug really. Could probably raise one (or wait until templates are up so you can try them, including the Linux one. I do think macOS is a bit more finicky due to it requiring authentication and stuff though anyway)

**Comment by mokalux** [comment]
no you cannot build for mac on a windows machine.
You can "rent" a mac on the cloud and build your project though, see: https://forum.gideros.rocks/discussion/comment/67074/#Comment_67074

**Comment by MetalMaxMX** [comment]
I'll be honest in saying that I am more interested in being able to export Windows builds from a Linux box than macOS builds really. Would also be cool for Windows users of course if they were able to build Linux exports as well since both can benefit from this but my usage is about primarily Linux to Win here, which I think Gideros can do with templates. 

I can see that cloud thing being beneficial if one wants to build macOS binaries too though.

**Comment by hgy29** [comment]
I've just released Gideros 2023.8 which, I believe, will answer your question.
