### ISSUE TITLE
Sprite:setScale(0) and input Events

### ISSUE THREAD

**Issue by piretro** [gideros/gideros#54]
on 2014.10
Sprites with scale 0 doesn't respond to touch events

on 2015.04.18
Sprites with scale 0 respond to touch events 

more info and example project here:
http://giderosmobile.com/forum/discussion/5661/any-difference-in-sprite-class-between-gideros-2014-10-and-2015-04-18

**Comment by hgy29** [comment]
Fix submitted in PR #75

**Comment by ar2rsawseen** [comment]
PR merged
