### ISSUE TITLE
being able to install more versions of the android player at the same time

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#55]
different versions of compiled playershould have different name so that they can be installed parallelly, now it's very hard to test (by repeatedly installin/uninstalling players) if there is a bug then which is the first version it appears on.

**Comment by ar2rsawseen** [comment]
Unfortunately I think that's not really possible due to android limitations, because player would need to have different packages to be able to install multiple players

**Comment by keszegh** [comment]
refactoring/changing the package name in eclipse for each new version to include the version number would be too much hassle then, i guess. (as this should work, at least).

**Comment by ar2rsawseen** [comment]
it would really be, there are already too many manual steps to do for each build

**Comment by keszegh** [comment]
i accept that. hopefully the mesh bug/slowdown will be corrected soon and then it's less important to be able to use several android players parallelly.

**Comment by SinisterSoft** [comment]
keszegh: You can always make your own player on android and keep it a different id (the com.xxx.xx bit).   It isn't difficult, just make a new project, export it to eclipse, in the manifest change the com.xxx.xxx bit at the top then delete the assets folder and build.   If you use a different id for each player then it will do what you want.
