### ISSUE TITLE
Last version with Qt5?

### ISSUE THREAD

**Issue by iahung** [gideros/gideros#555]
I'm on Windows 8.1, and the fact that Qt6 doesn't support my OS is well known to me. When I found Qt6 in Gideros's installation directory, I was already afraid that it would not run on my computer. But I didn't give up hope yet. Because I'm completely new to Gideros, I think it could be that Qt6 is used for an optional backend. It turned out that I was wrong. The Gideros Studio seems to be written in Qt, and it was built with Qt 6. When I tried to run, I met the same error message as https://github.com/gideros/gideros/issues/538.

**Comment by mokalux** [comment]
Yep, sorry but Gideros 2022.1 and above: [studio/desktop] Switch to QT6 and 64 bit.
Latest version that uses **Qt5** is Gideros **2021.11**
https://wiki.gideros.rocks/index.php/Latest_Release
