### ISSUE TITLE
There is no uninstaller registered to Windows

### ISSUE THREAD

**Issue by iahung** [gideros/gideros#556]
On Windows' Programs and Features I don't see any entries for Gideros. I then go to Gideros' installation directory and luckily there is an uninstaller.

p/s: I'm running Windows 8.1. Even though Gideros Studio is Qt 6 and thus not working on my system, the installer is a normal NSIS based installer and I think it should correctly register the uninstaller to Windows.

**Comment by mokalux** [comment]
yes the uninstaller is in Gideros Studio folder.
