### ISSUE TITLE
No download available

### ISSUE THREAD

**Issue by keyara** [gideros/gideros#557]
I've tried on several different browsers to download Gideros. The link to download the latest release and the ms windows link have not been downloading the exe.

**Comment by hgy29** [comment]
Had a try just now, and links seems to work here. They all end up to GitHub release page, and download is ok here.

**Comment by mokalux** [comment]
**Downloading Gideros works for me**, I don't see any problem here (I am using Firefox, windows 10 64bit))

**Comment by mokalux** [comment]
I believe the issue has been solved as the OP was able to download Gideros from GH?
Shall we close the issue?
