### ISSUE TITLE
Issues running on macOS and no verification email from forum

### ISSUE THREAD

**Issue by gingerbeardman** [gideros/gideros#559]
Also posted at: https://forum.giderosmobile.com/discussion/8692/issues-running-on-macos-and-no-verification-email-from-forum/p1

I'm posting here are all other avenues have not yielded a response or a solution.

I've been trying to use Gideros on macOS Monterey and also sign up to the forum for support. Here are the issues I have encountered.

## Gideros Attempt 1

- I’m trying to run this but the fact the Studio app is not signed means it does not run or accept network connections on recent macOS.

## Forum Attempt 1

- I can’t sign up for the forum because I can’t run the “captcha” code snippet. A sort of chicken and egg scenario.

## Gideros Attempt 2

- I managed to ad-hoc sign the binaries and got them running and accepting network requests. So I could enter the code snippet and sign-up to the forum.
- I have to start the Player manually as the toolbar button does not work in this scenario.

## Forum Attempt 2

- But, new problem, my forum confirmation email has not arrived! 
- After a week my forum account seems to no longer be nagging me to verify.

---- 

How to self-sign an app using an Ad-hoc signature. I think you'll need Xcode Tools installed to do this.

```
codesign --force --deep -s - MyApp.app
```

---- 

To date I have received no emails from Gideros.

Many would have given up by now, but let’s see this through.

I think these issues might indicate that you are turning away many users.

- macOS 12.6.7
- Gideros 2023.6 & 2023.7
- Safari 16.5.2

**Comment by mokalux** [comment]
this issue has been adressed on the forum https://forum.gideros.rocks/discussion/comment/68296/#Comment_68296 let's see how it turns out.
