### ISSUE TITLE
 macro "lua_pushcfunction" passed 3 arguments, but takes just 2 

### ISSUE THREAD

**Issue by gamobink** [gideros/gideros#565]
../luabinding/gmathbinder.cpp:721:51: error: macro "lua_pushcfunction" passed 3 arguments, but takes just 2
  721 |         lua_pushcfunction(L, lua_vector_dot, "Dot");

compiling ../luabinding/gmathbinder.cpp
../luabinding/gmathbinder.cpp:721:51: error: macro "lua_pushcfunction" passed 3 arguments, but takes just 2
  721 |         lua_pushcfunction(L, lua_vector_dot, "Dot");
      |                                                   ^
In file included from ../lua/src/lua.hpp:6,
                 from ../luabinding/gmathbinder.cpp:1:
../lua/src/lua.h:265: note: macro "lua_pushcfunction" defined here
  265 | #define lua_pushcfunction(L,f)  lua_pushcclosure(L, (f), 0)
      |
../luabinding/gmathbinder.cpp:761:46: error: macro "lua_pushcfunction" passed 3 arguments, but takes just 2
  761 |     lua_pushcfunction(L, lua_vector, "vector");
      |                                              ^
../lua/src/lua.h:265: note: macro "lua_pushcfunction" defined here
  265 | #define lua_pushcfunction(L,f)  lua_pushcclosure(L, (f), 0)
      |
../luabinding/gmathbinder.cpp:772:59: error: macro "lua_pushcfunction" passed 3 arguments, but takes just 2
  772 |     lua_pushcfunction(L, lua_vector_index, "vector__index");
      |                                                           ^
../lua/src/lua.h:265: note: macro "lua_pushcfunction" defined here
  265 | #define lua_pushcfunction(L,f)  lua_pushcclosure(L, (f), 0)
      |
../luabinding/gmathbinder.cpp:776:65: error: macro "lua_pushcfunction" passed 3 arguments, but takes just 2
  776 |     lua_pushcfunction(L, lua_vector_namecall, "vector__namecall");
      |                                                                 ^
../lua/src/lua.h:265: note: macro "lua_pushcfunction" defined here
  265 | #define lua_pushcfunction(L,f)  lua_pushcclosure(L, (f), 0)

**Comment by gamobink** [comment]
use luau is ok.

**Comment by mokalux** [comment]
are you building Gideros from Github source code?

**Comment by gamobink** [comment]
It's my fault,building Gideros from Github source code is ok.
