### ISSUE TITLE
huge slowdown on android player (probably when using meshes)

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#57]
huge slowdown on android player when using meshes.
it was still fine in a v2015.03.* version.

**Comment by john-blackburn** [comment]
Probably due to the recent transition to OpenGL ES 2.0....

John

**Comment by ar2rsawseen** [comment]
I know you hate this question, but is there a difference for you when using this release?
https://github.com/gideros/gideros/releases/tag/2015.04.12

Want to check if it is related to high precision change in shaders, if it is still slow, then it is related to 3D and/or OpenGL ES 2 changes

**Comment by keszegh** [comment]
the legacy open gl es1 engine/abstraction layer should be possible to force from within the app by some setting at least until bugs related to open gl es2 like this slowdown exist.

**Comment by hgy29** [comment]
PR #75 should provide significant improvement if slowdown was due to larger matrix computations, specially on pre-armv7 CPUs

**Comment by ar2rsawseen** [comment]
PR merged
