### ISSUE TITLE
Different export paths for different platforms

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#60]
Having to remember to change the path manually on export makes it too easy for an iOS or Android export to overwrite the other.  This will get worse as more platforms are added.

It would be great if each platform had it's own export path.

This could even mean that if the user created a shared folder with virtualbox then they could export iOS to that, then in the virtualbox have OSX running and sign the code!

**Comment by ar2rsawseen** [comment]
Added in https://github.com/gideros/gideros/commit/1872353511fadfa555d3b033621790f5fa2702c8
