### ISSUE TITLE
Project WindowWidth/Height set incorrectly for landscape projects

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#61]
Window width/height are set to 320x480 by default, this should be 480x320 for landscape project.

Possibly better would be if left at 0,0 then the player could get it's windowWidth/Height from contentWidth/Height ?   

That would mean existing projects look ok if either orientation.

Currently on landscape it messes up if autoscale is on unless you are aware of it and correct the setting.

**Comment by ar2rsawseen** [comment]
Implemented in https://github.com/gideros/gideros/commit/601575a706ae6b00a6eb71d76633eaf1f8bbd544
