### ISSUE TITLE
Exporting to Windows exports data even if template not found

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#62]
If no template folder isn't found then maybe a message should appear saying 'template not found' rather than an export of the whole contents of the  templates folder occuring?

This would let people know they haven't installed that export platform properly?

**Comment by ar2rsawseen** [comment]
Added in https://github.com/gideros/gideros/commit/4c9913f31476cbd6c7b2d2b3ad696d75b99050db
