### ISSUE TITLE
Implement x,y properties likes setPosition

### ISSUE THREAD

**Issue by takaaptech** [gideros/gideros#64]
Can we implement Sprite x and y properties likes other LUA engines (Love, Corona) so we can change position by assign them:

player.x , player.y = 100,100 
is as same as:
player:setPosition(100,100)

and local x,y = player.x , player.y
is as same as:
player:getPosition()

This will make we convert source code from other LUA engines to Gideros more convenience!

**Comment by ar2rsawseen** [comment]
Not that it is not possible, but most probably this kind of modification provides a huge performance penalty, at least for plain Lua when using meta methods.

would need to test more to understand the consequences

**Comment by SinisterSoft** [comment]
takaaptech:  You could write a converter.  Something that took the source from Corona and made a Gideros version.

**Comment by hgy29** [comment]
This is an old topic, but I think implementing what the OP want will break many existing gideros projects, which should be avoided. Better write a lua side converter (thanks to metamethods) IMHO.
