### ISSUE TITLE
Print sometimes crashes in debug

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#65]
If you have pass something in print, sometimes it crashes.

See:  http://giderosmobile.com/forum/discussion/5646/luajit-patch#Item_17

It seems much worse in LuaJIT, but a test with Atilim a while back showed character corruption.

**Comment by SinisterSoft** [comment]
I have a gut feeling that somehow this is stack related.

**Comment by ar2rsawseen** [comment]
does it happen on player or exported apps and on which platforms? Because on exported apps, print is platform dependent and usually outputs to console, or something like that I think :)

**Comment by SinisterSoft** [comment]
It was a player - android.

**Comment by hgy29** [comment]
There is a bug in printToServer implementation that may cause memory corruption under luajit.
If supplied str parameter to printToServer is not null terminated, which is a valid case if size is supplied, then strcpy may copy more bytes than it should.
LuaJIT seems to pass size and not null terminate strings in a lot of cases whereas interpreted lua always null terminate its strings and pass -1 as size.

**Comment by ar2rsawseen** [comment]
@hgy29 it seems for you C is a high level language like for us lua :D

**Comment by SinisterSoft** [comment]
@hgy29 / @ar2rsawseen Ahh - so is it being fixed to check for -1 as size and if not then using size as size?

**Comment by hgy29** [comment]
Fix submitted in PR #70

**Comment by SinisterSoft** [comment]
Thanks. :)

**Comment by ar2rsawseen** [comment]
PR Merged
