### ISSUE TITLE
Need Application:fitToWindow() [Enhancement]

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#66]
Due to the weird nature of Application:setFullScreen() and Application:setWindowSize(w, h)
Application:fitToWindow() is a need, or second choice probably that the application automatically fit to window on window resize and setFullScreen.
(Also probably need Application:isFullScreen(), because player might do full screen with Alt+Enter, if the shortcut still attached)

**Comment by ar2rsawseen** [comment]
Can you clarify the weird nature of Application:setFullScreen() and Application:setWindowSize(w, h)?

**Comment by tkhnoman** [comment]
After Application:setFullScreen( true ) and Application:setWindowSize(w, h), Application:getDeviceHeight() and the rest return the same.
The things that changed is only frame size container of the player, while the resolution is still the same.

**Comment by ar2rsawseen** [comment]
Ok, I see, then it is a bug increasing only window size and not canvas size

**Comment by ar2rsawseen** [comment]
I just talked with @marceloLiberton and you need to enable autoscale on player to use fullscreen properly. Can you try it that way?

**Comment by tkhnoman** [comment]
Oh yes it works, but now one question arise, the exported project's window won't be scalable right?
Somehow when scaling manually, many object that offscreen would become visible.

**Comment by ar2rsawseen** [comment]
We are trying to figure out right configurations ourself now :)
For now the decision is that desktop exported project will have autoscale enabled by default.
But that again raises the issues you specified

**Comment by ar2rsawseen** [comment]
Fixed toggle autoscale on Application:setFullscreen toggle
https://github.com/gideros/gideros/commit/8c3c7e338527df0854dbfd3d116bb2428f15dd8a
