### ISSUE TITLE
Player settings window redundant

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#67]
The dropdown to select the player works so well that the player settings window is almost redundant.

If 'localhost (127.0.0.1)' was added to the dropdown (just in case there is no network - so no lan ip address)  then there would be no need to the window anymore.

**Comment by SinisterSoft** [comment]
I'm not sure what the purpose of the 'Player settings' windows is any more in the Player menu.   It seems to work the same no matter what is in there.  I'm guessing it's redundant.

**Comment by hgy29** [comment]
in fact it is still useful when network configuration doesn't allow auto detection to work properly

**Comment by mokalux** [comment]
indeed auto detection didn't work for me so I had to use the player settings.

You may want to close this one?

**Comment by hgy29** [comment]
Yes, there are variious reasons why the studio wouldn't detect a possible player, for example due to firewalls
