### ISSUE TITLE
Windows Player resize himself

### ISSUE THREAD

**Issue by JeromeGsq** [gideros/gideros#72]
In the last build, when i use the Windows player and run CTRL+R, the window of the player resize himself and after that, when i rerun, move the content of the window to the bottom of the screen (see this link)

But, if i set a resolution of 640*960 to the player and set the editor window to left of my screen and run CTRL+R, the player will be placed at the right of the editor.

![1430380531-sans-titre-5](https://cloud.githubusercontent.com/assets/6270529/7411556/73bf8baa-ef39-11e4-8c22-7421c137d943.jpg)

**Comment by ar2rsawseen** [comment]
Can you please recheck if it is still happening in 2015.06.04

**Comment by JeromeGsq** [comment]
I will try this Monday, because here I don't have a good internet
connection.

Does the windows export is currently supporting for everyone ?

Thank you for your help and good work !


2015-06-06 10:47 GMT+02:00 Arturs Sosins <notifications@github.com>:

> Can you please recheck if it is still happening in 2015.06.04
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gideros/gideros/issues/72#issuecomment-109553456>.
>



-- 
Jérôme Ghesquière
Étudiant, Univ. Lille 1, IUT A
fr.viadeo.com/fr/profile/jerome.ghesquiere3

**Comment by JeromeGsq** [comment]
No, i have another issue. 
I will provide you a video.

**Comment by ar2rsawseen** [comment]
So what you don't like is that restarting project in player resest window dimensions, right?

**Comment by JeromeGsq** [comment]
Yes i think this is not a good idea. The 2015.04.18 version is the best according to me.

Maybe do you think it is possible to integrate inside the IDE this window ?
Like this : 
![sans titre 4](https://cloud.githubusercontent.com/assets/6270529/8030793/febff2fe-0dc9-11e5-9d00-29a86a5b2fdd.png)

**Comment by ar2rsawseen** [comment]
It should be easy to fix to keep window dimensions, but implementing player in widget, would not be so easy

**Comment by JeromeGsq** [comment]
Ok no problem, this is because when I have only one screen, this is very boring to make the two windows showing together like this 
![window](https://cloud.githubusercontent.com/assets/6270529/8053045/3ae6906c-0e8d-11e5-95d8-0569958a334d.png)

**Comment by ar2rsawseen** [comment]
Tested, current player does not reset window dimensions
if you will have problems after next release, please reopen issue ;)
