### ISSUE TITLE
application:exit() on Windows Exported Project

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#76]
application:exit() gave not responding on Windows Exported project.

Also, on application closed, can it run Event.APPLICATION_EXIT?

(another reminder, |D| did not access directory folder but temporary folder)

**Comment by john-blackburn** [comment]
Are you referring to Windows desktop export or Windows store?

John

-----Original Message-----

**Comment by tkhnoman** [comment]
Windows Desktop

**Comment by ar2rsawseen** [comment]
Fixed here:
https://github.com/gideros/gideros/commit/7d7363eedfe564bf7e7e6e877ec61039b7855708
