### ISSUE TITLE
Box2D slowdown

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#78]
Box2D performance has decreased significantly.

A simple Box2D scene with a few bodies give the following results:

2014.01:

iPad 2: 60fps
iPod (5th gen): 60fps
iPad (mini retina): 60fps

2015.05.09

iPad 2: 29fps
iPod (5th gen): 50-60fps
iPad (mini retina): 55-60fps

**Comment by totebo** [comment]
This is appears to be an with Shapes rather than Box2D.

**Comment by ar2rsawseen** [comment]
New release contains speed improvements, can you please recheck with Gideros 2015.06.04

**Comment by totebo** [comment]
Yes! This now seem to be resolved, and may even be faster than before.
