### ISSUE TITLE
No need to clear screen on some apps

### ISSUE THREAD

**Issue by SinisterSoft** [gideros/gideros#80]
There should be an option not to clear the screen between frames.  That way no time is wasted if you are drawing a tilemap to the screen or filling it with a bitmap (in that case you are clearing the screen for nothing).

maybe an application: setting to bypass the clear?

**Comment by hgy29** [comment]
So this option already exists, right ? This issue can be closed :)

**Comment by ar2rsawseen** [comment]
There is an api, but there is a problem mentioned in https://github.com/gideros/gideros/issues/88
