### ISSUE TITLE
application:setWindowSize() on Windows Desktop

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#86]
Whenever i did application:setWindowSize(width, height), it goes back to the resolution that chosen at the player. Only the window size changed, not the canvas size.
Turning on Auto Scale didn't fix this.
Also, currently i can't set window lower than the chosen one at Player, but it is expected since auto scale didn't work.

**Comment by ar2rsawseen** [comment]
if it is on player, then I think it is an expected behavior, player resolution is set like hardware resolution. As in you can's change size on device for example. Same goes for player orientation

But exported project should behave correctly, can you confirm?

**Comment by tkhnoman** [comment]
Haven't retrieve the new Template yet, but the old one doesn't behave correctly here.

**Comment by ar2rsawseen** [comment]
New template was sent to backers like 2 days ago, can you please try it? :)

**Comment by tkhnoman** [comment]
Checked and haven't get it yet, backer name is Andre Khrisna.

**Comment by tkhnoman** [comment]
Re-checked another mail, and it's there.. lol
Will try it now

**Comment by tkhnoman** [comment]
What i found on mail is May 3 version, last month... (it seems i read the date wrong)
So it seems that backer under name Andre Khrisna haven't retrieve it yet

**Comment by tkhnoman** [comment]
Received the template. Exported project works fine.
