### ISSUE TITLE
GiderosiOSPlayer (compiled as 32bit or 64bit) no errors but black screen output only? 

### ISSUE THREAD

**Issue by FuzzyDweeb** [gideros/gideros#9]
GiderosiOSPlayer (compiled as 32bit or 64bit) no errors but black screen output only? 
![screen shot 2015-03-01 at 10 27 43 am](https://cloud.githubusercontent.com/assets/9529552/6430345/e30c1a98-bffd-11e4-9047-9820f43e17f8.png)

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/gideros/gideros/commit/06d391ca0b90c6cf5893c2042bd4721046d9e103
