### ISSUE TITLE
[IDE] Detach Output panel from main IDE

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#90]
I work on multiple monitors most of the time. Having the output on a separate monitor from the code would allow a better code overview.

**Comment by ar2rsawseen** [comment]
Output pane is now detachable, it is modeless, but it is still part of the Studio Window, thats the best we can do :)
https://github.com/gideros/gideros/commit/82144045deb236d91ae4632bc275d1ccbfb804fc

**Comment by totebo** [comment]
Awesome!
