### ISSUE TITLE
[IDE] Making the "Error Dialog" window optional

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#93]
I end up hiding the "Error Dialog" window that pops up outside view, because it stops my workflow. It would help if it was removed entirely (is it needed?) or at least if it was optional.

Another option is to split the "Output" window into two; one showing only errors and one showing all other output.

**Comment by ar2rsawseen** [comment]
The easiest way would be to show dialog only in exported app and do not show it in player.
Is there anyone that disagrees?

**Comment by totebo** [comment]
Perfect.

**Comment by ar2rsawseen** [comment]
Done https://github.com/gideros/gideros/commit/711d1ba699950ef3524b2ac99d70b2f7534ece7b
