### ISSUE TITLE
io.open on Desktop Export

### ISSUE THREAD

**Issue by tkhnoman** [gideros/gideros#94]
this command gave me error on Desktop Export 

	local file,errorget = io.open( "|D|file.ini", "w" )
	error(errorget)

**Comment by ar2rsawseen** [comment]
Thanks, will check when I get back :)

**Comment by hgy29** [comment]
Just checked on Windows desktop export: works fine on my PC.
What error do you get ?

**Comment by tkhnoman** [comment]
D:/Sent/Empty/mfly/assets/resource/main.lua:277: |D|setto.deta: Invalid argument

local file,errorget = io.open( "|D|setto.deta", "w" )
error(errorget)

Windows 7 Professional 32 bit SP1
I'm not sure why though. 
Also previous export works fine

**Comment by hgy29** [comment]
Just an idea: what did you set as 'Organization' in export dialog ?
It will be used to construct the path where to store documents under windows (User/xxx/AppData/Roaming/<Organization>/<ProjectName>), so it must not contain characters that are not allowed in file names

**Comment by tkhnoman** [comment]
Hmm...
Only when i set 'Organization' to empty, it run OK.
And the folder is here:
S:\Users\tkhnoman\AppData\Roaming\GiderosMobile\Desktop

When i set it as my organization name 'ElagoTech', it gave me error, but the folder was created.

Should i input something to the domain?

**Comment by ar2rsawseen** [comment]
Interesting, I though the problem was in unicode chars used in company name and I think I fixed that in this new release.

So it seems something else is at fault.

When no value provided than it uses default value GiderosMobile.

How about trying to start an app as administrator?

**Comment by tkhnoman** [comment]
Tried it, and it still gave me the same error.

But amazingly, it run when i checked the Compatibility mode at exe's properties.

**Comment by ar2rsawseen** [comment]
Compatability mode to what? Windows 8?
Hmm then maybe this path is OS version specific

**Comment by tkhnoman** [comment]
Nope, i just checked it and let it at Windows 7. It runs.
Tried to change to Vista and XP, and it still run, but when turned off, it gave error.

**Comment by ar2rsawseen** [comment]
But you already have windows 7, don't you?
That does not make sense :)

Maybe you have some kind of special Windows 7 version?

**Comment by tkhnoman** [comment]
Nope, standard one that i bought from a store.
I'm also totally not sure why. lol.

Tried it on my Windows 8 on laptop and it run OK. This is confusing...

**Comment by john-blackburn** [comment]
I believe the Documents directory is stored in %appdata%. Could you open a
command prompt on the PC where it is not working and type

echo %appdata%

and let us know the value? There are some directories where you cannot
alter files.

**Comment by tkhnoman** [comment]
S:\Users\tkhnoman\AppData\Roaming

**Comment by tkhnoman** [comment]
I tried using lfs, and it works OK :
lfs.mkdir("S:\\Users\\tkhnoman\\AppData\\Roaming\\ElagoTech\\mfly\\test")

The problem probably with that |D|.

I also tried to read an image that i copied to document folder.
It have the same reaction with io.open bug, which gave error that file not found, but if i activated "Compatibility mode", it runs.

**Comment by tkhnoman** [comment]
Found the problem.
It seems that project name must be 8 string in length, so my project, which is just "mfly" throw an error.

I will leave the issue open, since it probably still considered bug
If it somehow got fixed, you might close the issue.

**Comment by hgy29** [comment]
This is weird! I will try with that project name and see what happens.

**Comment by hgy29** [comment]
Just tried, it work fine for me with 'ElagoTech' and 'mfly'. I don't believe it can be a string length issue (except if it leaded to a path longer than 1023 chars).

**Comment by ar2rsawseen** [comment]
hmm, maybe it simply "stuck" on your path for some reason, but works with every other?
How about if you remove your ElagoTech directory in appdata and try again?

**Comment by tkhnoman** [comment]
Tried to delete the directory, it still give error
Also, it seems that total length of organization and project name that affected it, not just project name.

Not sure why too, because it works on my Windows 8.
Probably something to do with my Windows, or some other weird thing.
But at least i can assume it goes fine on any other PC like mine.

**Comment by ar2rsawseen** [comment]
So if you try something with same length but different company and project name it still does not work?

**Comment by tkhnoman** [comment]
Yes, it would run well only when the total length is long enough

**Comment by ar2rsawseen** [comment]
What I meant is, are you sure the length is the problem, as in, did you try different name with same length for org and project name on your machine? :)

**Comment by tkhnoman** [comment]
Yes i tried so many times, with different org name and project name. It succeed when it reach certain length.
But i'm not sure what is the real problem(with my PC) because it is indeed weird if that is the case.
Also the fact that when compatibility clicked, it works (without that length rule) made it more weirder. Lol.

**Comment by tkhnoman** [comment]
I'm able to reproduce this bug on my other Windows 7 (with one char org and project name), but it behave differently.
It does not error, but the data somehow stored at %temp%

**Comment by ar2rsawseen** [comment]
That is probably a correct fallback :)

The only info about windows paths I could find, was the max character limit which is 255.

But thats probably not related to you

**Comment by tkhnoman** [comment]
Why is it a correct fallback?
I'm using |D|, and when i'm using one character org and project name, the data not stored on %appData% but the data is stored on %temp%, and not in any subfolder.
The savedata also would got weeped on clean temporary, so it is a bug, right?

If i'm using enough length, it goes to %appData%.

I will try look into the sourcecode too

**Comment by tkhnoman** [comment]
After taking a look at the source code, i feel that there is high possibility that the bug is at Qt and not Gideros.
I will try to download the new version, mine is too old, it still can't get QStandardPaths::AppDataLocation, but when i use QStandardPaths::DataLocation (at Local, not Roaming) everything works perfectly.

I'm still downloading the new Qt version at 10Kb/s.. lol..
You can see at another things, i will try to check on this issue myself.

**Comment by ar2rsawseen** [comment]
:d 
yes I already changed it internally from roaming to local data, so you could try with next release if it behaves better 
https://github.com/gideros/gideros/commit/5e335de0c391c9b0a68f92c3961c5bc923ebf0d1

**Comment by tkhnoman** [comment]
Dang, after changing data.bin rapidly and check run, it seems that a certain length still gave error, even at QStandardPaths::DataLocation... It's not too long, but not too short, just in the middle, at certain length... So weird.

The stupid thing is that i uninstalled my old Qt already...
 OTL
After i finished downloading Qt, which is very slow because of Qt's server, i will recheck on it again.

**Comment by tkhnoman** [comment]
Phew... this is the correct fix:
(setDocumentDirectory need to be under it, because when temporaryDirectory got a value, documentsDirectory somehow become broken, in some PC, it overwritten with temp value)

Probably variable documentsDirectory isn't even needed...
Please close this issue after you did the fix. Thanks.



if(exportedApp_){
            resourceDirectory_ = directory.absoluteFilePath("resource").toStdString().c_str();
            QString = docLocation = QStandardPaths::writableLocation(QStandardPaths::AppLocalDataLocation);
            QString = tempLocation = QStandardPaths::writableLocation(QStandardPaths::TempLocation);
            directory.mkpath(docLocation);
            directory.mkpath(tempLocation);
            documentsDirectory = docLocation.toStdString().c_str();
            setDocumentsDirectory(documentsDirectory);
            temporaryDirectory = tempLocation.toStdString().c_str();
            setTemporaryDirectory(temporaryDirectory);
        }else{
            dir_ = QDir::temp();
            dir_.mkdir("gideros");
            dir_.cd("gideros");
            dir_.mkdir(projectName_);
            dir_.cd(projectName_);
            dir_.mkdir("documents");
            dir_.mkdir("temporary");

            resourceDirectory_ = dir_.absoluteFilePath("resource").toStdString().c_str();
            documentsDirectory = dir_.absoluteFilePath("documents").toStdString().c_str();
            setDocumentsDirectory(documentsDirectory);
            temporaryDirectory = dir_.absoluteFilePath("temporary").toStdString().c_str();
            setTemporaryDirectory(temporaryDirectory);
        }

        setResourceDirectory(resourceDirectory_.c_str());

**Comment by ar2rsawseen** [comment]
Really?
interesting
and in the end it should be AppLocalDataLocation, not roaming data location using AppDataLocation, right?

**Comment by tkhnoman** [comment]
Oh, i'm sorry.. I copied that from the last code here (since mine are totally mess up for testing)

It is alright to use AppDataLocation, in my test i'm using AppDataLocation.

    resourceDirectory_ = directory.absoluteFilePath("resource").toStdString().c_str();
            directory.mkpath(QStandardPaths::writableLocation(QStandardPaths::AppDataLocation));
            directory.mkpath(QStandardPaths::writableLocation(QStandardPaths::TempLocation));


            documentsDirectory = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation).toStdString().c_str();
            setDocumentsDirectory(documentsDirectory);

            temporaryDirectory = QStandardPaths::writableLocation(QStandardPaths::TempLocation).toStdString().c_str();
               setTemporaryDirectory(temporaryDirectory);

**Comment by ar2rsawseen** [comment]
So fixed in https://github.com/gideros/gideros/commit/d4d94d139c1665af3afc62c0f16ea9c6b2b1ceda
Let's see how it will behave in next release ;)
