### ISSUE TITLE
Upgrade to Lua 5.3

### ISSUE THREAD

**Issue by totebo** [gideros/gideros#95]
One improvement would be support for 64 bit integers for leaderboards, which are supported by iOS and Android.

Forum link: http://giderosmobile.com/forum/discussion/comment/42195#Comment_42195

**Comment by SinisterSoft** [comment]
I think the latest LuaJIT would also do that, plus have the advantage of being universal bytecode (Lua 5.3 doesn't have universal bytecode).

**Comment by totebo** [comment]
If LuaJIT supports 64 bit integers I'm all for it.

**Comment by SinisterSoft** [comment]
It should work for the tests you wanted on that link (18 digits+, etc).

**Comment by john-blackburn** [comment]
Yes, we plan to move to LuaJIT quite soon. But LuaJIT is only Lua 5.1 I think so we are stuck with that! Are there any Lua 5.3 features you need apart from 64 bit? http://www.lua.org/manual/5.3/readme.html#changes

**Comment by totebo** [comment]
For me the main reason would be 64 bit support for leaderboards. I currently have a workaround using strings that I convert in XCode (and possible Eclipse), but it's not ideal.

**Comment by totebo** [comment]
http://docs.giderosmobile.com/reference/lua/int64#int64
