### ISSUE TITLE
alllow app autoscale option for exported desktop app

### ISSUE THREAD

**Issue by keszegh** [gideros/gideros#96]
it should be possible to export the app to desktop such that the window can be resized with mouse pulling the corner and toggle full-screen with alt-enter. just like the autoscale mode of the player works. 

(a resize event would be also useful for that, but meanwhile at each enterframe checking if the device dimensions changed will do the job for me)

**Comment by ar2rsawseen** [comment]
Btw, there is a resize event:

http://docs.giderosmobile.com/reference/gideros/EventDispatcher/Event.APPLICATION_RESIZE#Event.APPLICATION_RESIZE

**Comment by keszegh** [comment]
good, i've searched for it in the application panel, and so i did not find it (btw it would be good to be able to search in the whole reference).

**Comment by ar2rsawseen** [comment]
yes currently there is a problem with updating bundled reference docs and api annotation

**Comment by keszegh** [comment]
also i'm not sure if a resize event is triggered when in the app a setFullScreen() happens.

**Comment by ar2rsawseen** [comment]
Fixed in https://github.com/gideros/gideros/commit/bd6c59185e4be3eaad20cbc1e8a06c82fbfb63b9
and tested fullscreen emits RESIZE event
