### ISSUE TITLE
enhancement - anti aliasing on Sprite

### ISSUE THREAD

**Issue by piretro** [gideros/gideros#98]
Hi, 
I don't know if this is feasible but it could be useful - at least for isometric tilemaps - to extend anti aliasing filter to Sprite class. 

more info here http://giderosmobile.com/forum/discussion/5800/anti-alias-on-sprite

Thank you

**Comment by hgy29** [comment]
Hi piretro, antialiasing can currently work only at two levels (speaking of OpenGL API): at triangle level, by sampling textures with filtering enabled, like Gideros allows it now, or at full screen level, through the use a MSAA technique (multisample anti-aliasing), the latter meaning that GPU will render, say, four times as many pixels as the screen actually has and then compute a mean value for actual display pixels.

MSAA has several drawbacks: not all devices may support it, frames take longer to render, it uses more GPU memory, etc

Crafting a pixel shader to handle the isometric tilemaps issue seems feasible and more efficient.

**Comment by piretro** [comment]
Thank you, I will try crafting a pixel shader. Expect some questions on gideros forum... :)
